### ISSUE TITLE
Cannot finish a review

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-pull-request-github#1075]
Refs: https://github.com/Microsoft/vscode/issues/71103

I made one comment on my own PR (clicked "Start Review") and now want to finish the review but I get this error:

 ```
ERR Submitting review failed, no pending review for current pull request: 1071.: Error: Submitting review failed, no pending review for current pull request: 1071.
	at T.<anonymous> (/home/bpasero/.vscode-insiders/extensions/github.vscode-pull-request-github-insiders-1.79.0/media/extension.js:15:48820)
	at Generator.next (<anonymous>)
	at s (/home/bpasero/.vscode-insiders/extensions/github.vscode-pull-request-github-insiders-1.79.0/media/extension.js:15:25556)
	at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by RMacfarlane** [comment]
Closing as I haven't been able to reproduce this with the latest version of the extension
