### ISSUE TITLE
TypeError: Cannot read property 'commentThreadCache' of undefined

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode-pull-request-github#1076]
Refs: https://github.com/Microsoft/vscode/issues/71103

I switched from a comment I typed (without submitting) to back to the PR description and got tons of errors in the console:

```
console.ts:134 [Extension Host] rejected promise not handled within 1 second: TypeError: Cannot read property 'commentThreadCache' of undefined (at d.then.t.onMessage.process.on.t.catch.t (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:729:916))
t.log @ console.ts:134
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:399
_invokeHandler @ rpcProtocol.ts:384
_receiveRequest @ rpcProtocol.ts:304
_receiveOneMessage @ rpcProtocol.ts:226
_protocol.onMessage.e @ rpcProtocol.ts:101
fire @ event.ts:584
a @ ipc.net.ts:392
e @ ipc.net.ts:399
fire @ event.ts:584
_receiveMessage @ ipc.net.ts:678
_socketDisposables.push._socketReader.onMessage.e @ ipc.net.ts:549
fire @ event.ts:584
acceptChunk @ ipc.net.ts:212
_register._socket.onData.e @ ipc.net.ts:173
t @ ipc.net.ts:24
emit @ events.js:182
addChunk @ _stream_readable.js:279
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onread @ net.js:636
console.ts:134 [Extension Host] stack trace: TypeError: Cannot read property 'commentThreadCache' of undefined
	at w.<anonymous> (/home/bpasero/.vscode-insiders/extensions/github.vscode-pull-request-github-insiders-1.79.0/media/extension.js:1:145567)
	at Generator.next (<anonymous>)
	at n (/home/bpasero/.vscode-insiders/extensions/github.vscode-pull-request-github-insiders-1.79.0/media/extension.js:1:140735)
	at new Promise (<anonymous>)
	at n (/home/bpasero/.vscode-insiders/extensions/github.vscode-pull-request-github-insiders-1.79.0/media/extension.js:1:140512)
	at w.refreshExistingPREditors (/home/bpasero/.vscode-insiders/extensions/github.vscode-pull-request-github-insiders-1.79.0/media/extension.js:1:145256)
	at w.<anonymous> (/home/bpasero/.vscode-insiders/extensions/github.vscode-pull-request-github-insiders-1.79.0/media/extension.js:1:145136)
	at Generator.next (<anonymous>)
	at n (/home/bpasero/.vscode-insiders/extensions/github.vscode-pull-request-github-insiders-1.79.0/media/extension.js:1:140735)
	at new Promise (<anonymous>)
	at n (/home/bpasero/.vscode-insiders/extensions/github.vscode-pull-request-github-insiders-1.79.0/media/extension.js:1:140512)
	at getChildren.n._disposables.push.i.window.onDidChangeVisibleTextEditors.e (/home/bpasero/.vscode-insiders/extensions/github.vscode-pull-request-github-insiders-1.79.0/media/extension.js:1:145092)
	at u.fire (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:44:708)
	at define.constructor._extHostDocumentsAndEditors.onDidChangeVisibleTextEditors.e (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:575:198)
	at u.fire (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:44:708)
	at u.$acceptDocumentsAndEditorsDelta (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:522:73)
	at d._doInvokeHandler (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:622:11)
	at d._invokeHandler (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:621:716)
	at d._receiveRequest (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:620:394)
	at d._receiveOneMessage (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:619:141)
	at define.constructor._protocol.onMessage.e (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:617:400)
	at u.fire (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:44:708)
	at e (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:40:460)
	at u.fire (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:44:708)
	at a (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:172:467)
	at e (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:172:513)
	at u.fire (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:44:708)
	at y._receiveMessage (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:181:276)
	at define.constructor._socketDisposables.push._socketReader.onMessage.e (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:178:415)
	at u.fire (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:44:708)
	at f.acceptChunk (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:175:35)
	at define.constructor._register._socket.onData.e (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:174:410)
	at Socket.t (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:182:689)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20) (at d.then.t.onMessage.process.on.t.catch.t (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:729:992))
t.log @ console.ts:134
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:399
_invokeHandler @ rpcProtocol.ts:384
_receiveRequest @ rpcProtocol.ts:304
_receiveOneMessage @ rpcProtocol.ts:226
_protocol.onMessage.e @ rpcProtocol.ts:101
fire @ event.ts:584
a @ ipc.net.ts:392
e @ ipc.net.ts:399
fire @ event.ts:584
_receiveMessage @ ipc.net.ts:678
_socketDisposables.push._socketReader.onMessage.e @ ipc.net.ts:549
fire @ event.ts:584
acceptChunk @ ipc.net.ts:212
_register._socket.onData.e @ ipc.net.ts:173
t @ ipc.net.ts:24
emit @ events.js:182
addChunk @ _stream_readable.js:279
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onread @ net.js:636
mainThreadExtensionService.ts:60 [[object Object]]Cannot read property 'commentThreadCache' of undefined
$onExtensionRuntimeError @ mainThreadExtensionService.ts:60
_doInvokeHandler @ rpcProtocol.ts:399
_invokeHandler @ rpcProtocol.ts:384
_receiveRequest @ rpcProtocol.ts:304
_receiveOneMessage @ rpcProtocol.ts:226
_protocol.onMessage.e @ rpcProtocol.ts:101
fire @ event.ts:584
a @ ipc.net.ts:392
e @ ipc.net.ts:399
fire @ event.ts:584
_receiveMessage @ ipc.net.ts:678
_socketDisposables.push._socketReader.onMessage.e @ ipc.net.ts:549
fire @ event.ts:584
acceptChunk @ ipc.net.ts:212
_register._socket.onData.e @ ipc.net.ts:173
t @ ipc.net.ts:24
emit @ events.js:182
addChunk @ _stream_readable.js:279
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onread @ net.js:636
mainThreadExtensionService.ts:61 TypeError: Cannot read property 'commentThreadCache' of undefined
	at w.<anonymous> (/home/bpasero/.vscode-insiders/extensions/github.vscode-pull-request-github-insiders-1.79.0/media/extension.js:1)
	at Generator.next (<anonymous>)
	at n (/home/bpasero/.vscode-insiders/extensions/github.vscode-pull-request-github-insiders-1.79.0/media/extension.js:1)
	at new Promise (<anonymous>)
	at n (/home/bpasero/.vscode-insiders/extensions/github.vscode-pull-request-github-insiders-1.79.0/media/extension.js:1)
	at w.refreshExistingPREditors (/home/bpasero/.vscode-insiders/extensions/github.vscode-pull-request-github-insiders-1.79.0/media/extension.js:1)
	at w.<anonymous> (/home/bpasero/.vscode-insiders/extensions/github.vscode-pull-request-github-insiders-1.79.0/media/extension.js:1)
	at Generator.next (<anonymous>)
	at n (/home/bpasero/.vscode-insiders/extensions/github.vscode-pull-request-github-insiders-1.79.0/media/extension.js:1)
	at new Promise (<anonymous>)
	at n (/home/bpasero/.vscode-insiders/extensions/github.vscode-pull-request-github-insiders-1.79.0/media/extension.js:1)
	at getChildren.n._disposables.push.i.window.onDidChangeVisibleTextEditors.e (/home/bpasero/.vscode-insiders/extensions/github.vscode-pull-request-github-insiders-1.79.0/media/extension.js:1)
	at u.fire (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:44)
	at define.constructor._extHostDocumentsAndEditors.onDidChangeVisibleTextEditors.e (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:575)
	at u.fire (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:44)
	at u.$acceptDocumentsAndEditorsDelta (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:522)
	at d._doInvokeHandler (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:622)
	at d._invokeHandler (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:621)
	at d._receiveRequest (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:620)
	at d._receiveOneMessage (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:619)
	at define.constructor._protocol.onMessage.e (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:617)
	at u.fire (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:44)
	at e (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:40)
	at u.fire (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:44)
	at a (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:172)
	at e (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:172)
	at u.fire (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:44)
	at y._receiveMessage (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:181)
	at define.constructor._socketDisposables.push._socketReader.onMessage.e (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:178)
	at u.fire (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:44)
	at f.acceptChunk (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:175)
	at define.constructor._register._socket.onData.e (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:174)
	at Socket.t (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:182)
	at Socket.emit (events.js:182)
	at addChunk (_stream_readable.js:279)
	at readableAddChunk (_stream_readable.js:264)
	at Socket.Readable.push (_stream_readable.js:219)
	at Pipe.onread (net.js:636)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:61
_doInvokeHandler @ rpcProtocol.ts:399
_invokeHandler @ rpcProtocol.ts:384
_receiveRequest @ rpcProtocol.ts:304
_receiveOneMessage @ rpcProtocol.ts:226
_protocol.onMessage.e @ rpcProtocol.ts:101
fire @ event.ts:584
a @ ipc.net.ts:392
e @ ipc.net.ts:399
fire @ event.ts:584
_receiveMessage @ ipc.net.ts:678
_socketDisposables.push._socketReader.onMessage.e @ ipc.net.ts:549
fire @ event.ts:584
acceptChunk @ ipc.net.ts:212
_register._socket.onData.e @ ipc.net.ts:173
t @ ipc.net.ts:24
emit @ events.js:182
addChunk @ _stream_readable.js:279
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onread @ net.js:636
console.ts:134 [Extension Host] rejected promise not handled within 1 second: TypeError: Cannot read property 'commentThreadCache' of undefined (at d.then.t.onMessage.process.on.t.catch.t (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:729:916))
t.log @ console.ts:134
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:399
_invokeHandler @ rpcProtocol.ts:384
_receiveRequest @ rpcProtocol.ts:304
_receiveOneMessage @ rpcProtocol.ts:226
_protocol.onMessage.e @ rpcProtocol.ts:101
fire @ event.ts:584
a @ ipc.net.ts:392
e @ ipc.net.ts:399
fire @ event.ts:584
_receiveMessage @ ipc.net.ts:678
_socketDisposables.push._socketReader.onMessage.e @ ipc.net.ts:549
fire @ event.ts:584
acceptChunk @ ipc.net.ts:212
_register._socket.onData.e @ ipc.net.ts:173
t @ ipc.net.ts:24
emit @ events.js:182
addChunk @ _stream_readable.js:279
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onread @ net.js:636
console.ts:134 [Extension Host] stack trace: TypeError: Cannot read property 'commentThreadCache' of undefined
	at w.<anonymous> (/home/bpasero/.vscode-insiders/extensions/github.vscode-pull-request-github-insiders-1.79.0/media/extension.js:1:145567)
	at Generator.next (<anonymous>)
	at n (/home/bpasero/.vscode-insiders/extensions/github.vscode-pull-request-github-insiders-1.79.0/media/extension.js:1:140735)
	at new Promise (<anonymous>)
	at n (/home/bpasero/.vscode-insiders/extensions/github.vscode-pull-request-github-insiders-1.79.0/media/extension.js:1:140512)
	at w.refreshExistingPREditors (/home/bpasero/.vscode-insiders/extensions/github.vscode-pull-request-github-insiders-1.79.0/media/extension.js:1:145256)
	at w.<anonymous> (/home/bpasero/.vscode-insiders/extensions/github.vscode-pull-request-github-insiders-1.79.0/media/extension.js:1:145136)
	at Generator.next (<anonymous>)
	at n (/home/bpasero/.vscode-insiders/extensions/github.vscode-pull-request-github-insiders-1.79.0/media/extension.js:1:140735)
	at new Promise (<anonymous>)
	at n (/home/bpasero/.vscode-insiders/extensions/github.vscode-pull-request-github-insiders-1.79.0/media/extension.js:1:140512)
	at getChildren.n._disposables.push.i.window.onDidChangeVisibleTextEditors.e (/home/bpasero/.vscode-insiders/extensions/github.vscode-pull-request-github-insiders-1.79.0/media/extension.js:1:145092)
	at u.fire (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:44:708)
	at define.constructor._extHostDocumentsAndEditors.onDidChangeVisibleTextEditors.e (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:575:198)
	at u.fire (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:44:708)
	at u.$acceptDocumentsAndEditorsDelta (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:522:73)
	at d._doInvokeHandler (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:622:11)
	at d._invokeHandler (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:621:716)
	at d._receiveRequest (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:620:394)
	at d._receiveOneMessage (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:619:141)
	at define.constructor._protocol.onMessage.e (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:617:400)
	at u.fire (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:44:708)
	at e (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:40:460)
	at u.fire (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:44:708)
	at a (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:172:467)
	at e (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:172:513)
	at u.fire (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:44:708)
	at y._receiveMessage (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:181:276)
	at define.constructor._socketDisposables.push._socketReader.onMessage.e (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:178:415)
	at u.fire (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:44:708)
	at f.acceptChunk (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:175:35)
	at define.constructor._register._socket.onData.e (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:174:410)
	at Socket.t (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:182:689)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20) (at d.then.t.onMessage.process.on.t.catch.t (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:729:992))
t.log @ console.ts:134
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:399
_invokeHandler @ rpcProtocol.ts:384
_receiveRequest @ rpcProtocol.ts:304
_receiveOneMessage @ rpcProtocol.ts:226
_protocol.onMessage.e @ rpcProtocol.ts:101
fire @ event.ts:584
a @ ipc.net.ts:392
e @ ipc.net.ts:399
fire @ event.ts:584
_receiveMessage @ ipc.net.ts:678
_socketDisposables.push._socketReader.onMessage.e @ ipc.net.ts:549
fire @ event.ts:584
acceptChunk @ ipc.net.ts:212
_register._socket.onData.e @ ipc.net.ts:173
t @ ipc.net.ts:24
emit @ events.js:182
addChunk @ _stream_readable.js:279
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onread @ net.js:636
mainThreadExtensionService.ts:60 [[object Object]]Cannot read property 'commentThreadCache' of undefined
$onExtensionRuntimeError @ mainThreadExtensionService.ts:60
_doInvokeHandler @ rpcProtocol.ts:399
_invokeHandler @ rpcProtocol.ts:384
_receiveRequest @ rpcProtocol.ts:304
_receiveOneMessage @ rpcProtocol.ts:226
_protocol.onMessage.e @ rpcProtocol.ts:101
fire @ event.ts:584
a @ ipc.net.ts:392
e @ ipc.net.ts:399
fire @ event.ts:584
_receiveMessage @ ipc.net.ts:678
_socketDisposables.push._socketReader.onMessage.e @ ipc.net.ts:549
fire @ event.ts:584
acceptChunk @ ipc.net.ts:212
_register._socket.onData.e @ ipc.net.ts:173
t @ ipc.net.ts:24
emit @ events.js:182
addChunk @ _stream_readable.js:279
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onread @ net.js:636
mainThreadExtensionService.ts:61 TypeError: Cannot read property 'commentThreadCache' of undefined
	at w.<anonymous> (/home/bpasero/.vscode-insiders/extensions/github.vscode-pull-request-github-insiders-1.79.0/media/extension.js:1)
	at Generator.next (<anonymous>)
	at n (/home/bpasero/.vscode-insiders/extensions/github.vscode-pull-request-github-insiders-1.79.0/media/extension.js:1)
	at new Promise (<anonymous>)
	at n (/home/bpasero/.vscode-insiders/extensions/github.vscode-pull-request-github-insiders-1.79.0/media/extension.js:1)
	at w.refreshExistingPREditors (/home/bpasero/.vscode-insiders/extensions/github.vscode-pull-request-github-insiders-1.79.0/media/extension.js:1)
	at w.<anonymous> (/home/bpasero/.vscode-insiders/extensions/github.vscode-pull-request-github-insiders-1.79.0/media/extension.js:1)
	at Generator.next (<anonymous>)
	at n (/home/bpasero/.vscode-insiders/extensions/github.vscode-pull-request-github-insiders-1.79.0/media/extension.js:1)
	at new Promise (<anonymous>)
	at n (/home/bpasero/.vscode-insiders/extensions/github.vscode-pull-request-github-insiders-1.79.0/media/extension.js:1)
	at getChildren.n._disposables.push.i.window.onDidChangeVisibleTextEditors.e (/home/bpasero/.vscode-insiders/extensions/github.vscode-pull-request-github-insiders-1.79.0/media/extension.js:1)
	at u.fire (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:44)
	at define.constructor._extHostDocumentsAndEditors.onDidChangeVisibleTextEditors.e (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:575)
	at u.fire (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:44)
	at u.$acceptDocumentsAndEditorsDelta (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:522)
	at d._doInvokeHandler (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:622)
	at d._invokeHandler (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:621)
	at d._receiveRequest (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:620)
	at d._receiveOneMessage (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:619)
	at define.constructor._protocol.onMessage.e (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:617)
	at u.fire (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:44)
	at e (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:40)
	at u.fire (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:44)
	at a (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:172)
	at e (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:172)
	at u.fire (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:44)
	at y._receiveMessage (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:181)
	at define.constructor._socketDisposables.push._socketReader.onMessage.e (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:178)
	at u.fire (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:44)
	at f.acceptChunk (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:175)
	at define.constructor._register._socket.onData.e (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:174)
	at Socket.t (/snap/code-insiders/98/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:182)
	at Socket.emit (events.js:182)
	at addChunk (_stream_readable.js:279)
	at readableAddChunk (_stream_readable.js:264)
	at Socket.Readable.push (_stream_readable.js:219)
	at Pipe.onread (net.js:636)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:61
_doInvokeHandler @ rpcProtocol.ts:399
_invokeHandler @ rpcProtocol.ts:384
_receiveRequest @ rpcProtocol.ts:304
_receiveOneMessage @ rpcProtocol.ts:226
_protocol.onMessage.e @ rpcProtocol.ts:101
fire @ event.ts:584
a @ ipc.net.ts:392
e @ ipc.net.ts:399
fire @ event.ts:584
_receiveMessage @ ipc.net.ts:678
_socketDisposables.push._socketReader.onMessage.e @ ipc.net.ts:549
fire @ event.ts:584
acceptChunk @ ipc.net.ts:212
_register._socket.onData.e @ ipc.net.ts:173
t @ ipc.net.ts:24
emit @ events.js:182
addChunk @ _stream_readable.js:279
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onread @ net.js:636
```

**Comment by RMacfarlane** [comment]
Alternate repro steps:
1. Check out a PR
2. In the "GitHub Pull Requests" tree, open a file under the checked out PR (or switch from an opened file to something else)
