### ISSUE TITLE
Comments gutter is unclear

### ISSUE THREAD

**Issue by svipas** [microsoft/vscode-pull-request-github#1228]
- Extension version: 0.8.0
- VSCode Version: 1.35.0
- OS: macOS

Even if I have `"scm.diffDecorations": "none"` setting this issue occurs.

https://streamable.com/27dve - just look at this from the beginning.

**After disabling this extension issue doesn't occur anymore.**

**Comment by svipas** [comment]
I don't know if it's related but I checked developer tools and saw this message:

```
  ERR unknown handler: Error: unknown handler
    at I.$unregisterCommentController (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4518:429)
    at u._doInvokeHandler (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3293:700)
    at u._invokeHandler (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3293:392)
    at u._receiveRequest (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3292:61)
    at u._receiveOneMessage (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3290:890)
    at _protocol.onMessage.e (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3289:136)
    at d.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:77:983)
    at a (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:322:248)
    at e (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:322:294)
    at d.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:77:983)
    at S._receiveMessage (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:331:276)
    at S._socketDisposables.push._socketReader.onMessage.e (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:328:437)
    at d.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:77:983)
    at g.acceptChunk (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:325:17)
    at _register._socket.onData.e (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:324:372)
    at Socket.t (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:333:519)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:279:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onread (net.js:636:20)
```

**Comment by svipas** [comment]
Repository to check the issue https://github.com/svipas/prettier-vscode

**Comment by svipas** [comment]
OMG, I'm such a noob :D It's for comments... Maybe there's a way how to disable them? I also see it doesn't respect `"scm.diffDecorationsGutterWidth":` setting.

**Comment by RMacfarlane** [comment]
@svipas Thanks for filing this! It sounds like there are 3 separate issues here
- Comments gutter is unclear
- Extension doesn't respect "scm.diffDecorationsGutterWidth": setting
- there's a problem with exiting review mode?

I'll update the title of this one, could you file new issues for the other two so that we can handle them independently?

**Comment by svipas** [comment]
@RMacfarlane you're correct, the second one can be also merged with `"scm.diffDecorations": "none"` because it's doesn't respect it too.

Separated issues: https://github.com/microsoft/vscode-pull-request-github/issues/1235 & https://github.com/microsoft/vscode-pull-request-github/issues/1236

Also, remember about the errors I mentioned above. Comments gutter is really unclear, also it would be perfect if `"scm.diffDecorations": "none"` and I'm into review mode I can still comment on the current line with a command from command palette, I keep my editor as minimal as possible, but I still want to use these features.

**Comment by alexr00** [comment]
Since this issue was filed we have:
- improved the comments gutter
- added a setting to disable it
- improved review mode
