### ISSUE TITLE
Unable to build from source

### ISSUE THREAD

**Issue by sreed101** [microsoft/vscode-pull-request-github#1250]
- Extension version: Latest master
- VSCode Version: 1.35.1
- OS: Fedora Linux 30

Steps to Reproduce:

1. yarn
2. yarn test

```
[scott@localhost vscode-pull-request-github]$ npm -v
5.6.0
[scott@localhost vscode-pull-request-github]$ node -v
v8.9.4
[scott@localhost vscode-pull-request-github]$ yarn
yarn install v1.16.0
[1/5] Validating package.json...
warning vscode-pull-request-github@0.8.0: The engine "vscode" appears to be invalid.
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
[5/5] Building fresh packages...
$ node ./node_modules/vscode/bin/install
Detected VS Code engine version: ^1.35.0
Found minimal version that qualifies engine range: 1.35.0
Fetching vscode.d.ts from: https://raw.githubusercontent.com/Microsoft/vscode/553cfb2c2205db5f15f3ee8395bbd5cf066d357d/src/vs/vscode.d.ts
vscode.d.ts successfully installed!

Done in 4.59s.
[scott@localhost vscode-pull-request-github]$ yarn test
yarn run v1.16.0
warning vscode-pull-request-github@0.8.0: The engine "vscode" appears to be invalid.
$ ./test.sh
Running webpack
[tslint-plugin] Starting linter in separate process...
[tslint-plugin] Linting complete.
Hash: 7472aede563a9201f84ff7a2cdf563c8d8f0b59f
Version: webpack 4.12.0
Child extension:
    Hash: 7472aede563a9201f84f
    Time: 18690ms
    Built at: 2019-06-27 12:24:52
               Asset      Size     Chunks             Chunk Names
        extension.js   2.9 MiB  extension  [emitted]  extension
    extension.js.map  3.22 MiB  extension  [emitted]  extension
    Entrypoint extension = extension.js extension.js.map
    [./src/api/api1.ts] 2.56 KiB {extension} [built]
    [./src/authentication/keychain.ts] 5.33 KiB {extension} [built]
    [./src/authentication/vsConfiguration.ts] 2.01 KiB {extension} [built]
    [./src/common/logger.ts] 1.89 KiB {extension} [built]
    [./src/common/resources.ts] 5.45 KiB {extension} [built]
    [./src/common/telemetry.ts] 7.82 KiB {extension} [built]
    [./src/common/uri.ts] 2.85 KiB {extension} [built]
    [./src/common/utils.ts] 13.8 KiB {extension} [built]
    [./src/extension.ts] 5.29 KiB {extension} [built]
    [./src/gitProviders/api.ts] 989 bytes {extension} [built]
    [./src/github/pullRequestManager.ts] 68.7 KiB {extension} [built]
    [./src/view/fileTypeDecorationProvider.ts] 2.13 KiB {extension} [built]
    [./src/view/prsTreeDataProvider.ts] 7.84 KiB {extension} [built]
    [./src/view/reviewManager.ts] 34.8 KiB {extension} [built]
    [vscode] external "vscode" 42 bytes {extension} [built]
        + 477 hidden modules
    
    ERROR in /home/scott/src/vscode-pull-request-github/src/github/utils.ts
    ./src/github/utils.ts
    [tsl] ERROR in /home/scott/src/vscode-pull-request-github/src/github/utils.ts(33,6)
          TS2322: Type '{ _rawComment: Comment; commentId: string; body: MarkdownString; selectCommand: Command | undefined; userName: string; userIconPath: Uri | undefined; label: string | undefined; commentReactions: { ...; }[]; }' is not assignable to type 'Comment & { _rawComment: Comment; }'.
      Type '{ _rawComment: Comment; commentId: string; body: MarkdownString; selectCommand: Command | undefined; userName: string; userIconPath: Uri | undefined; label: string | undefined; commentReactions: { ...; }[]; }' is missing the following properties from type 'Comment': mode, author
    
    ERROR in /home/scott/src/vscode-pull-request-github/src/github/utils.ts
    ./src/github/utils.ts
    [tsl] ERROR in /home/scott/src/vscode-pull-request-github/src/github/utils.ts(54,3)
          TS2345: Argument of type 'readonly Comment[]' is not assignable to parameter of type 'Comment[]'.
      Type 'readonly Comment[]' is missing the following properties from type 'Comment[]': pop, push, reverse, shift, and 6 more.
    
    ERROR in /home/scott/src/vscode-pull-request-github/src/view/reviewDocumentCommentProvider.ts
    ./src/view/reviewDocumentCommentProvider.ts
    [tsl] ERROR in /home/scott/src/vscode-pull-request-github/src/view/reviewDocumentCommentProvider.ts(54,12)
          TS2345: Argument of type '{ threadId: string; resource: Uri; range: Range; comments: (Comment & { _rawComment: Comment; })[]; collapsibleState: CommentThreadCollapsibleState; }' is not assignable to parameter of type 'CommentThread'.
      Property 'uri' is missing in type '{ threadId: string; resource: Uri; range: Range; comments: (Comment & { _rawComment: Comment; })[]; collapsibleState: CommentThreadCollapsibleState; }' but required in type 'CommentThread'.
    
    ERROR in /home/scott/src/vscode-pull-request-github/src/view/reviewDocumentCommentProvider.ts
    ./src/view/reviewDocumentCommentProvider.ts
    [tsl] ERROR in /home/scott/src/vscode-pull-request-github/src/view/reviewDocumentCommentProvider.ts(539,13)
          TS2345: Argument of type '{ threadId: string; resource: Uri; range: Range; comments: (Comment & { _rawComment: Comment; })[]; collapsibleState: CommentThreadCollapsibleState; }' is not assignable to parameter of type 'CommentThread'.
      Property 'uri' is missing in type '{ threadId: string; resource: Uri; range: Range; comments: (Comment & { _rawComment: Comment; })[]; collapsibleState: CommentThreadCollapsibleState; }' but required in type 'CommentThread'.
    
    ERROR in /home/scott/src/vscode-pull-request-github/src/view/reviewDocumentCommentProvider.ts
    ./src/view/reviewDocumentCommentProvider.ts
    [tsl] ERROR in /home/scott/src/vscode-pull-request-github/src/view/reviewDocumentCommentProvider.ts(615,13)
          TS2345: Argument of type '{ threadId: string; resource: Uri; range: Range; comments: (Comment & { _rawComment: Comment; })[]; collapsibleState: CommentThreadCollapsibleState.Expanded; }' is not assignable to parameter of type 'CommentThread'.
      Property 'uri' is missing in type '{ threadId: string; resource: Uri; range: Range; comments: (Comment & { _rawComment: Comment; })[]; collapsibleState: CommentThreadCollapsibleState.Expanded; }' but required in type 'CommentThread'.
    
    ERROR in /home/scott/src/vscode-pull-request-github/src/view/reviewDocumentCommentProvider.ts
    ./src/view/reviewDocumentCommentProvider.ts
    [tsl] ERROR in /home/scott/src/vscode-pull-request-github/src/view/reviewDocumentCommentProvider.ts(922,22)
          TS2551: Property 'splice' does not exist on type 'readonly Comment[]'. Did you mean 'slice'?
    
    ERROR in /home/scott/src/vscode-pull-request-github/src/view/treeNodes/pullRequestNode.ts
    ./src/view/treeNodes/pullRequestNode.ts
    [tsl] ERROR in /home/scott/src/vscode-pull-request-github/src/view/treeNodes/pullRequestNode.ts(66,16)
          TS2345: Argument of type '{ threadId: string; resource: Uri; range: Range; comments: (Comment & { _rawComment: Comment; })[]; collapsibleState: CommentThreadCollapsibleState.Expanded; }' is not assignable to parameter of type 'CommentThread'.
      Property 'uri' is missing in type '{ threadId: string; resource: Uri; range: Range; comments: (Comment & { _rawComment: Comment; })[]; collapsibleState: CommentThreadCollapsibleState.Expanded; }' but required in type 'CommentThread'.
    
    ERROR in /home/scott/src/vscode-pull-request-github/src/view/treeNodes/pullRequestNode.ts
    ./src/view/treeNodes/pullRequestNode.ts
    [tsl] ERROR in /home/scott/src/vscode-pull-request-github/src/view/treeNodes/pullRequestNode.ts(110,31)
          TS2339: Property 'value' does not exist on type 'string | MarkdownString'.
      Property 'value' does not exist on type 'string'.
    
    ERROR in /home/scott/src/vscode-pull-request-github/src/view/treeNodes/pullRequestNode.ts
    ./src/view/treeNodes/pullRequestNode.ts
    [tsl] ERROR in /home/scott/src/vscode-pull-request-github/src/view/treeNodes/pullRequestNode.ts(110,57)
          TS2339: Property 'value' does not exist on type 'string | MarkdownString'.
      Property 'value' does not exist on type 'string'.
    
    ERROR in /home/scott/src/vscode-pull-request-github/src/view/treeNodes/pullRequestNode.ts
    ./src/view/treeNodes/pullRequestNode.ts
    [tsl] ERROR in /home/scott/src/vscode-pull-request-github/src/view/treeNodes/pullRequestNode.ts(562,85)
          TS2345: Argument of type 'readonly Comment[]' is not assignable to parameter of type 'Comment[]'.
    
    ERROR in /home/scott/src/vscode-pull-request-github/src/view/treeNodes/pullRequestNode.ts
    ./src/view/treeNodes/pullRequestNode.ts
    [tsl] ERROR in /home/scott/src/vscode-pull-request-github/src/view/treeNodes/pullRequestNode.ts(563,47)
          TS2345: Argument of type 'readonly Comment[]' is not assignable to parameter of type 'Comment[]'.
    
    ERROR in /home/scott/src/vscode-pull-request-github/src/view/treeNodes/pullRequestNode.ts
    ./src/view/treeNodes/pullRequestNode.ts
    [tsl] ERROR in /home/scott/src/vscode-pull-request-github/src/view/treeNodes/pullRequestNode.ts(686,20)
          TS2551: Property 'splice' does not exist on type 'readonly Comment[]'. Did you mean 'slice'?
    
    ERROR in /home/scott/src/vscode-pull-request-github/src/view/treeNodes/pullRequestNode.ts
    ./src/view/treeNodes/pullRequestNode.ts
    [tsl] ERROR in /home/scott/src/vscode-pull-request-github/src/view/treeNodes/pullRequestNode.ts(687,45)
          TS2345: Argument of type 'readonly Comment[]' is not assignable to parameter of type 'Comment[]'.
    
    ERROR in /home/scott/src/vscode-pull-request-github/src/view/treeNodes/pullRequestNode.ts
    ./src/view/treeNodes/pullRequestNode.ts
    [tsl] ERROR in /home/scott/src/vscode-pull-request-github/src/view/treeNodes/pullRequestNode.ts(711,21)
          TS2551: Property 'splice' does not exist on type 'readonly Comment[]'. Did you mean 'slice'?
    
    ERROR in /home/scott/src/vscode-pull-request-github/src/view/treeNodes/pullRequestNode.ts
    ./src/view/treeNodes/pullRequestNode.ts
    [tsl] ERROR in /home/scott/src/vscode-pull-request-github/src/view/treeNodes/pullRequestNode.ts(712,46)
          TS2345: Argument of type 'readonly Comment[]' is not assignable to parameter of type 'Comment[]'.
    
    ERROR in /home/scott/src/vscode-pull-request-github/src/view/treeNodes/pullRequestNode.ts
    ./src/view/treeNodes/pullRequestNode.ts
    [tsl] ERROR in /home/scott/src/vscode-pull-request-github/src/view/treeNodes/pullRequestNode.ts(853,47)
          TS2345: Argument of type 'readonly Comment[]' is not assignable to parameter of type 'Comment[]'.
Child webview:
    Hash: f7a2cdf563c8d8f0b59f
    Time: 15002ms
    Built at: 2019-06-27 12:24:49
       Asset      Size  Chunks             Chunk Names
    index.js  5.16 MiB   index  [emitted]  index
    Entrypoint index = index.js
    [./node_modules/css-loader/index.js!./preview-src/index.css] ./node_modules/css-loader!./preview-src/index.css 20 KiB {index} [built]
    [./preview-src/app.tsx] 766 bytes {index} [built]
    [./preview-src/cache.ts] 1.09 KiB {index} [built]
    [./preview-src/comment.tsx] 8.12 KiB {index} [built]
    [./preview-src/context.tsx] 6.68 KiB {index} [built]
    [./preview-src/header.tsx] 4.9 KiB {index} [built]
    [./preview-src/index.css] 1.05 KiB {index} [built]
    [./preview-src/index.ts] 523 bytes {index} [built]
    [./preview-src/merge.tsx] 8.08 KiB {index} [built]
    [./preview-src/message.ts] 1.71 KiB {index} [built]
    [./preview-src/overview.tsx] 1.04 KiB {index} [built]
    [./preview-src/sidebar.tsx] 3.68 KiB {index} [built]
    [./preview-src/timeline.tsx] 6.54 KiB {index} [built]
    [./preview-src/timestamp.tsx] 328 bytes {index} [built]
    [./src/common/timelineEvent.ts] 1.65 KiB {index} [built]
        + 114 hidden modules
Transpiling src/
node_modules/vscode/vscode.d.ts:8956:3 - error TS2300: Duplicate identifier 'Collapsed'.

8956    Collapsed = 0,
        ~~~~~~~~~

  src/typings/vscode.proposed.d.ts:735:3
    735         Collapsed = 0,
                ~~~~~~~~~
    'Collapsed' was also declared here.

node_modules/vscode/vscode.d.ts:8961:3 - error TS2300: Duplicate identifier 'Expanded'.

8961    Expanded = 1
        ~~~~~~~~

  src/typings/vscode.proposed.d.ts:739:3
    739         Expanded = 1
                ~~~~~~~~
    'Expanded' was also declared here.

node_modules/vscode/vscode.d.ts:9003:3 - error TS2687: All declarations of 'collapsibleState' must have identical modifiers.

9003    collapsibleState: CommentThreadCollapsibleState;
        ~~~~~~~~~~~~~~~~

src/github/utils.ts:33:6 - error TS2322: Type '{ _rawComment: Comment; commentId: string; body: MarkdownString; selectCommand: Command | undefined; userName: string; userIconPath: Uri | undefined; label: string | undefined; commentReactions: { ...; }[]; }' is not assignable to type 'Comment & { _rawComment: Comment; }'.
  Type '{ _rawComment: Comment; commentId: string; body: MarkdownString; selectCommand: Command | undefined; userName: string; userIconPath: Uri | undefined; label: string | undefined; commentReactions: { ...; }[]; }' is missing the following properties from type 'Comment': mode, author

33  let vscodeComment: vscode.Comment & { _rawComment: Comment } = {
        ~~~~~~~~~~~~~

src/github/utils.ts:54:3 - error TS2345: Argument of type 'readonly Comment[]' is not assignable to parameter of type 'Comment[]'.

54      thread.comments
        ~~~~~~~~~~~~~~~

src/typings/vscode.proposed.d.ts:735:3 - error TS2300: Duplicate identifier 'Collapsed'.

735     Collapsed = 0,
        ~~~~~~~~~

  node_modules/vscode/vscode.d.ts:8956:3
    8956        Collapsed = 0,
                ~~~~~~~~~
    'Collapsed' was also declared here.

src/typings/vscode.proposed.d.ts:739:3 - error TS2300: Duplicate identifier 'Expanded'.

739     Expanded = 1
        ~~~~~~~~

  node_modules/vscode/vscode.d.ts:8961:3
    8961        Expanded = 1
                ~~~~~~~~
    'Expanded' was also declared here.

src/typings/vscode.proposed.d.ts:770:3 - error TS2717: Subsequent property declarations must have the same type.  Property 'comments' must be of type 'readonly Comment[]', but here has type 'Comment[]'.

770     comments: Comment[];
        ~~~~~~~~

src/typings/vscode.proposed.d.ts:792:3 - error TS2687: All declarations of 'collapsibleState' must have identical modifiers.

792     collapsibleState?: CommentThreadCollapsibleState;
        ~~~~~~~~~~~~~~~~

src/typings/vscode.proposed.d.ts:792:3 - error TS2717: Subsequent property declarations must have the same type.  Property 'collapsibleState' must be of type 'CommentThreadCollapsibleState', but here has type 'CommentThreadCollapsibleState | undefined'.

792     collapsibleState?: CommentThreadCollapsibleState;
        ~~~~~~~~~~~~~~~~

src/typings/vscode.proposed.d.ts:803:3 - error TS2386: Overload signatures must all be optional or required.

803     dispose?(): void;
        ~~~~~~~

src/typings/vscode.proposed.d.ts:818:3 - error TS2717: Subsequent property declarations must have the same type.  Property 'body' must be of type 'string | MarkdownString', but here has type 'MarkdownString'.

818     body: MarkdownString;
        ~~~~

src/view/reviewDocumentCommentProvider.ts:54:12 - error TS2345: Argument of type '{ threadId: string; resource: Uri; range: Range; comments: (Comment & { _rawComment: Comment; })[]; collapsibleState: CommentThreadCollapsibleState; }' is not assignable to parameter of type 'CommentThread'.
  Property 'uri' is missing in type '{ threadId: string; resource: Uri; range: Range; comments: (Comment & { _rawComment: Comment; })[]; collapsibleState: CommentThreadCollapsibleState; }' but required in type 'CommentThread'.

 54     ret.push({
                 ~
 55             threadId: firstComment.id.toString(),
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
... 
 59             collapsibleState
    ~~~~~~~~~~~~~~~~~~~
 60     });
    ~~~

  node_modules/vscode/vscode.d.ts:8986:12
    8986        readonly uri: Uri;
                         ~~~
    'uri' is declared here.

src/view/reviewDocumentCommentProvider.ts:539:13 - error TS2345: Argument of type '{ threadId: string; resource: Uri; range: Range; comments: (Comment & { _rawComment: Comment; })[]; collapsibleState: CommentThreadCollapsibleState; }' is not assignable to parameter of type 'CommentThread'.
  Property 'uri' is missing in type '{ threadId: string; resource: Uri; range: Range; comments: (Comment & { _rawComment: Comment; })[]; collapsibleState: CommentThreadCollapsibleState; }' but required in type 'CommentThread'.

539             ret.push({
                         ~
540                     threadId: firstComment.id.toString(),
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
... 
554                     collapsibleState: collapsibleState
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
555             });
    ~~~~

  node_modules/vscode/vscode.d.ts:8986:12
    8986        readonly uri: Uri;
                         ~~~
    'uri' is declared here.

src/view/reviewDocumentCommentProvider.ts:615:13 - error TS2345: Argument of type '{ threadId: string; resource: Uri; range: Range; comments: (Comment & { _rawComment: Comment; })[]; collapsibleState: CommentThreadCollapsibleState.Expanded; }' is not assignable to parameter of type 'CommentThread'.
  Property 'uri' is missing in type '{ threadId: string; resource: Uri; range: Range; comments: (Comment & { _rawComment: Comment; })[]; collapsibleState: CommentThreadCollapsibleState.Expanded; }' but required in type 'CommentThread'.

615             ret.push({
                         ~
616                     threadId: String(firstComment.id),
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
... 
623                     collapsibleState: vscode.CommentThreadCollapsibleState.Expanded
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
624             });
    ~~~~

  node_modules/vscode/vscode.d.ts:8986:12
    8986        readonly uri: Uri;
                         ~~~
    'uri' is declared here.

src/view/reviewDocumentCommentProvider.ts:922:22 - error TS2551: Property 'splice' does not exist on type 'readonly Comment[]'. Did you mean 'slice'?

922                             thread.comments.splice(index, 1);
                                                ~~~~~~

  node_modules/typescript/lib/lib.es5.d.ts:1119:5
    1119     slice(start?: number, end?: number): T[];
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    'slice' is declared here.

src/view/treeNodes/pullRequestNode.ts:66:16 - error TS2345: Argument of type '{ threadId: string; resource: Uri; range: Range; comments: (Comment & { _rawComment: Comment; })[]; collapsibleState: CommentThreadCollapsibleState.Expanded; }' is not assignable to parameter of type 'CommentThread'.
  Property 'uri' is missing in type '{ threadId: string; resource: Uri; range: Range; comments: (Comment & { _rawComment: Comment; })[]; collapsibleState: CommentThreadCollapsibleState.Expanded; }' but required in type 'CommentThread'.

 66     threads.push({
                     ~
 67             threadId: firstComment.id.toString(),
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
... 
 71             collapsibleState: vscode.CommentThreadCollapsibleState.Expanded,
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 72     });
    ~~~

  node_modules/vscode/vscode.d.ts:8986:12
    8986        readonly uri: Uri;
                         ~~~
    'uri' is declared here.

src/view/treeNodes/pullRequestNode.ts:110:31 - error TS2339: Property 'value' does not exist on type 'string | MarkdownString'.
  Property 'value' does not exist on type 'string'.

110     if (matchingComment[0].body.value !== oldComment.body.value) {
                                    ~~~~~

src/view/treeNodes/pullRequestNode.ts:110:57 - error TS2339: Property 'value' does not exist on type 'string | MarkdownString'.
  Property 'value' does not exist on type 'string'.

110     if (matchingComment[0].body.value !== oldComment.body.value) {
                                                              ~~~~~

src/view/treeNodes/pullRequestNode.ts:562:85 - error TS2345: Argument of type 'readonly Comment[]' is not assignable to parameter of type 'Comment[]'.

562                             if (match.comments.length !== thread.comments.length || commentsEditedInThread(matchingCommentThread[0].comments, thread.comments)) {
                                                                                                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/view/treeNodes/pullRequestNode.ts:563:47 - error TS2345: Argument of type 'readonly Comment[]' is not assignable to parameter of type 'Comment[]'.

563                                     this.updateCommentThreadComments(match, thread.comments);
                                                                                ~~~~~~~~~~~~~~~

src/view/treeNodes/pullRequestNode.ts:686:20 - error TS2551: Property 'splice' does not exist on type 'readonly Comment[]'. Did you mean 'slice'?

686             thread.comments.splice(vscodeCommentIndex, 1, vscodeComment);
                                ~~~~~~

  node_modules/typescript/lib/lib.es5.d.ts:1119:5
    1119     slice(start?: number, end?: number): T[];
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    'slice' is declared here.

src/view/treeNodes/pullRequestNode.ts:687:45 - error TS2345: Argument of type 'readonly Comment[]' is not assignable to parameter of type 'Comment[]'.
  Type 'readonly Comment[]' is missing the following properties from type 'Comment[]': pop, push, reverse, shift, and 6 more.

687             this.updateCommentThreadComments(thread, thread.comments);
                                                         ~~~~~~~~~~~~~~~

src/view/treeNodes/pullRequestNode.ts:711:21 - error TS2551: Property 'splice' does not exist on type 'readonly Comment[]'. Did you mean 'slice'?

711                     thread.comments.splice(index, 1);
                                        ~~~~~~

  node_modules/typescript/lib/lib.es5.d.ts:1119:5
    1119     slice(start?: number, end?: number): T[];
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    'slice' is declared here.

src/view/treeNodes/pullRequestNode.ts:712:46 - error TS2345: Argument of type 'readonly Comment[]' is not assignable to parameter of type 'Comment[]'.

712                     this.updateCommentThreadComments(thread, thread.comments);
                                                                 ~~~~~~~~~~~~~~~

src/view/treeNodes/pullRequestNode.ts:853:47 - error TS2345: Argument of type 'readonly Comment[]' is not assignable to parameter of type 'Comment[]'.

853                             this.updateCommentThreadComments(thread, thread.comments);
                                                                         ~~~~~~~~~~~~~~~


Found 26 errors.


Transpiling preview-src/

Launching test runner
### VS Code Extension Test Run ###

Current working directory: /home/scott/src/vscode-pull-request-github
Downloading VS Code 1.35.1 into .vscode-test/vscode-1.35.1.
Downloading VS Code from: https://update.code.visualstudio.com/1.35.1/linux-x64/stable
Downloaded VS Code 1.35.1
Running extension tests: /home/scott/src/vscode-pull-request-github/.vscode-test/vscode-1.35.1/VSCode-linux-x64/code /home/scott/src/vscode-pull-request-github/out/test --extensionDevelopmentPath=/home/scott/src/vscode-pull-request-github --extensionTestsPath=/home/scott/src/vscode-pull-request-github/out/test --locale=en
[main 2019-06-27T16:25:18.651Z] Running extension tests from the command line is currently only supported if no other instance of Code is running.

[main 2019-06-27T16:25:18.653Z] Error: Running extension tests from the command line is currently only supported if no other instance of Code is running.
    at U.<anonymous> (/home/scott/src/vscode-pull-request-github/.vscode-test/vscode-1.35.1/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:500:716)
    at Generator.next (<anonymous>)
    at s (/home/scott/src/vscode-pull-request-github/.vscode-test/vscode-1.35.1/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:13:221)
    at process._tickCallback (internal/process/next_tick.js:68:7)

Tests exited with code: 1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[scott@localhost vscode-pull-request-github]$
```

**Comment by RMacfarlane** [comment]
@sreed101 Sorry! This should be fixed with https://github.com/microsoft/vscode-pull-request-github/commit/e71dd72fbdc2881634bd9347ca2a3f0bb6bc16b2, we previously bumped the engine version of VS Code without fully adopting the new shape of an API.
