### ISSUE TITLE
Can't authenticate

### ISSUE THREAD

**Issue by cappslock** [microsoft/vscode-pull-request-github#1251]
Issue Type: <b>Bug</b>

When attempting to sign in, nothing happens besides an error message: "Error signing in to github.com".

This is logged to the output:

```
[Info] Looking for git repository
[Info] Git repository found, initializing review manager and pr tree view.
[Info] Found GitHub remote
[Info] Error signing in to github.com: TypeError: Cannot set property 'text' of undefined
[Info] TypeError: Cannot set property 'text' of undefined
	at t.CredentialStore.willStartLogin (/Users/eric/.vscode/extensions/github.vscode-pull-request-github-0.8.0/media/extension.js:36:358635)
	at t.CredentialStore.<anonymous> (/Users/eric/.vscode/extensions/github.vscode-pull-request-github-0.8.0/media/extension.js:36:356720)
	at Generator.next (<anonymous>)
	at n (/Users/eric/.vscode/extensions/github.vscode-pull-request-github-0.8.0/media/extension.js:36:354529)
	at new Promise (<anonymous>)
	at n (/Users/eric/.vscode/extensions/github.vscode-pull-request-github-0.8.0/media/extension.js:36:354306)
	at t.CredentialStore.login (/Users/eric/.vscode/extensions/github.vscode-pull-request-github-0.8.0/media/extension.js:36:356515)
	at t.CredentialStore.<anonymous> (/Users/eric/.vscode/extensions/github.vscode-pull-request-github-0.8.0/media/extension.js:36:356396)
	at Generator.next (<anonymous>)
	at o (/Users/eric/.vscode/extensions/github.vscode-pull-request-github-0.8.0/media/extension.js:36:354362)
[Info] Error signing in to github.com: TypeError: Cannot set property 'text' of undefined
[Info] TypeError: Cannot set property 'text' of undefined
	at t.CredentialStore.willStartLogin (/Users/eric/.vscode/extensions/github.vscode-pull-request-github-0.8.0/media/extension.js:36:358635)
	at t.CredentialStore.<anonymous> (/Users/eric/.vscode/extensions/github.vscode-pull-request-github-0.8.0/media/extension.js:36:356720)
	at Generator.next (<anonymous>)
	at o (/Users/eric/.vscode/extensions/github.vscode-pull-request-github-0.8.0/media/extension.js:36:354362)
[Info] Error signing in to github.com: TypeError: Cannot set property 'text' of undefined
[Info] TypeError: Cannot set property 'text' of undefined
	at t.CredentialStore.willStartLogin (/Users/eric/.vscode/extensions/github.vscode-pull-request-github-0.8.0/media/extension.js:36:358635)
	at t.CredentialStore.<anonymous> (/Users/eric/.vscode/extensions/github.vscode-pull-request-github-0.8.0/media/extension.js:36:356720)
	at Generator.next (<anonymous>)
	at o (/Users/eric/.vscode/extensions/github.vscode-pull-request-github-0.8.0/media/extension.js:36:354362)
[Info] Error signing in to github.com: TypeError: Cannot set property 'text' of undefined
[Info] TypeError: Cannot set property 'text' of undefined
	at t.CredentialStore.willStartLogin (/Users/eric/.vscode/extensions/github.vscode-pull-request-github-0.8.0/media/extension.js:36:358635)
	at t.CredentialStore.<anonymous> (/Users/eric/.vscode/extensions/github.vscode-pull-request-github-0.8.0/media/extension.js:36:356720)
	at Generator.next (<anonymous>)
	at o (/Users/eric/.vscode/extensions/github.vscode-pull-request-github-0.8.0/media/extension.js:36:354362)
```

Extension version: 0.8.0
VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:29:22.216Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.52GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by nkpart** [comment]
Seeing the same issue on an Insiders build:

```Version: 1.36.0-insider
Commit: fe0c3e785c22c3ed2d5caa7178488c92d62bdb08
Date: 2019-06-28T12:34:48.210Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.6.0```

```[Info] Error signing in to github.com: TypeError: Cannot set property 'text' of undefined
[Info] TypeError: Cannot set property 'text' of undefined
	at t.CredentialStore.willStartLogin (/home/nkpart/.vscode-server-insiders/extensions/github.vscode-pull-request-github-0.8.0/media/extension.js:36:358635)
	at t.CredentialStore.<anonymous> (/home/nkpart/.vscode-server-insiders/extensions/github.vscode-pull-request-github-0.8.0/media/extension.js:36:356720)
	at Generator.next (<anonymous>)
	at o (/home/nkpart/.vscode-server-insiders/extensions/github.vscode-pull-request-github-0.8.0/media/extension.js:36:354362)
	at process._tickCallback (internal/process/next_tick.js:68:7)```

**Comment by Dieff** [comment]
Same issue here. I'm trying to authenticate to a Github Enterprise instance. Have tried using both Firefox and Chrome. Also using WSL remote if that makes a difference.

```
Version: 1.36.1 (system setup)
Commit: 2213894ea0415ee8c85c5eea0d0ff81ecc191529
Date: 2019-07-08T22:59:35.033Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.16299
extension version: 0.9.0
```

Here is the error log:

```
[Info] Looking for git repository
[Info] Git repository found, initializing review manager and pr tree view.
[Info] Review> Validate state in progress
[Info] Review> Validating state...
[Info] Found GitHub remote
[Info] Error signing in to gh.******.com: TypeError: Cannot set property 'text' of undefined
[Info] TypeError: Cannot set property 'text' of undefined
	at t.CredentialStore.willStartLogin (/home/ndieff/.vscode-server/extensions/github.vscode-pull-request-github-0.9.0/media/extension.js:36:357835)
	at t.CredentialStore.<anonymous> (/home/ndieff/.vscode-server/extensions/github.vscode-pull-request-github-0.9.0/media/extension.js:36:355895)
	at Generator.next (<anonymous>)
	at /home/ndieff/.vscode-server/extensions/github.vscode-pull-request-github-0.9.0/media/extension.js:36:353676
	at new Promise (<anonymous>)
	at n (/home/ndieff/.vscode-server/extensions/github.vscode-pull-request-github-0.9.0/media/extension.js:36:353453)
	at t.CredentialStore.login (/home/ndieff/.vscode-server/extensions/github.vscode-pull-request-github-0.9.0/media/extension.js:36:355690)
	at M.<anonymous> (/home/ndieff/.vscode-server/extensions/github.vscode-pull-request-github-0.9.0/media/extension.js:1:362232)
	at Generator.next (<anonymous>)
	at o (/home/ndieff/.vscode-server/extensions/github.vscode-pull-request-github-0.9.0/media/extension.js:1:354218)
	at process._tickCallback (internal/process/next_tick.js:68:7)
[Info] Error signing in to gh.*******.com: TypeError: Cannot set property 'text' of undefined
[Info] TypeError: Cannot set property 'text' of undefined
	at t.CredentialStore.willStartLogin (/home/ndieff/.vscode-server/extensions/github.vscode-pull-request-github-0.9.0/media/extension.js:36:357835)
	at t.CredentialStore.<anonymous> (/home/ndieff/.vscode-server/extensions/github.vscode-pull-request-github-0.9.0/media/extension.js:36:355895)
	at Generator.next (<anonymous>)
	at o (/home/ndieff/.vscode-server/extensions/github.vscode-pull-request-github-0.9.0/media/extension.js:36:353509)
	at process._tickCallback (internal/process/next_tick.js:68:7)
[Info] Error signing in to gh.*********.com: TypeError: Cannot set property 'text' of undefined
[Info] TypeError: Cannot set property 'text' of undefined
	at t.CredentialStore.willStartLogin (/home/ndieff/.vscode-server/extensions/github.vscode-pull-request-github-0.9.0/media/extension.js:36:357835)
	at t.CredentialStore.<anonymous> (/home/ndieff/.vscode-server/extensions/github.vscode-pull-request-github-0.9.0/media/extension.js:36:355895)
	at Generator.next (<anonymous>)
	at o (/home/ndieff/.vscode-server/extensions/github.vscode-pull-request-github-0.9.0/media/extension.js:36:353509)
	at process._tickCallback (internal/process/next_tick.js:68:7)
[Info] Error signing in to gh.**********.com: TypeError: Cannot set property 'text' of undefined
[Info] TypeError: Cannot set property 'text' of undefined
	at t.CredentialStore.willStartLogin (/home/ndieff/.vscode-server/extensions/github.vscode-pull-request-github-0.9.0/media/extension.js:36:357835)
	at t.CredentialStore.<anonymous> (/home/ndieff/.vscode-server/extensions/github.vscode-pull-request-github-0.9.0/media/extension.js:36:355895)
	at Generator.next (<anonymous>)
	at o (/home/ndieff/.vscode-server/extensions/github.vscode-pull-request-github-0.9.0/media/extension.js:36:353509)
	at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by carloluis** [comment]
@Dieff You can authenticate the extension on GH Enterprise by:

1. Create a new token on your `https://<GH-Enterprise>/settings/tokens` page
   - Select these scopes for the Token:
       - `repo`
       - `user` > `read:user`
       - `repo` > `user:email`
       - `write:discussion`

2. Then, associate that token with the extension in `settings.json`:

```json
{
  "githubPullRequests.hosts": [{
    "host": "https://<GH-Enterprise>",
    "token": "TOKEN"
  }]
}
```

3. Restart the editor, and you should be able to use the _GH-Pull Requests_ extension.

**Comment by Rody66** [comment]
@carloluis Thank you! It works.

**Comment by devamitk** [comment]
Awesome !! Worked like a charm. :)

**Comment by cconeill** [comment]
Noting that this no longer works, the `githubPullRequests.hosts` config set in JSON is overwritten whenever the GitHub extension starts.

**Comment by tim-hilt** [comment]
That's right. After watching [Sana and Burkes Satellite Video on YouTube](https://www.youtube.com/watch?v=T6sW1Dk9B4E&t=621s), i wanted to check the extension out, but the authentication-process didn't work out for me.

``` shell
~ λ code-insiders -v
1.46.0-insider
d487078dc7fc1c276657cadb61b4f63833a8df55
x64
```

OS is Arch Linux.

**Comment by carloluis** [comment]
> Noting that this no longer works, the `githubPullRequests.hosts` config set in JSON is overwritten whenever the GitHub extension starts.

Hi, the authentication issue is caused by the last version of the plugin since they decided to drop support for GH-Enterprise. You can read more [here](https://github.com/Microsoft/vscode-pull-request-github/wiki#2-is-github-enterprise-supported)

> As of version 0.16.0 of the extension, we are discontinuing support for GitHub Enterprise. At the beginning of this project, we had resources to test against Enterprise, but we have now been without that for quite some time.
...

> If you would still like to use the extension, you can use the "Install Another Version" option from the extensions viewlet to download version 0.15.0: https://github.com/Microsoft/vscode/issues/12764#issuecomment-442370545

I installed the prev. version [`0.15.0`](https://github.com/microsoft/vscode-pull-request-github/releases/tag/0.15.0) version and its working back again.

![image](https://user-images.githubusercontent.com/6170808/84036276-4b821f80-a99d-11ea-9e45-31b6e7e39441.png)

**Comment by eisenhowerj** [comment]
Now, we just need to figure out how to get rid of that pesky dot reminding us that Github Enterprise is an afterthought.

![image](https://user-images.githubusercontent.com/3538462/84537301-77fbab80-acbd-11ea-80c2-088a7a59d08f.png)
