### ISSUE TITLE
Error signing in to github.com: TypeError: s.env.createAppUri is not a function

### ISSUE THREAD

**Issue by iansan5653** [microsoft/vscode-pull-request-github#1475]
Version: 1.42.0-insider (user setup)
Commit: 629a08ed6231d7af269ae61a5cc610490d1f7f5d
Date: 2020-01-07T05:28:24.258Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.16299
GitHub Pull Requests v0.13.0

Steps to Reproduce:

1. Open a repository in VSCode
2. Click "Sign in to github.com"

The extension errors with "Error signing into github.com". There is a stack trace in the output log:
```
[Info] TypeError: s.env.createAppUri is not a function
	at t.GitHubServer.<anonymous> (c:\Users\iansanders\.vscode-insiders\extensions\github.vscode-pull-request-github-0.13.0\media\extension.js:1:523107)
	at Generator.next (<anonymous>)
	at c:\Users\iansanders\.vscode-insiders\extensions\github.vscode-pull-request-github-0.13.0\media\extension.js:1:519922
	at new Promise (<anonymous>)
	at n (c:\Users\iansanders\.vscode-insiders\extensions\github.vscode-pull-request-github-0.13.0\media\extension.js:1:519699)
	at t.GitHubServer.login (c:\Users\iansanders\.vscode-insiders\extensions\github.vscode-pull-request-github-0.13.0\media\extension.js:1:523048)
	at t.CredentialStore.<anonymous> (c:\Users\iansanders\.vscode-insiders\extensions\github.vscode-pull-request-github-0.13.0\media\extension.js:1:743033)
	at Generator.next (<anonymous>)
	at c:\Users\iansanders\.vscode-insiders\extensions\github.vscode-pull-request-github-0.13.0\media\extension.js:1:740627
	at new Promise (<anonymous>)
	at n (c:\Users\iansanders\.vscode-insiders\extensions\github.vscode-pull-request-github-0.13.0\media\extension.js:1:740404)
	at t.CredentialStore.login (c:\Users\iansanders\.vscode-insiders\extensions\github.vscode-pull-request-github-0.13.0\media\extension.js:1:742778)
	at M.<anonymous> (c:\Users\iansanders\.vscode-insiders\extensions\github.vscode-pull-request-github-0.13.0\media\extension.js:1:133709)
	at Generator.next (<anonymous>)
	at c:\Users\iansanders\.vscode-insiders\extensions\github.vscode-pull-request-github-0.13.0\media\extension.js:1:124572
	at new Promise (<anonymous>)
	at n (c:\Users\iansanders\.vscode-insiders\extensions\github.vscode-pull-request-github-0.13.0\media\extension.js:1:124349)
	at c:\Users\iansanders\.vscode-insiders\extensions\github.vscode-pull-request-github-0.13.0\media\extension.js:1:133643
	at Array.map (<anonymous>)
	at M.<anonymous> (c:\Users\iansanders\.vscode-insiders\extensions\github.vscode-pull-request-github-0.13.0\media\extension.js:1:133636)
	at Generator.next (<anonymous>)
	at o (c:\Users\iansanders\.vscode-insiders\extensions\github.vscode-pull-request-github-0.13.0\media\extension.js:1:124405)
```

**Comment by RMacfarlane** [comment]
Thanks @iansan5653, this should be fixed with https://github.com/microsoft/vscode-pull-request-github/commit/3375b2a0719b66fc56dcd6d8589d73e71e537a7a. Publishing a new version of the extension now.

**Comment by iansan5653** [comment]
Confirmed, thanks!
