### ISSUE TITLE
Hovers/links don't seem to work anymore?

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-pull-request-github#1503]
![image](https://user-images.githubusercontent.com/2193314/75254915-f592be80-5795-11ea-9147-07b94b021d8d.png)

Expecting this hover:

![image](https://user-images.githubusercontent.com/2193314/75254970-0b07e880-5796-11ea-9388-fd91c4a4c372.png)

Version: 1.43.0-insider (user setup)
Commit: 89cafb24e5d75a0c8d561a6cdd95e93b5679e152
Date: 2020-02-25T05:29:49.719Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

Ext: 2020.2.29762

**Comment by alexr00** [comment]
Do you have master checked out? I tried to repro, and I saw some weirdness when the branch wasn't master.

**Comment by Tyriar** [comment]
Yes it's master. It's Tyriar/xterm.js checked out to master, with xtermjs/xterm.js as remote `ups` and setting:

```
  "githubPullRequests.remotes": [
    "origin",
    "ups"
  ]
```

**Comment by Tyriar** [comment]
Another case:

![image](https://user-images.githubusercontent.com/2193314/75258146-e3ffe580-579a-11ea-90ea-135b7e97b841.png)

**Comment by Tyriar** [comment]
Might be related to this error in console, there is a lot of them:

```
Error: GraphQL error: Could not resolve to a User with the login of 'babel/template/-/template-7.6.0.tgz#7f0159c7f5012230dad64cca42ec9bdb5c9536e6"'.	at new t (c:\Users\daimms.REDMOND\.vscode-insiders\extensions\github.vscode-pull-request-github-insiders-2020.2.29762\media\extension.js:1:552020)	at c:\Users\daimms.REDMOND\.vscode-insiders\extensions\github.vscode-pull-request-github-insiders-2020.2.29762\media\extension.js:1:572903	at c:\Users\daimms.REDMOND\.vscode-insiders\extensions\github.vscode-pull-request-github-insiders-2020.2.29762\media\extension.js:1:579247	at Array.forEach (<anonymous>)	at c:\Users\daimms.REDMOND\.vscode-insiders\extensions\github.vscode-pull-request-github-insiders-2020.2.29762\media\extension.js:1:579227	at Map.forEach (<anonymous>)	at e.broadcastQueries (c:\Users\daimms.REDMOND\.vscode-insiders\extensions\github.vscode-pull-request-github-insiders-2020.2.29762\media\extension.js:1:579134)	at Object.next (c:\Users\daimms.REDMOND\.vscode-insiders\extensions\github.vscode-pull-request-github-insiders-2020.2.29762\media\extension.js:1:580307)	at _ (c:\Users\daimms.REDMOND\.vscode-insiders\extensions\github.vscode-pull-request-github-insiders-2020.2.29762\media\extension.js:1:979343)	at v (c:\Users\daimms.REDMOND\.vscode-insiders\extensions\github.vscode-pull-request-github-insiders-2020.2.29762\media\extension.js:1:979847)	at e.value (c:\Users\daimms.REDMOND\.vscode-insiders\extensions\github.vscode-pull-request-github-insiders-2020.2.29762\media\extension.js:1:980400)	at c:\Users\daimms.REDMOND\.vscode-insiders\extensions\github.vscode-pull-request-github-insiders-2020.2.29762\media\extension.js:1:561217	at Array.forEach (<anonymous>)	at Object.next (c:\Users\daimms.REDMOND\.vscode-insiders\extensions\github.vscode-pull-request-github-insiders-2020.2.29762\media\extension.js:1:561190)	at _ (c:\Users\daimms.REDMOND\.vscode-insiders\extensions\github.vscode-pull-request-github-insiders-2020.2.29762\media\extension.js:1:979343)	at v (c:\Users\daimms.REDMOND\.vscode-insiders\extensions\github.vscode-pull-request-github-insiders-2020.2.29762\media\extension.js:1:979847)	at e.value (c:\Users\daimms.REDMOND\.vscode-insiders\extensions\github.vscode-pull-request-github-insiders-2020.2.29762\media\extension.js:1:980400)	at _ (c:\Users\daimms.REDMOND\.vscode-insiders\extensions\github.vscode-pull-request-github-insiders-2020.2.29762\media\extension.js:1:979343)	at v (c:\Users\daimms.REDMOND\.vscode-insiders\extensions\github.vscode-pull-request-github-insiders-2020.2.29762\media\extension.js:1:979847)	at e.value (c:\Users\daimms.REDMOND\.vscode-insiders\extensions\github.vscode-pull-request-github-insiders-2020.2.29762\media\extension.js:1:980400)	at c:\Users\daimms.REDMOND\.vscode-insiders\extensions\github.vscode-pull-request-github-insiders-2020.2.29762\media\extension.js:1:199514	at c:\Users\daimms.REDMOND\.vscode-insiders\extensions\github.vscode-pull-request-github-insiders-2020.2.29762\media\extension.js:8:2898	at I (c:\Users\daimms.REDMOND\.vscode-insiders\extensions\github.vscode-pull-request-github-insiders-2020.2.29762\media\extension.js:8:2932)	at x (c:\Users\daimms.REDMOND\.vscode-insiders\extensions\github.vscode-pull-request-github-insiders-2020.2.29762\media\extension.js:8:2753)	at p (c:\Users\daimms.REDMOND\.vscode-insiders\extensions\github.vscode-pull-request-github-insiders-2020.2.29762\media\extension.js:8:703)	at processTicksAndRejections (internal/process/task_queues.js:75:11) (at S.<anonymous> (c:\Users\daimms.REDMOND\.vscode-insiders\extensions\github.vscode-pull-request-github-insiders-2020.2.29762\media\extension.js:1:133319))
```

**Comment by alexr00** [comment]
The problem here is that I currently assume that issues come from the `origin` remote, and in your case they come from the `ups` remote. I'll try to guess which remote you want (the first one that has a matching issue) and I'll add a setting `githubIssues.defaultRemote`. It will only impact issues written as `#123`, and not ones that are fully qualified (microsoft/vscode#123).
