### ISSUE TITLE
Entering/leaving review mode: `Error: unknown handler`

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-pull-request-github#1594]
Issue Type: <b>Bug</b>

In the dev console, everything seems to work still:

```
  ERR unknown handler: Error: unknown handler
    at e.$unregisterCommentController (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6140:700)
    at e._doInvokeHandler (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3942:707)
    at e._invokeHandler (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3942:399)
    at e._receiveRequest (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3941:59)
    at e._receiveOneMessage (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3939:908)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3938:136
    at e.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:99:801)
    at v.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:400:97)
    at t.PersistentProtocol._receiveMessage (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:404:451)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:401:635
    at e.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:99:801)
    at g.acceptChunk (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:397:532)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:396:832
    at Socket.t (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:407:812)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

(A private repository, in case that matters.)

Extension version: 2020.3.35461
VS Code version: Code - Insiders 1.44.0-insider (d7d1147d6b764a48b789000c03088ee9afabcd8a, 2020-03-31T08:22:34.682Z)
OS version: Darwin x64 19.2.0
Remote OS version: Linux x64 4.19.76-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.35GB free)|
|Process Argv|-psn_0_3851180|
|Screen Reader|no|
|VM|22%|

|Item|Value|
|---|---|
|Remote|Container vscode-remote-containers_devc…|
|OS|Linux x64 4.19.76-linuxkit|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (4 x 2400)|
|Memory (System)|7.78GB (0.31GB free)|
|VM|0%|
</details>

**Comment by tnrich** [comment]
Also seeing this right before my extension host terminates: 
![image](https://user-images.githubusercontent.com/2730609/129624772-07cf135a-6cd2-405f-af35-f6b9372854f5.png)
