### ISSUE TITLE
Cannot signin due to ECONNREFUSED

### ISSUE THREAD

**Issue by svillar** [microsoft/vscode-pull-request-github#1649]
- Extension version: 0.15.0
- VSCode Version: 1.44.2
- OS: Linux

Steps to Reproduce:

1. Try to sign in in github by clicking on the bottom bar button
2. Follow steps on the browser. Eventually got redirected back to VSCode
3. Accept opening the `vscode://` URL when prompted
4. Fails to signin. The extension output shows

```
[Info] Error signing in to github.com: Error: connect ECONNREFUSED 127.0.0.1:8118
[Info] Error: connect ECONNREFUSED 127.0.0.1:8118
	at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1056:14)
```

I can properly resolve `github.com` (checked with `nslookup` and opening it in the browser).

**Comment by adam-p** [comment]
Same problem. Same version of VSCode and the extension, but on Windows 10 Pro. This has been the state probably for a couple of weeks.

I also double-checked that I can ping `api.github.com`, but I don't think that's the problem -- it looks more like a local proxy can't be connected to.

```
[Info] Error signing in to github.com: HttpError: request to https://api.github.com/ failed, reason: connect ECONNREFUSED 127.0.0.1:49715
[Info] HttpError: request to https://api.github.com/ failed, reason: connect ECONNREFUSED 127.0.0.1:49715
	at c:\Users\a.pritchard\.vscode\extensions\github.vscode-pull-request-github-0.15.0\media\extension.js:36:1116
	at c:\Users\a.pritchard\.vscode\extensions\github.vscode-pull-request-github-0.15.0\media\extension.js:8:2898
	at O (c:\Users\a.pritchard\.vscode\extensions\github.vscode-pull-request-github-0.15.0\media\extension.js:8:2932)
	at x (c:\Users\a.pritchard\.vscode\extensions\github.vscode-pull-request-github-0.15.0\media\extension.js:8:2753)
	at R (c:\Users\a.pritchard\.vscode\extensions\github.vscode-pull-request-github-0.15.0\media\extension.js:8:2341)
	at p (c:\Users\a.pritchard\.vscode\extensions\github.vscode-pull-request-github-0.15.0\media\extension.js:8:703)
	at processTicksAndRejections (internal/process/task_queues.js:75:11)
```

**Comment by siwuxei** [comment]
Same too

**Comment by alexr00** [comment]
Auth stack has changed. Closing since I don't expect this to still be happening.
