### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by robertwt7** [microsoft/vscode-pull-request-github#1766]
Hey guys, when I try to install on WSL it doesn't seem to work

I checked similar issue at #586 however my vs code version is higher.

Here's the screenshot of what's happening, doesn't seem to show me any other log, was pretty excited for this extension after watching github satelite!

Please help

Cheers

![image](https://user-images.githubusercontent.com/15647967/81241182-f1640680-904c-11ea-8820-17d5d3199801.png)

**Comment by RMacfarlane** [comment]
@sandy081 Any ideas here?

**Comment by sandy081** [comment]
@robertwt7 Can you please check if you are not able to install only this extension or other extensions?

You can find more logs here
- Help -> Toggle Developer Tools -> Console
- View -> Open View… -> Log (Window)
- View -> Open View… -> Log (Remote WSL)

**Comment by robertwt7** [comment]
Only this extension, I just installed the github extension and it was fine

Right here's what i got from the log

```
  ERR Unable to install extension 'github.vscode-pull-request-github' as it is not compatible with VS Code '1.44.2'.: Error: Unable to install extension 'github.vscode-pull-request-github' as it is not compatible with VS Code '1.44.2'.
    at /home/robertwt7/.vscode-server/bin/ff915844119ce9485abfe8aa9076ec76b5300ddd/out/vs/server/remoteExtensionHostAgent.js:441:207
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
```
