### ISSUE TITLE
Unhandled promise rejection from "has no Github remotes" when in subdirectory

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-pull-request-github#1970]
- Extension version: nightly 2020.7.8134
- VSCode Version: 1.47-insider
- OS: Windows 1909

1. Have a Git repo cloned (with remotes)
2. Open one of its subdirectories in VS Code
3. Observe this error in the extension host:

```
rejected promise not handled within 1 second: Error: file:///c%3A/Users/Connor/Documents/Github/vscode-js-debug has no GitHub remotes
extensionHostProcess.js:976
stack trace: Error: file:///c%3A/Users/Connor/Documents/Github/vscode-js-debug has no GitHub remotes
	at S.<anonymous> (c:\Users\Connor\.vscode-insiders\extensions\github.vscode-pull-request-github-insiders-2020.7.8134\media\extension.js:1:127867)
	at Generator.next (<anonymous>)
	at c:\Users\Connor\.vscode-insiders\extensions\github.vscode-pull-request-github-insiders-2020.7.8134\media\extension.js:1:104763
	at new Promise (<anonymous>)
	at c:\Users\Connor\.vscode-insiders\extensions\github.vscode-pull-request-github-insiders-2020.7.8134\media\extension.js:1:104511
	at S.getOrigin (c:\Users\Connor\.vscode-insiders\extensions\github.vscode-pull-request-github-insiders-2020.7.8134\media\extension.js:1:127792)
	at Object.<anonymous> (c:\Users\Connor\.vscode-insiders\extensions\github.vscode-pull-request-github-insiders-2020.7.8134\media\extension.js:1:1249810)
	at Generator.next (<anonymous>)
	at c:\Users\Connor\.vscode-insiders\extensions\github.vscode-pull-request-github-insiders-2020.7.8134\media\extension.js:1:1248712
	at new Promise (<anonymous>)
	at c:\Users\Connor\.vscode-insiders\extensions\github.vscode-pull-request-github-insiders-2020.7.8134\media\extension.js:1:1248460
	at Object.getCurrentUserLogin (c:\Users\Connor\.vscode-insiders\extensions\github.vscode-pull-request-github-insiders-2020.7.8134\media\extension.js:1:1249739)
	at Object.<anonymous> (c:\Users\Connor\.vscode-insiders\extensions\github.vscode-pull-request-github-insiders-2020.7.8134\media\extension.js:1:1249527)
	at Generator.next (<anonymous>)
	at c:\Users\Connor\.vscode-insiders\extensions\github.vscode-pull-request-github-insiders-2020.7.8134\media\extension.js:1:1248712
	at new Promise (<anonymous>)
	at c:\Users\Connor\.vscode-insiders\extensions\github.vscode-pull-request-github-insiders-2020.7.8134\media\extension.js:1:1248460
	at Object.notifySuggestedAccounts (c:\Users\Connor\.vscode-insiders\extensions\github.vscode-pull-request-github-insiders-2020.7.8134\media\extension.js:1:1249475)
	at c:\Users\Connor\.vscode-insiders\extensions\github.vscode-pull-request-github-insiders-2020.7.8134\media\extension.js:1:1248988
	at l.fire (c:\Users\Connor\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:45:801)
	at c:\Users\Connor\.vscode-insiders\extensions\github.vscode-pull-request-github-insiders-2020.7.8134\media\extension.js:1:114159
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
```
In this case I opened `demos/node` within that repository. I do have remotes on that repo.

It doesn't look like this breaks anything obviously, the pull requests and issues view still works. Kind of annoying though 😛

**Comment by alexr00** [comment]
@connor4312 I can't seem to repro this. What are your remotes?

**Comment by connor4312** [comment]
I have two remotes -- one for a pull request from a contributor, and the origin

```
PS C:\Users\Connor\Documents\Github\vscode-js-debug> git remote show
cbmd
origin
PS C:\Users\Connor\Documents\Github\vscode-js-debug> git remote show origin
* remote origin
  Fetch URL: git@github.com:microsoft/vscode-pwa.git
  Push  URL: git@github.com:microsoft/vscode-pwa.git
```
