### ISSUE TITLE
Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#2076]
Exception has occurred: TypeError: Cannot read property 'toLowerCase' of undefined
t c:\Users\alros\repos\Microsoft\vscode-pull-request-github2\media\extension.js:77946:50
	at Array.map (<anonymous>)
	at PullRequestModel.<anonymous> (c:\Users\alros\repos\Microsoft\vscode-pull-request-github2\media\extension.js:77928:60)
	at Generator.next (<anonymous>)
	at fulfilled (c:\Users\alros\repos\Microsoft\vscode-pull-request-github2\media\extension.js:77303:58)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)

**Comment by aeschli** [comment]
Verified in code
