### ISSUE TITLE
Create issue is not working

### ISSUE THREAD

**Issue by Perh0rd** [microsoft/vscode-pull-request-github#2128]
- Extension version: 0.20.0
- VSCode Version:  1.49.0
- OS: Windows 10 enterprise 64b

Steps to Reproduce:

https://ttprivatenew.s3.amazonaws.com/pulse/paul-xpedigo/attachments/14668894/TinyTake14-09-2020-03-22-16.mp4

Hi, 
Get error "Unexpected end of JSON input", while creating an issue from left menu.

**Comment by Perh0rd** [comment]
I confirm this bug does not exist on 0.19.0

**Comment by ddorf** [comment]
Same issue and error message on my system:

Extension version: 0.20.0
VSCode Version: 1.49.1
OS: Windows 10 home 64b

**Comment by jhampson-dbre** [comment]
Same issue. message in extenision host logs:

```
[2020-10-08 16:31:30.933] [exthost] [trace] [GitHub.vscode-pull-request-github] INVOKE provider 'U'
[2020-10-08 16:31:30.934] [exthost] [error] [GitHub.vscode-pull-request-github] provider FAILED
[2020-10-08 16:31:30.938] [exthost] [error] SyntaxError: Unexpected end of JSON input
	at JSON.parse (<anonymous>)
	at Object.s [as extractIssueOriginFromQuery] (c:\Users\iqc8073\.vscode\extensions\github.vscode-pull-request-github-0.20.1\media\extension.js:1:589764)
	at t.UserCompletionProvider.<anonymous> (c:\Users\iqc8073\.vscode\extensions\github.vscode-pull-request-github-0.20.1\media\extension.js:1:1037641)
	at Generator.next (<anonymous>)
	at o (c:\Users\iqc8073\.vscode\extensions\github.vscode-pull-request-github-0.20.1\media\extension.js:1:1036559)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
```

**Comment by bs** [comment]
Reverting to 0.19.0 doesn't work here, as I get an exception thrown when the extension starts up.

**Comment by jhujasonw** [comment]
FWIW I see the error that @jhampson-dbre mentions if I try to do a contextual user search in the Asignees field.  If I try to save, I get the same stack trace that @Perh0rd mentions.  For posterity, here is a copy-pasta of that stack.  Mine looks a little bit different because it's a Remote-WSL folder that is open.

```
SyntaxError: Unexpected end of JSON input  
	at JSON.parse (<anonymous>)
	at Object.s [as extractIssueOriginFromQuery] (/home/xxxx/.vscode-server/extensions/github.vscode-pull-request-github-0.20.1/media/extension.js:1)
	at t.IssueFeatureRegistrar.<anonymous> (/home/xxxx/.vscode-server/extensions/github.vscode-pull-request-github-0.20.1/media/extension.js:1)
	at Generator.next (<anonymous>)
	at /home/xxxx/.vscode-server/extensions/github.vscode-pull-request-github-0.20.1/media/extension.js:1
	at new Promise (<anonymous>)
	at r (/home/xxxx/.vscode-server/extensions/github.vscode-pull-request-github-0.20.1/media/extension.js:1)
	at t.IssueFeatureRegistrar.createIssueFromFile (/home/xxxx/.vscode-server/extensions/github.vscode-pull-request-github-0.20.1/media/extension.js:1)
	at t.IssueFeatureRegistrar.<anonymous> (/home/xxxx/.vscode-server/extensions/github.vscode-pull-request-github-0.20.1/media/extension.js:1)
	at _executeContributedCommand (/home/xxxx/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/server/remoteExtensio.js:719)
	at _.$executeContributedCommand (/home/xxxx/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/server/remoteExtensio.js:720)
	at m._doInvokeHandler (/home/xxxx/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/server/remoteExtensio.js:895)
	at m._invokeHandler (/home/xxxx/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/server/remoteExtensio.js:895)
	at m._receiveRequest (/home/xxxx/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/server/remoteExtensio.js:893)
	at m._receiveOneMessage (/home/xxxx/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/server/remoteExtensio.js:892)
	at /home/xxxx/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/server/remoteExtensio.js:890
	at l.fire (/home/xxxx/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/server/remoteExtensio.js:45)
	at v.fire (/home/xxxx/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/server/remoteExtensio.js:256)
	at /home/xxxx/.vsco…HostProcess.js:1084
	at l.fire (/home/xxxx/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/server/remoteExtensio.js:45)
	at v.fire (/home/xxxx/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/server/remoteExtensio.js:256)
	at t.PersistentProtocol._receiveMessage (/home/xxxx/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/server/remoteExtensio.js:261)
	at /home/xxxx/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/server/remoteExtensio.js:258
	at l.fire (/home/xxxx/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/server/remoteExtensio.js:45)
	at p.acceptChunk (/home/xxxx/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/server/remoteExtensio.js:253)
	at /home/xxxx/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/server/remoteExtensio.js:253
	at Socket.t (/home/xxxx/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/server/remoteExtensio.js:263)
	at Socket.emit (events.js:223)
	at addChunk (_stream_readable.js:309)
	at readableAddChunk (_stream_readable.js:290)
	at Socket.Readable.push (_stream_readable.js:224)
	at TCP.onStreamRead (internal/stream_base_commons.js:181)
```

I also cannot back-rev to either 0.20.0 or 0.19.0 as they no longer work.

**Comment by jhujasonw** [comment]
I was able to back-rev to 0.19.0 of the extension by back-reving VSCode to 1.49.0. (last good known working config) 

After going through some extension back-reving issues on other extensions, 0.19.0 of the github pull request module works.  A bisection between tags 0.19.0 and 0.20.0 show 32 commits.  It would take me quite a while to figure out what caused this, and I am not familiar enough with the code base.  I hope this helps a bit though

**Comment by dantman** [comment]
I am also unable to create an issue.

At first there was no error message anywhere. In output I saw "[Info] No remote with name 'upstream' found. Please update your 'githubPullRequests.remotes' setting." at startup. Which is strange because that setting is the default of `origin,upstream` and I have `origin` and `old` as remotes.

After deleting the `old` remote trying to create an issue shows a "Unexpected end of JSON input" notification. However I still cannot find any errors in Output or the extension host log.
