### ISSUE TITLE
Github create issue doesnt show anything

### ISSUE THREAD

**Issue by skarchmit** [microsoft/vscode-pull-request-github#2298]
- Extension version: 0.21.2
- VSCode Version: 1.51.1
- OS: Mac OS Big Sur (11.0)

Full vscode details:

Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-11T01:11:34.018Z (1 wk ago)
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 20.1.0

Steps to Reproduce:

0. I'm Using a .code-workspace file for a single github repo
1. Open a file into active editor
2. Command Pallete (command shift P)
3. Search and select "Github Issues: Create Issue from Selection
4. A window pops up asking for details (Enter the details)
5. Hit enter. The box goes away. Check the github repo for the issue. Issue is not updated.

**Comment by alexr00** [comment]
@skarchmit Do you get a notification that tells you that the issue was created? 

Can you open the developer tools (command palette -> Developer: Toggle developer tools) and share any errors or warnings that are in the console?

**Comment by skarchmit** [comment]
So I've started a new session in VSCode (complete restart), toggled developer tools, executed the issue creation. 

No issue has been added to the repo and no message was displayed in VSCode that it failed.

```sh
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1771  WARN [File Watcher (chokidar)] Watcher basePath does not match version on disk and was corrected (original: /Users/skarchmit/git/monorepo, real: /Users/skarchmit/Git/monorepo)
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5478 Overwriting grammar scope name to file mapping for scope source.sql.
Old grammar file: file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/extensions/sql/syntaxes/sql.tmLanguage.json.
New grammar file: file:///Users/skarchmit/.vscode-insiders/extensions/ms-mssql.mssql-1.9.0/syntaxes/SQL.plist
register @ /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5478
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5478 Overwriting grammar scope name to file mapping for scope source.yaml.
Old grammar file: file:///Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/extensions/yaml/syntaxes/yaml.tmLanguage.json.
New grammar file: file:///Users/skarchmit/.vscode-insiders/extensions/redhat.vscode-yaml-0.13.0/syntaxes/yaml.tmLanguage.json
register @ /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5478
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:309 [Extension Host] (node:21345) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead. (at writeOut (internal/process/warning.js:27:3))
t.log @ /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:309
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:309 [Extension Host] [vscode-icons] v11.0.0 activated! (at /Users/skarchmit/.vscode-insiders/extensions/vscode-icons-team.vscode-icons-11.0.0/dist/src/vscode-icons.bundle.js:9:208991)
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1771   ERR No application in the Launch Services database matches the input criteria.: Error: No application in the Launch Services database matches the input criteria.
console.ts:137 [Extension Host] rejected promise not handled within 1 second: Canceled: Canceled (at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1081:388)
t.log @ console.ts:135
$logExtensionHostMessage @ remoteConsoleUtil.ts:29
_doInvokeHandler @ rpcProtocol.ts:401
_invokeHandler @ rpcProtocol.ts:332
_receiveRequest @ rpcProtocol.ts:278
_receiveOneMessage @ rpcProtocol.ts:220
(anonymous) @ rpcProtocol.ts:93
fire @ event.ts:545
fire @ ipc.net.ts:407
_receiveMessage @ ipc.net.ts:755
(anonymous) @ ipc.net.ts:630
fire @ event.ts:545
acceptChunk @ ipc.net.ts:224
(anonymous) @ ipc.net.ts:149
t @ ipc.net.ts:892
emit @ events.js:223
addChunk @ _stream_readable.js:309
readableAddChunk @ _stream_readable.js:290
Readable.push @ _stream_readable.js:224
onStreamRead @ internal/stream_base_commons.js:181
console.ts:137 [Extension Host] stack trace: Canceled: Canceled	at b.makeCancelError (/Users/skarchmit/.vscode-insiders/extensions/ms-python.python-2020.11.371526539/out/client/extension.js:1:169220)	at b.handleFailedRequest (/Users/skarchmit/.vscode-insiders/extensions/ms-python.python-2020.11.371526539/out/client/extension.js:1:169074)	at /Users/skarchmit/.vscode-insiders/extensions/ms-python.python-2020.11.371526539/out/client/extension.js:1:131852 (at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1081:467)
t.log @ console.ts:135
$logExtensionHostMessage @ remoteConsoleUtil.ts:29
_doInvokeHandler @ rpcProtocol.ts:401
_invokeHandler @ rpcProtocol.ts:332
_receiveRequest @ rpcProtocol.ts:278
_receiveOneMessage @ rpcProtocol.ts:220
(anonymous) @ rpcProtocol.ts:93
fire @ event.ts:545
fire @ ipc.net.ts:407
_receiveMessage @ ipc.net.ts:755
(anonymous) @ ipc.net.ts:630
fire @ event.ts:545
acceptChunk @ ipc.net.ts:224
(anonymous) @ ipc.net.ts:149
t @ ipc.net.ts:892
emit @ events.js:223
addChunk @ _stream_readable.js:309
readableAddChunk @ _stream_readable.js:290
Readable.push @ _stream_readable.js:224
onStreamRead @ internal/stream_base_commons.js:181
```

![image](https://user-images.githubusercontent.com/8825870/99990660-f37f7f80-2d68-11eb-9e3c-9328c115577f.png)

**Comment by alexr00** [comment]
@skarchmit thanks for the info. There's nothing suspicious there. Are you able to make gif of the issue (https://gifcap.dev/ works well for this and is made by member of the VS Code team)?

**Comment by skarchmit** [comment]
Looks like it resolved itself over the weekend. It now works as expected. Not sure if the issue was on github's end, but my vscode version and extension version did not change.
