### ISSUE TITLE
No tree view with id 'github:compareChanges' registered.

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode-pull-request-github#2397]
Testing microsoft/vscode#114967

I created a PR and saw this message:

![image](https://user-images.githubusercontent.com/900690/105831739-61ddf980-5fc7-11eb-895c-0d9a136b5bf8.png)

**Comment by isidorn** [comment]
I also see this, here's the complete stack trace

```
 ERR No tree view with id 'github:compareChanges' registered.: Error: No tree view with id 'github:compareChanges' registered.
	at u.$setVisible (/snap/code-insiders/615/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:86:40343)
	at p._doInvokeHandler (/snap/code-insiders/615/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89:10276)
	at p._invokeHandler (/snap/code-insiders/615/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89:9968)
	at p._receiveRequest (/snap/code-insiders/615/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89:8638)
	at p._receiveOneMessage (/snap/code-insiders/615/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89:7440)
	at /snap/code-insiders/615/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89:5568
	at v.fire (/snap/code-insiders/615/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:55:1836)
	at d.fire (/snap/code-insiders/615/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:63:15515)
	at /snap/code-insiders/615/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104:29104
	at v.fire (/snap/code-insiders/615/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:55:1836)
	at d.fire (/snap/code-insiders/615/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:63:15515)
	at t._receiveMessage (/snap/code-insiders/615/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:63:20765)
	at /snap/code-insiders/615/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:63:17659
	at v.fire (/snap/code-insiders/615/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:55:1836)
	at u.acceptChunk (/snap/code-insiders/615/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:63:12880)
	at /snap/code-insiders/615/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:63:12228
	at Socket.m (/snap/code-insiders/615/usr/share/code-insiders/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104:12375)
	at Socket.emit (events.js:315:20)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:271:9)
	at Socket.Readable.push (_stream_readable.js:212:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
```

**Comment by eamodio** [comment]
Is there any chance you both had both the stable and nightly versions of the extension installed at the same time?

**Comment by bpasero** [comment]
No, I always use empty user data dir and empty extensions dir for testing.

**Comment by isidorn** [comment]
No. I only had the nightly version.

**Comment by bamurtaugh** [comment]
I also ran into this when testing https://github.com/microsoft/vssaas-planning/issues/2176; can be seen at ~8:50 in this week's Golden Scenario run.

1. Create a PR in a Codespace
2. When you click button to Create PR, get the message "No tree view with id 'github:compareChanges' registered," although the PR is created and can be acted upon (commented on, reviewed, merged).

![image](https://user-images.githubusercontent.com/25310137/109081606-69242000-76b7-11eb-9461-8f203d749482.png)

- Extension version: Nightly, v2021.2.34443, have stable version disabled
- Testing in Codespaces:
Version: 1.54.0-insider
Commit: c47da720f351455681978a48edc4d9a0d095ea0e
Date: 2021-02-24T11:27:23.847Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36

**Comment by burkeholland** [comment]
Hit this in the Codespaces Golden Scenario run today with Nightly. Had stable installed (because @builtin), but disabled. Codespaces showed me as not logged in. Logging in did not fix the issue. Reloading the browser did.

![image](https://user-images.githubusercontent.com/686963/121784529-f2356900-cb79-11eb-8250-125028af8713.png)

**Comment by alexr00** [comment]
@burkeholland did you reload after you disabled stable?

**Comment by bamurtaugh** [comment]
@burkeholland and I have both been experiencing this one again in recent uses of Codespaces, but not necessarily consistently (i.e. I just loaded up a Codespace and it didn't happen). Next time I encounter it, I'll grab logs.

**Comment by burkeholland** [comment]
I am hitting this today...

```
2022-11-08 20:01:22.186 [info] > git checkout -q main [3ms]
2022-11-08 20:01:22.250 [info] > git status -z -uall [10ms]
2022-11-08 20:01:22.251 [info] > git remote --verbose [23ms]
2022-11-08 20:01:22.251 [info] > git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname) [53ms]
2022-11-08 20:01:22.252 [info] > git config --get commit.template [1ms]
2022-11-08 20:01:22.264 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/main refs/remotes/main [1ms]
2022-11-08 20:01:22.316 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/main refs/remotes/main [16ms]
2022-11-08 20:01:22.328 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/main refs/remotes/main [48ms]
2022-11-08 20:01:22.330 [info] > git show -s --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%D%n%B -z cdf6698eb3dac824537ed5a5248c22a7501539ab [2ms]
2022-11-08 20:01:22.428 [info] > git config --local branch.main.github-pr-owner-number [38ms]
2022-11-08 20:01:22.456 [info] > git status -z -uall [8ms]
2022-11-08 20:01:22.457 [info] > git remote --verbose [14ms]
2022-11-08 20:01:22.457 [info] > git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname) [21ms]
2022-11-08 20:01:22.457 [info] > git config --get commit.template [2ms]
2022-11-08 20:01:22.474 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/main refs/remotes/main [9ms]
2022-11-08 20:01:23.062 [info] > git rev-list --count f4b39377f092ed94c53a2bb7c518e1fb818a70fa.. -- /workspaces/next-idea/.devcontainer/devcontainer.json [2ms]
2022-11-08 20:01:23.082 [info] > git log --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%D%n%B -z -n4 -- /workspaces/next-idea/.devcontainer/devcontainer.json [11ms]
2022-11-08 20:01:23.365 [info] > git status -z -uall [7ms]
2022-11-08 20:01:23.366 [info] > git remote --verbose [14ms]
2022-11-08 20:01:23.366 [info] > git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname) [22ms]
2022-11-08 20:01:23.367 [info] > git config --get commit.template [2ms]
2022-11-08 20:01:23.380 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/main refs/remotes/main [3ms]
2022-11-08 20:01:23.440 [info] > git config --local -l [41ms]
2022-11-08 20:01:23.469 [info] > git status -z -uall [8ms]
2022-11-08 20:01:23.470 [info] > git remote --verbose [14ms]
2022-11-08 20:01:23.470 [info] > git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname) [21ms]
2022-11-08 20:01:23.470 [info] > git config --get commit.template [2ms]
2022-11-08 20:01:23.489 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/main refs/remotes/main [12ms]
2022-11-08 20:01:23.533 [info] > git ls-files --stage -- /workspaces/next-idea/.devcontainer/devcontainer.json [1ms]
2022-11-08 20:01:23.541 [info] > git cat-file -s 4c922136a7b6e481a825f50259d68f38085850ae [1ms]
2022-11-08 20:01:23.601 [info] > git show --textconv :.devcontainer/devcontainer.json [1ms]
2022-11-08 20:01:23.852 [info] > git show --textconv 998257a741f7ad674de9fa9733fef9d5aeef4f3c:.devcontainer/devcontainer.json [29ms]
2022-11-08 20:01:23.941 [info] > git diff cdf6698eb3dac824537ed5a5248c22a7501539ab -- .devcontainer/devcontainer.json [7ms]
2022-11-08 20:01:23.942 [info] > git diff cdf6698eb3dac824537ed5a5248c22a7501539ab -- .devcontainer/devcontainer.json [2ms]
2022-11-08 20:01:24.078 [info] > git rev-list --count f4b39377f092ed94c53a2bb7c518e1fb818a70fa.. -- /workspaces/next-idea/.devcontainer/devcontainer.json [2ms]
2022-11-08 20:01:24.087 [info] > git log --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%D%n%B -z -n4 -- /workspaces/next-idea/.devcontainer/devcontainer.json [2ms]
2022-11-08 20:01:34.645 [info] > git checkout -q -b burkeholland-another-branch --no-track HEAD [3ms]
2022-11-08 20:01:34.680 [info] > git status -z -uall [8ms]
2022-11-08 20:01:34.681 [info] > git remote --verbose [16ms]
2022-11-08 20:01:34.681 [info] > git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname) [26ms]
2022-11-08 20:01:34.681 [info] > git config --get commit.template [1ms]
2022-11-08 20:01:34.690 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/burkeholland-another-branch refs/remotes/burkeholland-another-branch [1ms]
2022-11-08 20:01:34.724 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/burkeholland-another-branch refs/remotes/burkeholland-another-branch [16ms]
2022-11-08 20:01:34.732 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/burkeholland-another-branch refs/remotes/burkeholland-another-branch [31ms]
2022-11-08 20:01:34.733 [info] > git show -s --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%D%n%B -z cdf6698eb3dac824537ed5a5248c22a7501539ab [2ms]
2022-11-08 20:01:34.856 [info] > git config --local branch.burkeholland-another-branch.github-pr-owner-number [39ms]
2022-11-08 20:01:35.380 [info] > git rev-list --count f4b39377f092ed94c53a2bb7c518e1fb818a70fa.. -- /workspaces/next-idea/.devcontainer/devcontainer.json [2ms]
2022-11-08 20:01:35.390 [info] > git log --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%D%n%B -z -n4 -- /workspaces/next-idea/.devcontainer/devcontainer.json [1ms]
2022-11-08 20:01:35.839 [info] > git status -z -uall [10ms]
2022-11-08 20:01:35.839 [info] > git remote --verbose [18ms]
2022-11-08 20:01:35.839 [info] > git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname) [26ms]
2022-11-08 20:01:35.840 [info] > git config --get commit.template [2ms]
2022-11-08 20:01:35.852 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/burkeholland-another-branch refs/remotes/burkeholland-another-branch [2ms]
2022-11-08 20:01:35.966 [info] > git ls-files --stage -- /workspaces/next-idea/.devcontainer/devcontainer.json [1ms]
2022-11-08 20:01:35.974 [info] > git cat-file -s 4c922136a7b6e481a825f50259d68f38085850ae [1ms]
2022-11-08 20:01:36.063 [info] > git show --textconv :.devcontainer/devcontainer.json [2ms]
2022-11-08 20:01:36.408 [info] > git rev-list --count f4b39377f092ed94c53a2bb7c518e1fb818a70fa.. -- /workspaces/next-idea/.devcontainer/devcontainer.json [1ms]
2022-11-08 20:01:36.419 [info] > git log --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%D%n%B -z -n4 -- /workspaces/next-idea/.devcontainer/devcontainer.json [3ms]
2022-11-08 20:01:41.997 [info] > git push -u origin burkeholland-another-branch [830ms]
2022-11-08 20:01:41.997 [info] remote: 
remote: Create a pull request for 'burkeholland-another-branch' on GitHub by visiting:        
remote:      https://github.com/burkeholland/next-idea/pull/new/burkeholland-another-branch        
remote: 
To https://github.com/burkeholland/next-idea.git
 * [new branch]      burkeholland-another-branch -> burkeholland-another-branch
2022-11-08 20:01:42.027 [info] > git status -z -uall [7ms]
2022-11-08 20:01:42.028 [info] > git remote --verbose [15ms]
2022-11-08 20:01:42.028 [info] > git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname) [23ms]
2022-11-08 20:01:42.030 [info] > git config --get commit.template [2ms]
2022-11-08 20:01:42.038 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/burkeholland-another-branch refs/remotes/burkeholland-another-branch [2ms]
2022-11-08 20:01:42.069 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/burkeholland-another-branch refs/remotes/burkeholland-another-branch [13ms]
2022-11-08 20:01:42.078 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/burkeholland-another-branch refs/remotes/burkeholland-another-branch [30ms]
2022-11-08 20:01:42.080 [info] > git show -s --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%D%n%B -z cdf6698eb3dac824537ed5a5248c22a7501539ab [2ms]
2022-11-08 20:01:42.209 [info] > git config --local branch.burkeholland-another-branch.github-pr-owner-number [39ms]
2022-11-08 20:01:42.728 [info] > git rev-list --count f4b39377f092ed94c53a2bb7c518e1fb818a70fa.. -- /workspaces/next-idea/.devcontainer/devcontainer.json [2ms]
2022-11-08 20:01:42.771 [info] > git log --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%D%n%B -z -n4 -- /workspaces/next-idea/.devcontainer/devcontainer.json [6ms]
2022-11-08 20:01:43.177 [info] > git status -z -uall [7ms]
2022-11-08 20:01:43.178 [info] > git remote --verbose [13ms]
2022-11-08 20:01:43.178 [info] > git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname) [22ms]
2022-11-08 20:01:43.179 [info] > git config --get commit.template [1ms]
2022-11-08 20:01:43.188 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/burkeholland-another-branch refs/remotes/burkeholland-another-branch [1ms]
2022-11-08 20:01:43.302 [info] > git ls-files --stage -- /workspaces/next-idea/.devcontainer/devcontainer.json [2ms]
2022-11-08 20:01:43.311 [info] > git cat-file -s 4c922136a7b6e481a825f50259d68f38085850ae [1ms]
2022-11-08 20:01:43.393 [info] > git show --textconv :.devcontainer/devcontainer.json [2ms]
2022-11-08 20:01:43.770 [info] > git rev-list --count f4b39377f092ed94c53a2bb7c518e1fb818a70fa.. -- /workspaces/next-idea/.devcontainer/devcontainer.json [2ms]
2022-11-08 20:01:43.780 [info] > git log --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%D%n%B -z -n4 -- /workspaces/next-idea/.devcontainer/devcontainer.json [2ms]
2022-11-08 20:01:49.231 [info] > git status -z -uall [7ms]
2022-11-08 20:01:49.232 [info] > git remote --verbose [14ms]
2022-11-08 20:01:49.232 [info] > git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname) [26ms]
2022-11-08 20:01:49.233 [info] > git config --get commit.template [2ms]
2022-11-08 20:01:49.241 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/burkeholland-another-branch refs/remotes/burkeholland-another-branch [2ms]
2022-11-08 20:01:58.690 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/burkeholland-update-config refs/remotes/burkeholland-update-config [1ms]
2022-11-08 20:02:05.546 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/main refs/remotes/main [1ms]
2022-11-08 20:02:05.571 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/main refs/remotes/main [13ms]
2022-11-08 20:02:05.581 [info] > git show -s --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%D%n%B -z cdf6698eb3dac824537ed5a5248c22a7501539ab [3ms]
2022-11-08 20:02:10.614 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/burkeholland-update-config refs/remotes/burkeholland-update-config [1ms]
2022-11-08 20:02:10.623 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/burkeholland-update-config refs/remotes/burkeholland-update-config [1ms]
2022-11-08 20:02:10.631 [info] > git show -s --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%D%n%B -z cdf6698eb3dac824537ed5a5248c22a7501539ab [2ms]
2022-11-08 20:02:12.085 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/burkeholland-another-branch refs/remotes/burkeholland-another-branch [2ms]
2022-11-08 20:02:12.110 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/burkeholland-another-branch refs/remotes/burkeholland-another-branch [12ms]
2022-11-08 20:02:12.117 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/burkeholland-another-branch refs/remotes/burkeholland-another-branch [24ms]
2022-11-08 20:02:12.118 [info] > git show -s --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%D%n%B -z cdf6698eb3dac824537ed5a5248c22a7501539ab [2ms]
2022-11-08 20:02:14.699 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/burkeholland-another-branch refs/remotes/burkeholland-another-branch [2ms]
2022-11-08 20:02:16.085 [info] > git config --local branch.burkeholland-another-branch.github-pr-owner-number aprilla#next-idea#7 [1ms]
2022-11-08 20:02:16.112 [info] > git status -z -uall [7ms]
2022-11-08 20:02:16.112 [info] > git remote --verbose [13ms]
2022-11-08 20:02:16.113 [info] > git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname) [20ms]
2022-11-08 20:02:16.127 [info] > git config --get commit.template [15ms]
2022-11-08 20:02:16.137 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/burkeholland-another-branch refs/remotes/burkeholland-another-branch [2ms]
2022-11-08 20:02:16.311 [info] > git config --local branch.burkeholland-another-branch.github-pr-owner-number [40ms]
2022-11-08 20:02:16.342 [info] > git status -z -uall [9ms]
2022-11-08 20:02:16.343 [info] > git remote --verbose [17ms]
2022-11-08 20:02:16.343 [info] > git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname) [24ms]
2022-11-08 20:02:16.343 [info] > git config --get commit.template [2ms]
2022-11-08 20:02:16.361 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/burkeholland-another-branch refs/remotes/burkeholland-another-branch [11ms]
2022-11-08 20:02:17.059 [info] > git config --local -l [35ms]
2022-11-08 20:02:17.091 [info] > git status -z -uall [11ms]
2022-11-08 20:02:17.091 [info] > git remote --verbose [17ms]
2022-11-08 20:02:17.091 [info] > git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname) [24ms]
2022-11-08 20:02:17.093 [info] > git config --get commit.template [6ms]
2022-11-08 20:02:17.126 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/burkeholland-another-branch refs/remotes/burkeholland-another-branch [17ms]
2022-11-08 20:02:17.213 [info] > git config --local -l [26ms]
2022-11-08 20:02:17.236 [info] > git config --local -l [68ms]
2022-11-08 20:02:17.266 [info] > git status -z -uall [31ms] (cancelled)
2022-11-08 20:02:17.266 [info] > git status -z -uall [13ms]
2022-11-08 20:02:17.267 [info] > git remote --verbose [19ms]
2022-11-08 20:02:17.267 [info] > git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname) [26ms]
2022-11-08 20:02:17.267 [info] > git remote --verbose [38ms]
2022-11-08 20:02:17.267 [info] > git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname) [45ms]
2022-11-08 20:02:17.270 [info] > git config --get commit.template [4ms]
2022-11-08 20:02:17.270 [info] > git config --get commit.template [11ms]
2022-11-08 20:02:17.290 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/burkeholland-another-branch refs/remotes/burkeholland-another-branch [8ms]
2022-11-08 20:02:17.311 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/burkeholland-another-branch refs/remotes/burkeholland-another-branch [35ms]
2022-11-08 20:02:17.318 [info] > git status -z -uall [8ms]
2022-11-08 20:02:17.319 [info] > git remote --verbose [14ms]
2022-11-08 20:02:17.319 [info] > git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname) [20ms]
2022-11-08 20:02:17.320 [info] > git config --get commit.template [1ms]
2022-11-08 20:02:17.329 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/burkeholland-another-branch refs/remotes/burkeholland-another-branch [3ms]
2022-11-08 20:02:17.424 [info] > git show --textconv 998257a741f7ad674de9fa9733fef9d5aeef4f3c:.devcontainer/devcontainer.json [29ms]
2022-11-08 20:02:17.724 [info] > git config --local -l [51ms]
2022-11-08 20:02:17.754 [info] > git status -z -uall [8ms]
2022-11-08 20:02:17.754 [info] > git remote --verbose [14ms]
2022-11-08 20:02:17.754 [info] > git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname) [21ms]
2022-11-08 20:02:17.755 [info] > git config --get commit.template [3ms]
2022-11-08 20:02:17.785 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/burkeholland-another-branch refs/remotes/burkeholland-another-branch [13ms]
2022-11-08 20:02:17.962 [info] > git fetch origin burkeholland-another-branch [324ms]
2022-11-08 20:02:17.962 [info] From https://github.com/burkeholland/next-idea
 * branch            burkeholland-another-branch -> FETCH_HEAD
2022-11-08 20:02:18.054 [info] > git status -z -uall [49ms]
2022-11-08 20:02:18.055 [info] > git remote --verbose [55ms]
2022-11-08 20:02:18.055 [info] > git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname) [63ms]
2022-11-08 20:02:18.056 [info] > git config --get commit.template [45ms]
2022-11-08 20:02:18.069 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/burkeholland-another-branch refs/remotes/burkeholland-another-branch [3ms]
2022-11-08 20:02:18.464 [info] > git check-ignore -v -z --stdin [3ms]
2022-11-08 20:02:18.562 [info] > git fetch origin burkeholland-another-branch [296ms]
2022-11-08 20:02:18.562 [info] From https://github.com/burkeholland/next-idea
 * branch            burkeholland-another-branch -> FETCH_HEAD
2022-11-08 20:02:18.591 [info] > git status -z -uall [7ms]
2022-11-08 20:02:18.591 [info] > git remote --verbose [13ms]
2022-11-08 20:02:18.591 [info] > git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname) [20ms]
2022-11-08 20:02:18.592 [info] > git config --get commit.template [2ms]
2022-11-08 20:02:18.599 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/burkeholland-another-branch refs/remotes/burkeholland-another-branch [2ms]
2022-11-08 20:02:22.360 [info] > git status -z -uall [8ms]
2022-11-08 20:02:22.361 [info] > git remote --verbose [14ms]
2022-11-08 20:02:22.361 [info] > git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname) [21ms]
2022-11-08 20:02:22.362 [info] > git config --get commit.template [3ms]
2022-11-08 20:02:22.370 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/burkeholland-another-branch refs/remotes/burkeholland-another-branch [1ms]
2022-11-08 20:03:08.450 [info] > git fetch [293ms]
2022-11-08 20:03:08.477 [info] > git status -z -uall [6ms]
2022-11-08 20:03:08.478 [info] > git remote --verbose [12ms]
2022-11-08 20:03:08.478 [info] > git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname) [20ms]
2022-11-08 20:03:08.479 [info] > git config --get commit.template [1ms]
2022-11-08 20:03:08.487 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/burkeholland-another-branch refs/remotes/burkeholland-another-branch [1ms]
2022-11-08 20:03:09.568 [info] > git status -z -uall [8ms]
2022-11-08 20:03:09.568 [info] > git remote --verbose [15ms]
2022-11-08 20:03:09.568 [info] > git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname) [22ms]
2022-11-08 20:03:09.569 [info] > git config --get commit.template [3ms]
2022-11-08 20:03:09.579 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/burkeholland-another-branch refs/remotes/burkeholland-another-branch [1ms]
2022-11-08 20:03:36.649 [info] > git config --local branch.burkeholland-another-branch.github-pr-owner-number [1ms]
2022-11-08 20:03:36.675 [info] > git status -z -uall [8ms]
2022-11-08 20:03:36.676 [info] > git remote --verbose [14ms]
2022-11-08 20:03:36.676 [info] > git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname) [21ms]
2022-11-08 20:03:36.676 [info] > git config --get commit.template [3ms]
2022-11-08 20:03:36.684 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/burkeholland-another-branch refs/remotes/burkeholland-another-branch [2ms]
2022-11-08 20:03:37.489 [info] > git fetch origin burkeholland-another-branch [275ms]
2022-11-08 20:03:37.489 [info] From https://github.com/burkeholland/next-idea
 * branch            burkeholland-another-branch -> FETCH_HEAD
2022-11-08 20:03:37.519 [info] > git status -z -uall [7ms]
2022-11-08 20:03:37.520 [info] > git remote --verbose [15ms]
2022-11-08 20:03:37.520 [info] > git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname) [22ms]
2022-11-08 20:03:37.521 [info] > git config --get commit.template [1ms]
2022-11-08 20:03:37.528 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/burkeholland-another-branch refs/remotes/burkeholland-another-branch [1ms]
2022-11-08 20:03:38.114 [info] > git show --textconv 998257a741f7ad674de9fa9733fef9d5aeef4f3c:.devcontainer/devcontainer.json [33ms]
2022-11-08 20:03:39.740 [info] > git status -z -uall [6ms]
2022-11-08 20:03:39.741 [info] > git remote --verbose [13ms]
2022-11-08 20:03:39.741 [info] > git for-each-ref --sort -committerdate --format %(refname) %(objectname) %(*objectname) [19ms]
2022-11-08 20:03:39.742 [info] > git config --get commit.template [2ms]
2022-11-08 20:03:39.749 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/burkeholland-another-branch refs/remotes/burkeholland-another-branch [1ms]
```

**Comment by segevfiner** [comment]
Still happening in v0.56.0 on VS Code 1.74.0 😢

**Comment by alexr00** [comment]
Open one is here: https://github.com/microsoft/vscode-pull-request-github/issues/4002
