### ISSUE TITLE
Error: "webview is disposed"

### ISSUE THREAD

**Issue by flying-sausages** [microsoft/vscode-pull-request-github#2655]
Issue Type: <b>Bug</b>

The issue #1247 is reproducible with the following actions:

- push branch to upstram on the terminal
- click the link in the message from remote offering to start a Pull request
- choose to open the PR through the browser

Extension version: 0.25.1
VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:39:47.234Z)
OS version: Darwin arm64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|undefined|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv|--crash-reporter-id f7ed250b-de69-464a-b5ec-d35559c43420|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by flying-sausages** [comment]
<img width="505" alt="image" src="https://user-images.githubusercontent.com/23618693/114945931-89b45f00-9e4a-11eb-9c22-fbc0881d68b6.png">

**Comment by vassyz** [comment]
This error has been popping up a lot lately. I usually get it while rebasing.

**Comment by whephner** [comment]
I have been seeing it when I push.

**Comment by alexr00** [comment]
Next time some one sees this can you please open the dev tools (command Developer: Toggle Developer Tools) and share the contents of the console?

Even with the steps in this issue I can't repro. Steps:
1. Checkout a new branch from the terminal.
2. Make commit on this new branch.
3. From the terminal, push the new branch and set the upstream. This prints to the terminal:
```
PS D:\repos\alexr00\playground> git push --set-upstream origin alexr00/testwebview1
Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
remote:
remote: Create a pull request for 'alexr00/testwebview1' on GitHub by visiting:
remote:      https://github.com/alexr00/playground/pull/new/alexr00/testwebview1
remote:
To https://github.com/alexr00/playground.git
 * [new branch]      alexr00/testwebview1 -> alexr00/testwebview1
Branch 'alexr00/testwebview1' set up to track remote branch 'alexr00/testwebview1' from 'origin'.
```
4. Click on the new pull branch.
5. See the notification from this extension asking if I want to continue to GitHub.com to create the PR.
6. Choose to go to GitHub.com.

**Comment by vassyz** [comment]
@alexr00 Not sure how much I should copy, here's the line from the console that contains the error:

```
Webview is disposed
onDidChangeNotification @ workbench.desktop.main.js:735
```

Or: `workbench.desktop.main.js:formatted:139034`

I got this after running a `git pull`.

**Comment by mike-onehub** [comment]
@alexr00 I got this, here is my console output:
```
electron/js2c/renderer_init.js:65 The vm module of Node.js is deprecated in the renderer process and will be removed.
t._load @ electron/js2c/renderer_init.js:65
abstractExtensionService.ts:1071 Extension 'marlinfirmware.auto-build cannot use PROPOSED API (must started out of dev or enabled via --enable-proposed-api)
updateEnableProposedApi @ abstractExtensionService.ts:1071
abstractExtensionService.ts:909 [tht13.python]: 'configuration.jsonValidation.url' must be an absolute URL or start with './'  to reference schemas located in the extension.
_logMessageInConsole @ abstractExtensionService.ts:909
console.ts:137 [Extension Host] (node:99476) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.(Use `Code Helper (Renderer) --trace-deprecation ...` to show where the warning was created)
S @ console.ts:137
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope source.python.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/python/syntaxes/MagicPython.tmLanguage.json.
New grammar file: file:///Users/ghstridr/.vscode/extensions/magicstack.magicpython-1.1.0/grammars/MagicPython.tmLanguage
register @ TMScopeRegistry.ts:45
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope source.ruby.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/ruby/syntaxes/ruby.tmLanguage.json.
New grammar file: file:///Users/ghstridr/.vscode/extensions/puppet.puppet-vscode-1.3.0/syntaxes/puppetfile.cson.json
register @ TMScopeRegistry.ts:45
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope source.yaml.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/yaml/syntaxes/yaml.tmLanguage.json.
New grammar file: file:///Users/ghstridr/.vscode/extensions/redhat.vscode-yaml-0.20.0/syntaxes/yaml.tmLanguage.json
register @ TMScopeRegistry.ts:45
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope source.lua.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/lua/syntaxes/lua.tmLanguage.json.
New grammar file: file:///Users/ghstridr/.vscode/extensions/septh.wow-bundle-1.3.0/languages/grammars/lua.tmLanguage.json
register @ TMScopeRegistry.ts:45
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope source.python.
Old grammar file: file:///Users/ghstridr/.vscode/extensions/magicstack.magicpython-1.1.0/grammars/MagicPython.tmLanguage.
New grammar file: file:///Users/ghstridr/.vscode/extensions/tht13.python-0.2.3/syntaxes/python.tmLanguage
register @ TMScopeRegistry.ts:45
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope source.regexp.python.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/python/syntaxes/MagicRegExp.tmLanguage.json.
New grammar file: file:///Users/ghstridr/.vscode/extensions/tht13.python-0.2.3/syntaxes/Regular%20Expressions%20%28Python%29.tmLanguage
register @ TMScopeRegistry.ts:45
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope source.ruby.
Old grammar file: file:///Users/ghstridr/.vscode/extensions/puppet.puppet-vscode-1.3.0/syntaxes/puppetfile.cson.json.
New grammar file: file:///Users/ghstridr/.vscode/extensions/wingrunr21.vscode-ruby-0.28.0/syntaxes/ruby.cson.json
register @ TMScopeRegistry.ts:45
console.ts:137 [Extension Host] Message View AWS Toolkit Logs didn't get externalized correctly.
S @ console.ts:137
2console.ts:137 [Extension Host] Message Connecting... didn't get externalized correctly.
S @ console.ts:137
console.ts:137 [Extension Host] Message Add a region to AWS Explorer... didn't get externalized correctly.
S @ console.ts:137
console.ts:137 [Extension Host] Message Click here to add a region to AWS Explorer. didn't get externalized correctly.
S @ console.ts:137
mainThreadExtensionService.ts:95 Activating extension 'rafapaulin.try-material-icon-theme' failed: command 'material-icon-theme.activateIcons' already exists.
$onExtensionActivationError @ mainThreadExtensionService.ts:95
console.ts:137 [Extension Host] Message AWS Toolkit didn't get externalized correctly.
S @ console.ts:137
console.ts:137 [Extension Host] [Guides] Sending usage statistics...
console.ts:137 [Extension Host] Message AWS Remote Invocations didn't get externalized correctly.
S @ console.ts:137
console.ts:137 [Extension Host] [Guides] Error while sending usage statistics: Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: Host: api.digitalparticle.com. is not in the cert's altnames: DNS:firebaseapp.com, DNS:*.firebaseapp.com
console.ts:137 [Extension Host] [Guides] Usage statistics will retry in the next 5 minutes
console.ts:137 [Extension Host] [vscode-icons] v11.5.0 activated!
console.ts:137 [Extension Host] git shortlog -e -s -n HEAD  (completed in 0.684s)
console.ts:137 [Extension Host] git log --full-history --format=95E9659B-27DC-43C4-A717-D75969757EA5%P95E9659B-27DC-43C4-A717-D75969757EA6%p95E9659B-27DC-43C4-A717-D75969757EA6%D95E9659B-27DC-43C4-A717-D75969757EA6%an95E9659B-27DC-43C4-A717-D75969757EA6%ae95E9659B-27DC-43C4-A717-D75969757EA6%at95E9659B-27DC-43C4-A717-D75969757EA6%cn95E9659B-27DC-43C4-A717-D75969757EA6%ce95E9659B-27DC-43C4-A717-D75969757EA6%ct95E9659B-27DC-43C4-A717-D75969757EA6%b95E9659B-27DC-43C4-A717-D75969757EA6%N95E9659B-27DC-43C4-A717-D75969757EA6%H95E9659B-27DC-43C4-A717-D75969757EA6%h95E9659B-27DC-43C4-A717-D75969757EA6%T95E9659B-27DC-43C4-A717-D75969757EA6%t95E9659B-27DC-43C4-A717-D75969757EA6%s95E9659B-27DC-43C4-A717-D75969757EA695E9659B-27DC-43C4-A717-D75969757EA795E9659B-27DC-43C4-A717-D75969757EA695E9659B-27DC-43C4-A717-D75969757EA6 --date-order --decorate=full --skip=0 --max-count=100 8028_Email-Relay-Setup_sustainable-advantage.com --follow -- config/invitation_from_bypass_domains.yml  (completed in 1.303s)
console.ts:137 [Extension Host] git rev-list --full-history --count 8028_Email-Relay-Setup_sustainable-advantage.com -- config/invitation_from_bypass_domains.yml  (completed in 1.397s)
console.ts:137 [Extension Host] git rev-list --full-history --count 8028_Email-Relay-Setup_sustainable-advantage.com -- config/invitation_from_bypass_domains.yml  (completed in 0.696s)
console.ts:137 [Extension Host] git log --full-history --format=95E9659B-27DC-43C4-A717-D75969757EA5%P95E9659B-27DC-43C4-A717-D75969757EA6%p95E9659B-27DC-43C4-A717-D75969757EA6%D95E9659B-27DC-43C4-A717-D75969757EA6%an95E9659B-27DC-43C4-A717-D75969757EA6%ae95E9659B-27DC-43C4-A717-D75969757EA6%at95E9659B-27DC-43C4-A717-D75969757EA6%cn95E9659B-27DC-43C4-A717-D75969757EA6%ce95E9659B-27DC-43C4-A717-D75969757EA6%ct95E9659B-27DC-43C4-A717-D75969757EA6%b95E9659B-27DC-43C4-A717-D75969757EA6%N95E9659B-27DC-43C4-A717-D75969757EA6%H95E9659B-27DC-43C4-A717-D75969757EA6%h95E9659B-27DC-43C4-A717-D75969757EA6%T95E9659B-27DC-43C4-A717-D75969757EA6%t95E9659B-27DC-43C4-A717-D75969757EA6%s95E9659B-27DC-43C4-A717-D75969757EA695E9659B-27DC-43C4-A717-D75969757EA795E9659B-27DC-43C4-A717-D75969757EA695E9659B-27DC-43C4-A717-D75969757EA6 --date-order --decorate=full --skip=0 --max-count=100 8028_Email-Relay-Setup_sustainable-advantage.com --follow -- config/invitation_from_bypass_domains.yml  (completed in 0.747s)
log.ts:296   ERR unknown handler: Error: unknown handler
    at o.$unregisterCommentController (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2699:51445)
    at r._doInvokeHandler (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1832:11905)
    at r._invokeHandler (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1832:11597)
    at r._receiveRequest (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1832:10259)
    at r._receiveOneMessage (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1832:9062)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1832:7166
    at n.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:60:1835)
    at a.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:76:16288)
    at i._receiveMessage (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:76:21546)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:76:18432
    at n.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:60:1835)
    at h.acceptChunk (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:76:13649)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:76:12997
    at Socket.D (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2938:132926)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
console.ts:137 [Extension Host] git rev-list --full-history --count 8028_Email-Relay-Setup_sustainable-advantage.com -- config/invitation_from_bypass_domains.yml  (completed in 1.114s)
console.ts:137 [Extension Host] git log --full-history --format=95E9659B-27DC-43C4-A717-D75969757EA5%P95E9659B-27DC-43C4-A717-D75969757EA6%p95E9659B-27DC-43C4-A717-D75969757EA6%D95E9659B-27DC-43C4-A717-D75969757EA6%an95E9659B-27DC-43C4-A717-D75969757EA6%ae95E9659B-27DC-43C4-A717-D75969757EA6%at95E9659B-27DC-43C4-A717-D75969757EA6%cn95E9659B-27DC-43C4-A717-D75969757EA6%ce95E9659B-27DC-43C4-A717-D75969757EA6%ct95E9659B-27DC-43C4-A717-D75969757EA6%b95E9659B-27DC-43C4-A717-D75969757EA6%N95E9659B-27DC-43C4-A717-D75969757EA6%H95E9659B-27DC-43C4-A717-D75969757EA6%h95E9659B-27DC-43C4-A717-D75969757EA6%T95E9659B-27DC-43C4-A717-D75969757EA6%t95E9659B-27DC-43C4-A717-D75969757EA6%s95E9659B-27DC-43C4-A717-D75969757EA695E9659B-27DC-43C4-A717-D75969757EA795E9659B-27DC-43C4-A717-D75969757EA695E9659B-27DC-43C4-A717-D75969757EA6 --date-order --decorate=full --skip=0 --max-count=100 8028_Email-Relay-Setup_sustainable-advantage.com --follow -- config/invitation_from_bypass_domains.yml  (completed in 1.116s)
console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error: Cannot resolve tree item for element 0/0:custom_relay_domains.yml
S @ console.ts:137
console.ts:137 [Extension Host] stack trace: Error: Cannot resolve tree item for element 0/0:custom_relay_domains.yml	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:61104	at runMicrotasks (<anonymous>)	at processTicksAndRejections (internal/process/task_queues.js:93:5)
S @ console.ts:137
log.ts:296   ERR Cannot resolve tree item for element 0/0:custom_relay_domains.yml: Error: Cannot resolve tree item for element 0/0:custom_relay_domains.yml
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:61104
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
3log.ts:296   ERR unknown handler: Error: unknown handler
    at o.$unregisterCommentController (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2699:51445)
    at r._doInvokeHandler (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1832:11905)
    at r._invokeHandler (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1832:11597)
    at r._receiveRequest (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1832:10259)
    at r._receiveOneMessage (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1832:9062)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1832:7166
    at n.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:60:1835)
    at a.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:76:16288)
    at i._receiveMessage (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:76:21546)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:76:18432
    at n.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:60:1835)
    at h.acceptChunk (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:76:13649)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:76:12997
    at Socket.D (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2938:132926)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
notificationsAlerts.ts:40 Webview is disposed
onDidChangeNotification @ notificationsAlerts.ts:40
```

**Comment by alexr00** [comment]
Thanks @mike-onehub. Looks like there are a lot of errors leading up to the titular problem. I'll start by trying to work through those.

**Comment by alexr00** [comment]
Found a reliably way to repro:
1. Checkout a PR
2. Open the PR overview
3. Change branches from command line
4. Change branches back to the PR branch from the command line.

Error comes from here:
https://github.com/microsoft/vscode-pull-request-github/blob/2384341c9a49da7ba550847e1399c3bb0c819c12/src/github/pullRequestOverview.ts#L237-L238

**Comment by alexr00** [comment]
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/2444

**Comment by Royhtml** [comment]
<img width="1236" height="660" alt="Image" src="https://github.com/user-attachments/assets/05a82177-2334-4e1e-b7fe-d2418daba8a5" />
Xampp Meta Panel
There are new tools for programmers that are perfectly suited for the needs of all types of servers.
