### ISSUE TITLE
Review comments provider not working

### ISSUE THREAD

**Issue by RMacfarlane** [Microsoft/vscode-pull-request-github#271]
1. Checkout out a pull request that has some comments
2. Click on a comment in the comments panel

The file opens, but no commenting ranges or comments are shown in the document. No errors in the output channel

**Comment by RMacfarlane** [comment]
```
ERR Unexpected end of JSON input: SyntaxError: Unexpected end of JSON input
log.ts:171
	at JSON.parse (<anonymous>)
	at Object.t.fromPRUri (/Users/ramacfar/.vscode-oss-dev/extensions/microsoft.vscode-pull-request-github-0.0.15/media/extension.js:1:1690)
	at s.<anonymous> (/Users/ramacfar/.vscode-oss-dev/extensions/microsoft.vscode-pull-request-github-0.0.15/media/extension.js:1:106641)
	at Generator.next (<anonymous>)
	at i (/Users/ramacfar/.vscode-oss-dev/extensions/microsoft.vscode-pull-request-github-0.0.15/media/extension.js:1:106141)
	at new Promise (<anonymous>)
	at i (/Users/ramacfar/.vscode-oss-dev/extensions/microsoft.vscode-pull-request-github-0.0.15/media/extension.js:1:105918)
	at s.provideDocumentComments (/Users/ramacfar/.vscode-oss-dev/extensions/microsoft.vscode-pull-request-github-0.0.15/media/extension.js:1:106592)
```
