### ISSUE TITLE
TypeError: Cannot read property 'dispose' of undefined

### ISSUE THREAD

**Issue by RikkiGibson** [microsoft/vscode-pull-request-github#2725]
- Extension version: 0.26.0
- VSCode Version: 1.56.0
- OS: Window 10 19042.928

Steps to Reproduce:

I don't know exactly how I produced this except that:
1. I was in review mode on a PR.
2. After some time spend reviewing (maybe sleeping/waking the PC, etc.), I clicked  back over to the "GitHub" tab
3. I saw this notification and the pull requests list was empty in the UI
![image](https://user-images.githubusercontent.com/5833655/117720608-b6cb0780-b193-11eb-97f3-cf716fbfba48.png)

Saw this stack trace in the inspector:
```
TypeError: Cannot read property 'dispose' of undefined
	at c:\Users\rikki\.vscode\extensions\github.vscode-pull-request-github-0.26.0\dist\extension.js:1005:21634
	at Array.forEach (<anonymous>)
	at c:\Users\rikki\.vscode\extensions\github.vscode-pull-request-github-0.26.0\dist\extension.js:1005:21621
	at Array.forEach (<anonymous>)
	at Md.dispose (c:\Users\rikki\.vscode\extensions\github.vscode-pull-request-github-0.26.0\dist\extension.js:1005:21581)
	at Object.dispose (c:\Users\rikki\.vscode\extensions\github.vscode-pull-request-github-0.26.0\dist\extension.js:1005:23035)
	at c:\Users\rikki\.vscode\extensions\github.vscode-pull-request-github-0.26.0\dist\extension.js:1066:402
	at Array.forEach (<anonymous>)
	at Mu.dispose (c:\Users\rikki\.vscode\extensions\github.vscode-pull-request-github-0.26.0\dist\extension.js:1066:389)
	at c:\Users\rikki\.vscode\extensions\github.vscode-pull-request-github-0.26.0\dist\extension.js:1062:1904
	at Array.forEach (<anonymous>)
	at Va.dispose (c:\Users\rikki\.vscode\extensions\github.vscode-pull-request-github-0.26.0\dist\extension.js:1062:1891)
	at c:\Users\rikki\.vscode\extensions\github.vscode-pull-request-github-0.26.0\dist\extension.js:1090:17562
	at Array.forEach (<anonymous>)
	at Wl.getChildren (c:\Users\rikki\.vscode\extensions\github.vscode-pull-request-github-0.26.0\dist\extension.js:1090:17549)
	at d.fetchChildrenNodes (c:\Users\rikki\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:87:61023)
	at d.getChildren (c:\Users\rikki\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:87:57862)
	at a.$getChildren (c:\Users\rikki\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:87:54839)
	at l._doInvokeHandler (c:\Users\rikki\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:91:12836)
	at l._invokeHandler (c:\Users\rikki\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:91:12520)
	at l._receiveRequest (c:\Users\rikki\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:91:11187)
	at l._receiveOneMessage (c:\Users\rikki\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:91:10172)
	at c:\Users\rikki\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:91:8074
	at fire (c:\Users\rikki\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1836)
	at S.fire (c:\Users\rikki\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:15497)
	at c:\Users\rikki\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:106:29764
	at fire (c:\Users\rikki\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1836)
	at S.fire (c:\Users\rikki\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:15497)
	at t._receiveMessage (c:\Users\rikki\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:20755)
	at c:\Users\rikki\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:17641
	at fire (c:\Users\rikki\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1836)
	at acceptChunk (c:\Users\rikki\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:12862)
	at c:\Users\rikki\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:12210
	at Socket.v (c:\Users\rikki\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:106:13195)
	at Socket.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.Readable.push (internal/streams/readable.js:223:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
onDidChangeNotification @ workbench.desktop.main.js:735
```

**Comment by alexr00** [comment]
Note for later looks like it's somewhere in here:

https://github.com/microsoft/vscode-pull-request-github/blob/63fe15d9c4dcc904ff8311a246acfae547f1b514/src/view/pullRequestCommentController.ts#L469-L478

**Comment by RikkiGibson** [comment]
I don't know if this provides insight, but I noticed that when the bug occurs and the pull requests list is empty, clicking "Refresh Pull Requests List" brings them back.

**Comment by alexr00** [comment]
Well, I found a place where something wasn't getting disposed properly, but I'm not sure if it could be causing this issue. The fix will be available in 0.28.0 and in the next nightly build.

**Comment by TylerLeonhardt** [comment]
@alexr00 got any verification steps?

**Comment by alexr00** [comment]
No steps for this as I'm not 100% certain about the cause of the issue. We'll call it verified since there have been no other reports of it.
