### ISSUE TITLE
Fetching pull requests for remote 'origin' failed, please check if the url . . . is valid.

### ISSUE THREAD

**Issue by DMCTowns** [microsoft/vscode-pull-request-github#3095]
Possibly related to closed issue #1941 but am reporting again as instructed at the bottom of the thread on that issue.

- Extension version: 0.32.0
- VSCode Version: 1.62.0
- OS: OS X 12.0.1

**Steps to Reproduce:**
1. Private repository
2. Remote URL in the format: https://***username***:***personal_access_token***@github.com/***organisation***/***repo***.git
3. Load workspace 
4. Receive an error notification: "Fetching pull requests for remote 'origin' failed, please check if the url https://***:***@github.com/***/***.git is valid. Source GitHub Pull Requests and Issues (Extension)"

**Developer Tools Output**
```
[GitHub.vscode-pull-request-github]: workbench.desktop.main.js:sourcemap:2967 `remoteHub/pullRequest` is not a valid menu identifier

ERR [Extension Host]  _logMessageInConsole @ workbench.desktop.main.js:sourcemap:2967
workbench.desktop.main.js:sourcemap:602   (node:27692) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code Helper (Renderer) --trace-deprecation ...` to show where the warning was created)
workbench.desktop.main.js:sourcemap:77 

[Extension Host] (node:27692) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.(Use `Code Helper (Renderer) --trace-deprecation ...` to show where the warning was created)
E @ workbench.desktop.main.js:sourcemap:77

[Extension Host] ftp-simple start :  workbench.desktop.main.js:sourcemap:77 /Users/diccon/Library/Application Support/Code/User/globalStorage/humy2833.ftp-simple/ftp-simple.json

[Extension Host] WorkSpacePath : workbench.desktop.main.js:sourcemap:77 /Users/diccon/Web Server/html/S2S-1.GIT
workbench.desktop.main.js:sourcemap:77 

[Extension Host] Deprecation: [@octokit/request-error] `error.code` is deprecated, use `error.status`.	at zn.get (/Users/diccon/.vscode/extensions/github.vscode-pull-request-github-0.32.0/dist/extension.js:1063:22834)	at nt.getPullRequestForBranch (/Users/diccon/.vscode/extensions/github.vscode-pull-request-github-0.32.0/dist/extension.js:1110:30422)	at processTicksAndRejections (internal/process/task_queues.js:93:5)	at async vn.getMatchingPullRequestMetadataFromGitHub (/Users/diccon/.vscode/extensions/github.vscode-pull-request-github-0.32.0/dist/extension.js:1121:5780)	at async np.validateState (/Users/diccon/.vscode/extensions/github.vscode-pull-request-github-0.32.0/dist/extension.js:1152:33951)
E @ workbench.desktop.main.js:sourcemap:77
```

5. Run 'Github Pull Requests: Create Pull Request'

**Developer tools output:**
```
console.ts:137 [Extension Host] rejected promise not handled within 1 second: HttpError: Not Found
E @ console.ts:137

$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:472
_invokeHandler @ rpcProtocol.ts:457
_receiveRequest @ rpcProtocol.ts:373
_receiveOneMessage @ rpcProtocol.ts:295
(anonymous) @ rpcProtocol.ts:160
fire @ event.ts:577
fire @ ipc.net.ts:513
_receiveMessage @ ipc.net.ts:871
(anonymous) @ ipc.net.ts:710
fire @ event.ts:577
acceptChunk @ ipc.net.ts:286
(anonymous) @ ipc.net.ts:247
k @ ipc.net.ts:50
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188

console.ts:137 [Extension Host] stack trace: HttpError: Not Found	at /Users/diccon/.vscode/extensions/github.vscode-pull-request-github-0.32.0/dist/extension.js:1063:23870	at processTicksAndRejections (internal/process/task_queues.js:93:5)	at async nt.getMetadata (/Users/diccon/.vscode/extensions/github.vscode-pull-request-github-0.32.0/dist/extension.js:1110:27266)	at async vn.getPullRequestDefaults (/Users/diccon/.vscode/extensions/github.vscode-pull-request-github-0.32.0/dist/extension.js:1111:11267)	at async Eg.create (/Users/diccon/.vscode/extensions/github.vscode-pull-request-github-0.32.0/dist/extension.js:1152:14797)

E @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:472
_invokeHandler @ rpcProtocol.ts:457
_receiveRequest @ rpcProtocol.ts:373
_receiveOneMessage @ rpcProtocol.ts:295
(anonymous) @ rpcProtocol.ts:160
fire @ event.ts:577
fire @ ipc.net.ts:513
_receiveMessage @ ipc.net.ts:871
(anonymous) @ ipc.net.ts:710
fire @ event.ts:577
acceptChunk @ ipc.net.ts:286
(anonymous) @ ipc.net.ts:247
k @ ipc.net.ts:50
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188
mainThreadExtensionService.ts:63 [[object Object]]Not Found
$onExtensionRuntimeError @ mainThreadExtensionService.ts:63
_doInvokeHandler @ rpcProtocol.ts:472
_invokeHandler @ rpcProtocol.ts:457
_receiveRequest @ rpcProtocol.ts:373
_receiveOneMessage @ rpcProtocol.ts:295
(anonymous) @ rpcProtocol.ts:160
fire @ event.ts:577
fire @ ipc.net.ts:513
_receiveMessage @ ipc.net.ts:871
(anonymous) @ ipc.net.ts:710
fire @ event.ts:577
acceptChunk @ ipc.net.ts:286
(anonymous) @ ipc.net.ts:247
k @ ipc.net.ts:50
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188

mainThreadExtensionService.ts:64 HttpError: Not Found
	at vscode-file://vscode-app/Users/diccon/.vscode/extensions/github.vscode-pull-request-github-0.32.0/dist/extension.js:1063
	at processTicksAndRejections (internal/process/task_queues.js:93)
	at async nt.getMetadata (vscode-file://vscode-app/Users/diccon/.vscode/extensions/github.vscode-pull-request-github-0.32.0/dist/extension.js:1110)
	at async vn.getPullRequestDefaults (vscode-file://vscode-app/Users/diccon/.vscode/extensions/github.vscode-pull-request-github-0.32.0/dist/extension.js:1111)
	at async Eg.create (vscode-file://vscode-app/Users/diccon/.vscode/extensions/github.vscode-pull-request-github-0.32.0/dist/extension.js:1152)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:64
_doInvokeHandler @ rpcProtocol.ts:472
_invokeHandler @ rpcProtocol.ts:457
_receiveRequest @ rpcProtocol.ts:373
_receiveOneMessage @ rpcProtocol.ts:295
(anonymous) @ rpcProtocol.ts:160
fire @ event.ts:577
fire @ ipc.net.ts:513
_receiveMessage @ ipc.net.ts:871
(anonymous) @ ipc.net.ts:710
fire @ event.ts:577
acceptChunk @ ipc.net.ts:286
(anonymous) @ ipc.net.ts:247
k @ ipc.net.ts:50
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188
```

**Comment by alexr00** [comment]
@DMCTowns is your account GitHub enterprise?

**Comment by jcoconnor** [comment]
I'm getting similar - installed extension for first time today and can't fetch Pull Requests from internal corporate github repository.

**Comment by kaveryanovGFL** [comment]
Here's what helped me. I made an access token in GitHub
and then locally from the root repository folder in the terminal run 
git remote set-url origin https://USER:access token@github.com/REPO.git

**Comment by MigdaliyrArchitect** [comment]
I am also having this issue. Non-Enterprise account. I have attempted changing the credential manager as well as switching from HTTPS to SSH but this extension refuses to authenticate and connect. Git from the command line works, as does GithubCLI.

**Comment by MigdaliyrArchitect** [comment]
Thanks for nothing.

**Comment by jcoconnor** [comment]
Does seem a bit rude to close without giving a reason.

**Comment by alexr00** [comment]
Hi folks in this thread: the original issue writer didn't respond to a question, so the original issue was not actionable. Closing the issue without the comment to that effect was an oversight on my part. 

If you're seeing similar issues (or other issues!) please feel free to open another issue and I would be happy to take a look. Logs and screenshots usually make it easier/faster to understand what's going on.

**Comment by fcFn** [comment]
I was able to solve it by using the "GitHub Pull Requests: Sign in to GitHub" command, then selecting the gear near the extension and selecting the account that has access to the private repository for which I was trying to fetch PRs.
