### ISSUE TITLE
Request file/read failed with message: No file system provider found for resource

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-pull-request-github#3198]
- Extension version: v0.35.2021121509
- VSCode Version: 1.64-insider (insiders.vscode.dev)
- OS: Windows 11

Steps to Reproduce:

1. Go to https://insiders.vscode.dev/github/python/cpython/pull/29581
2. Open a bunch of modified files in the diff editor very quickly
3. 🐛 see this error message a lot in dev tools: 
![image](https://user-images.githubusercontent.com/30305945/146226395-6404b49c-cf0f-4e99-81a5-3696bc9fe78d.png)

**Comment by alexr00** [comment]
@jrieken this error is coming from Any Code. GHPRI uses the `"review"` scheme for diffs. We don't register a file system provider though, just a `TextDocumentContentProvider`. Any Code appears to be doing `vscode.workspace.fs.stat` on some of the `"review"` files, which then fails.

This seems like it should be handled in Any Code since not all files that it `stats` will necessarily be `statable`.

**Comment by alexr00** [comment]
Full stack:

```
Uncaught (in promise) Error: Request file/read failed with message: No file system provider found for resource 'review://github%2B7b2276223a312c22726566223a7b2274797065223a332c226964223a223239353831227d7d/python/cpython/Include/internal/pycore_ast_state.h?%7B%22path%22%3A%22Include%2Finternal%2Fpycore_ast_state.h%22%2C%22commit%22%3A%229130a4d62032468e0d4949aaa49c29afb0d854ca%22%2C%22base%22%3Atrue%2C%22isOutdated%22%3Afalse%2C%22rootPath%22%3A%22%2Fpython%2Fcpython%22%7D'
    at handleResponse (extension.js:2071:40)
    at processMessageQueue (extension.js:1896:13)
    at eval (extension.js:1882:11)
ResponseError @ extension.js:563
handleResponse @ extension.js:2071
processMessageQueue @ extension.js:1896
eval @ extension.js:1882
setTimeout (async)
setImmediate @ extension.js:479
triggerMessageQueue @ extension.js:1880
callback @ extension.js:1933
invoke @ extension.js:127
fire @ extension.js:178
BrowserMessageReader._messageListener @ extension.js:2900
```
