### ISSUE TITLE
Outdated comments in a non-checked out PR cause a console error

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#3289]
```
rejected promise not handled within 1 second: Error: Illegal argument: line must be non-negative
[c:\Program]() Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:112
stack trace: Error: Illegal argument: line must be non-negative
    at y ([c:\Program]() Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:5:1247)
    at new p ([c:\Program]() Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:84:18560)
    at new p (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:84:17955)
    at [d:\repos\Microsoft\vscode-pull-request-github\dist\webpack]():\vscode-pull-request-github\src\view\pullRequestCommentController.ts:172:8
    at Array.map (<anonymous>)
    at [d:\repos\Microsoft\vscode-pull-request-github\dist\webpack]():\vscode-pull-request-github\src\view\pullRequestCommentController.ts:170:7
    at Array.forEach (<anonymous>)
    at PullRequestCommentController.addThreadsForEditors ([d:\repos\Microsoft\vscode-pull-request-github\dist\webpack]():\vscode-pull-request-github\src\view\pullRequestCommentController.ts:161:11)
    at PullRequestCommentController.onDidChangeOpenEditors ([d:\repos\Microsoft\vscode-pull-request-github\dist\webpack]():\vscode-pull-request-github\src\view\pullRequestCommentController.ts:232:9)
    at [d:\repos\Microsoft\vscode-pull-request-github\dist\webpack]():\vscode-pull-request-github\src\view\pullRequestCommentController.ts:65:10
    at l.fire ([c:\Program]() Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:64:1712)
    at [c:\Program]() Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:94:64933
    at l.fire ([c:\Program]() Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:64:1712)
    at p.acceptDocumentsAndEditorsDelta ([c:\Program]() Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:93:74645)
    at p.$acceptDocumentsAndEditorsDelta ([c:\Program]() Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:93:72836)
    at i._doInvokeHandler ([c:\Program]() Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:97:13801)
    at i._invokeHandler ([c:\Program]() Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:97:13485)
    at i._receiveRequest ([c:\Program]() Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:97:12147)
    at i._receiveOneMessage ([c:\Program]() Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:97:10825)
    at [c:\Program]() Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:97:8934
    at l.fire ([c:\Program]() Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:64:1712)
    at s.fire ([c:\Program]() Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:19002)
    at [c:\Program]() Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:112:34390
    at l.fire ([c:\Program]() Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:64:1712)
    at s.fire ([c:\Program]() Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:19002)
    at a._receiveMessage ([c:\Program]() Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:23583)
    at [c:\Program]() Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:21117
    at l.fire ([c:\Program]() Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:64:1712)
    at _.acceptChunk ([c:\Program]() Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:15833)
    at [c:\Program]() Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:72:14963
    at Socket.A ([c:\Program]() Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:112:13838)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
    at Pipe.callbackTrampoline (internal/async_hooks.js:131:14)
```

This also causes some comments not to be fully added, so if you try to edit a comment later then there will be more errors and possible bugs.

**Comment by rchiodo** [comment]
@alexr00 can you list some verification steps? Thanks.

**Comment by alexr00** [comment]
To verify:
1. Setup or already have a PR in the following way (can be done from extension or github.com)
  a. Make a commit.
  b. Create the PR.
  c. Add a comment to a line in the PR.
  d. Make a commit in which you delete the line that the comment from (c) was on.
  e. Push commit to PR branch.
2. Install GitHub Pull Requests and Issue pre-release.
3. Open the repository from (1) in VS Code and check out any branch _except_ the PR branch.
4. Go to the Pull Requests view.
5. Expand the the PR that you made in (1)
6. Open the file diff from (1c) using the Pull Requests view
7. Open the developer tools and verify that you don't see the exception in the issue.
