### ISSUE TITLE
ETIMEDOUT when fetching pull request

### ISSUE THREAD

**Issue by nitishblkbox** [microsoft/vscode-pull-request-github#3569]
The extension goes to timeout everytime.
I have tried uninstalling the extension and VSCode alongwith clearing all VSCode data as suggested in documentation but the issue still persists. Note: The issue started happening after I had some network issues and I decided to logout and login to the extension but the login did not work. After reinstalling everything login seems to be working fine, even getting the list of pull requests works but when I click on a pull request to it starts loading for a long time and then prompts me with this.

<img width="411" alt="Screenshot 2022-05-26 at 4 20 43 PM" src="https://user-images.githubusercontent.com/89137271/170473813-595784f0-fe42-4d96-97ec-9a110cb3a917.png">

Debug logs show something is going wrong.
```
[Debug 1653503299.703s] GitHubRepository> Fetch issues with query - done
[Debug 1653503299.709s] GitHubRepository> Fetch issues with query - done
[Debug 1653503299.716s] GitHubRepository> Fetch issues with query - done
[Debug 1653503311.766s] Error signing in to GitHub: HttpError: request to https://api.github.com/user failed, reason: connect ETIMEDOUT 13.234.168.60:443
[Debug 1653503311.767s] HttpError: request to https://api.github.com/user failed, reason: connect ETIMEDOUT 13.234.168.60:443
	at /Users/nitish/.vscode/extensions/github.vscode-pull-request-github-0.42.0/dist/extension.js:1039:6565
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async Xm.setCurrentUser (/Users/nitish/.vscode/extensions/github.vscode-pull-request-github-0.42.0/dist/extension.js:1056:16311)
	at async Xm.createHub (/Users/nitish/.vscode/extensions/github.vscode-pull-request-github-0.42.0/dist/extension.js:1056:17492)
	at async Xm.login (/Users/nitish/.vscode/extensions/github.vscode-pull-request-github-0.42.0/dist/extension.js:1056:15481)
	at async tm.authenticate (/Users/nitish/.vscode/extensions/github.vscode-pull-request-github-0.42.0/dist/extension.js:1185:17558)
	at async /Users/nitish/.vscode/extensions/github.vscode-pull-request-github-0.42.0/dist/extension.js:1185:6195
	at async o._executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:31325)
[Debug 1653503313.068s] GithubRepository> Unable to fetch issues with query: Error: Network error: request to https://api.github.com/graphql failed, reason: connect ETIMEDOUT 13.234.168.60:443
[Debug 1653503313.068s] GithubRepository> Unable to fetch issues with query: Error: Network error: request to https://api.github.com/graphql failed, reason: connect ETIMEDOUT 13.234.168.60:443
[Debug 1653503313.068s] GithubRepository> Unable to fetch issues with query: Error: Network error: request to https://api.github.com/graphql failed, reason: connect ETIMEDOUT 13.234.168.60:443
[Debug 1653503313.069s] GithubRepository> Unable to fetch issues with query: Error: Network error: request to https://api.github.com/graphql failed, reason: connect ETIMEDOUT 13.234.168.60:443
[Debug 1653503313.069s] GithubRepository> Unable to fetch issues with query: Error: Network error: request to https://api.github.com/graphql failed, reason: connect ETIMEDOUT 13.234.168.60:443
[Debug 1653503313.069s] GithubRepository> Unable to fetch issues with query: Error: Network error: request to https://api.github.com/graphql failed, reason: connect ETIMEDOUT 13.234.168.60:443
```

- Extension version: 0.42.0
- VSCode Version: 1.67.2 Commit: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
- OS: Mac OS Monterey

Steps to Reproduce:

1. Have a network issue, logout of the extension
2. Log back in

**Comment by nitishblkbox** [comment]
The problem went away on it's own, I'll reopen if this happens again once your changes are available in the official release.

**Comment by ogahga** [comment]
it still happening. In almost every PR. 

<img width="569" height="201" alt="Image" src="https://github.com/user-attachments/assets/63e27edc-32de-45df-b1a0-b07187992bd8" />
