### ISSUE TITLE
Empty branch pickers in "Create Pull Request" view

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-pull-request-github#3592]
Don't have perfect steps but I think I just did this
- Opened vscode in our repo
- Check out the branch `roblou/issue142870_2`
- Run "Create Pull Request"
- Get empty fields in the view. When I click the dropdowns to pick a branch, nothing happens

<img width="370" alt="image" src="https://user-images.githubusercontent.com/323878/172267451-255c829a-d03d-4ff4-abe8-7b452e94d6d0.png">

[ghpr.log](https://github.com/microsoft/vscode-pull-request-github/files/8848965/ghpr.log)

I see this error:

```
[2022-06-06 16:39:09.866] [renderer1] [error] Failed to execute git
[2022-06-06 16:40:44.405] [renderer1] [error] Not Found: HttpError: Not Found
    at /Users/roblou/.vscode-insiders/extensions/github.vscode-pull-request-github-0.43.2022060609/dist/extension.js:1075:6173
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at xt.compareCommits (/Users/roblou/.vscode-insiders/extensions/github.vscode-pull-request-github-0.43.2022060609/dist/extension.js:1168:41969)
    at Kh.getTotalGitHubCommits (/Users/roblou/.vscode-insiders/extensions/github.vscode-pull-request-github-0.43.2022060609/dist/extension.js:1180:43565)
```

**Comment by roblourens** [comment]
I have been using the pr extension heavily and have not seen this since the fix
