### ISSUE TITLE
Cannot view more than 100 and few files in PR

### ISSUE THREAD

**Issue by ShlomiAltostra** [microsoft/vscode-pull-request-github#3623]
- Extension version: 0.44.0
- VSCode Version: 1.68.0
- OS: Windows 11 build 22000.708 (with WSL Ubuntu 20.04)

Steps to Reproduce:
1. Create PR with a lot of files
2. Review files in the extension
3. After 100 or so files, no more files could be displayed

Viewing file error
![image](https://user-images.githubusercontent.com/57314279/173597890-93777f2a-244b-4058-abfa-bc1567809bde.png)

Marking file as viewed:
![image](https://user-images.githubusercontent.com/57314279/173598088-e0a0024b-24f6-46df-ad05-894b05616b8e.png)

~~This coincides with GitHub not loading diffs by default (hope it is related)~~ (found to be untrue)
![image](https://user-images.githubusercontent.com/57314279/173599799-2538ccf1-6b90-4974-9021-cd4c4e697147.png)

**Comment by alexr00** [comment]
@ShlomiAltostra would you be willing to try the [pre-release](https://github.com/microsoft/vscode-pull-request-github/wiki/Pre-release-Build) version of the extension? Last week I made a significant perf improvement (https://github.com/microsoft/vscode-pull-request-github/commit/f467882fc6b4651ebbbe66c4d9868f9d151047c3) for large PRs and the change is currently only available in the pre-release build.

**Comment by ShlomiAltostra** [comment]
@alexr00 
The bug persists after clicking on `Switch to pre-relseae version` and reloading vscode

Installed version is `v0.45.2022061`

Console in vscode dev-tools has the following errors:

Open file:
```
  ERR TreeError [pr:github] Data tree node not found: [object Object]: Error: TreeError [pr:github] Data tree node not found: [object Object]
    at ce.getDataNode (vscode-file://vscode-app/c:/Users/Shlomi/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:220:19897)
    at ce.rerender (vscode-file://vscode-app/c:/Users/Shlomi/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:220:17399)
    at vscode-file://vscode-app/c:/Users/Shlomi/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2975:13268
    at m.invoke (vscode-file://vscode-app/c:/Users/Shlomi/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:145)
    at s.deliver (vscode-file://vscode-app/c:/Users/Shlomi/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:2265)
    at o.fire (vscode-file://vscode-app/c:/Users/Shlomi/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:1843)
    at vscode-file://vscode-app/c:/Users/Shlomi/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2975:25640
    at m.invoke (vscode-file://vscode-app/c:/Users/Shlomi/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:145)
    at s.deliver (vscode-file://vscode-app/c:/Users/Shlomi/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:2265)
    at o.fire (vscode-file://vscode-app/c:/Users/Shlomi/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:67:1843)
    at N.runner (vscode-file://vscode-app/c:/Users/Shlomi/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:694:51418)
    at N.doRun (vscode-file://vscode-app/c:/Users/Shlomi/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:71:18188)
    at N.onTimeout (vscode-file://vscode-app/c:/Users/Shlomi/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:71:18154)
```

Marking file as Viewed:
```
Marked file as viewed failed: TypeError: Cannot read properties of undefined (reading 'substring')
```
![image](https://user-images.githubusercontent.com/57314279/174114172-74c2c747-de6f-49c6-b3d3-0b557283d261.png)

**Comment by ShlomiAltostra** [comment]
@alexr00 
I did a little more digging
Here is a repo and PR which produce the condition
https://github.com/ShlomiAltostra/big-repo/pull/1

For example, I cannot open (from the extension) the file `vitaecongue`, nor can I mark it as viewed

**Comment by alexr00** [comment]
@ShlomiAltostra thank you for the investigation and the repro repo! I was able to find the issue. It looks after 100 files the GitHub API leave the patch out. Since we already have a separate issue after 300 files and some logic to deal with that, I can just drop our 300 file check to 100.
