### ISSUE TITLE
Error when opening folder

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-pull-request-github#4001]
From @bpasero 

```
ERR GraphQL error: Could not resolve to a PullRequest with the number of 4845.: Error: GraphQL error: Could not resolve to a PullRequest with the number of 4845.
    at new e (/Users/bpasero/.vscode-insiders/extensions/github.vscode-pull-request-github-0.51.2022092809/dist/extension.js:1346:139)
    at /Users/bpasero/.vscode-insiders/extensions/github.vscode-pull-request-github-0.51.2022092809/dist/extension.js:1346:20919
    at /Users/bpasero/.vscode-insiders/extensions/github.vscode-pull-request-github-0.51.2022092809/dist/extension.js:1346:26874
    at Set.forEach (<anonymous>)
    at /Users/bpasero/.vscode-insiders/extensions/github.vscode-pull-request-github-0.51.2022092809/dist/extension.js:1346:26851
    at Map.forEach (<anonymous>)
    at i.broadcastQueries (/Users/bpasero/.vscode-insiders/extensions/github.vscode-pull-request-github-0.51.2022092809/dist/extension.js:1346:26802)
    at /Users/bpasero/.vscode-insiders/extensions/github.vscode-pull-request-github-0.51.2022092809/dist/extension.js:1346:28350
    at Object.next (/Users/bpasero/.vscode-insiders/extensions/github.vscode-pull-request-github-0.51.2022092809/dist/extension.js:1266:12612)
    at me (/Users/bpasero/.vscode-insiders/extensions/github.vscode-pull-request-github-0.51.2022092809/dist/extension.js:1266:10509)
    at re (/Users/bpasero/.vscode-insiders/extensions/github.vscode-pull-request-github-0.51.2022092809/dist/extension.js:1266:10924)
    at K.value (/Users/bpasero/.vscode-insiders/extensions/github.vscode-pull-request-github-0.51.2022092809/dist/extension.js:1266:11456)
    at /Users/bpasero/.vscode-insiders/extensions/github.vscode-pull-request-github-0.51.2022092809/dist/extension.js:1346:14235
    at Set.forEach (<anonymous>)
    at Object.next (/Users/bpasero/.vscode-insiders/extensions/github.vscode-pull-request-github-0.51.2022092809/dist/extension.js:1346:14198)
    at me (/Users/bpasero/.vscode-insiders/extensions/github.vscode-pull-request-github-0.51.2022092809/dist/extension.js:1266:10509)
    at re (/Users/bpasero/.vscode-insiders/extensions/github.vscode-pull-request-github-0.51.2022092809/dist/extension.js:1266:10924)
    at K.value (/Users/bpasero/.vscode-insiders/extensions/github.vscode-pull-request-github-0.51.2022092809/dist/extension.js:1266:11456)
    at me (/Users/bpasero/.vscode-insiders/extensions/github.vscode-pull-request-github-0.51.2022092809/dist/extension.js:1266:10509)
    at re (/Users/bpasero/.vscode-insiders/extensions/github.vscode-pull-request-github-0.51.2022092809/dist/extension.js:1266:10924)
    at K.value (/Users/bpasero/.vscode-insiders/extensions/github.vscode-pull-request-github-0.51.2022092809/dist/extension.js:1266:11456)
    at /Users/bpasero/.vscode-insiders/extensions/github.vscode-pull-request-github-0.51.2022092809/dist/extension.js:1410:10904
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by bpasero** [comment]
I think October is still fine for this.

**Comment by alexr00** [comment]
Can you share your .gitconfig file for the folder that this happens with?

**Comment by bpasero** [comment]
@alexr00 

```ini
[core]
	autocrlf = false
	safecrlf = true
	preloadindex = true
	fscache = true
	editor = code-insiders --wait
[gc]
	auto = 256
[alias]
	co = checkout
	ci = commit
	st = status
	br = branch
	hist = log --pretty=format:\"%Cgreen%h%Creset %Cred%ad%Creset | %s%C(cyan)%d%Creset %Cred<%an>%Creset\" --graph --date=relative --date-order -25
	hist-unlimited = log --pretty=format:\"%Cgreen%h%Creset %ad | %s%C(cyan)%d%Creset %Cred<%an>%Creset\" --graph --date=relative --date-order
	standup = !git log --pretty=format:\"%ad | %Cred%s%Creset\" --since=\"1 day ago\" --date=relative --date-order --all --author=\"\"
[color]
	status = always
[push]
	default = upstream
[pull]
	rebase = merges
[diff]
	tool = code-insiders
[difftool "code-insiders"]
	cmd = code-insiders --wait -d $LOCAL $REMOTE
[merge]
	tool = code-insiders
[mergetool]
	writeToTemp = true
	keepBackup = false
[mergetool "code-insiders"]
	cmd = code-insiders -wait -m $REMOTE $LOCAL $BASE $MERGED
[commit]
	gpgsign = true
[credential]
	helper = osxkeychain
[filter "lfs"]
	clean = git-lfs clean -- %f
	smudge = git-lfs smudge -- %f
	process = git-lfs filter-process
	required = true
[init]
	defaultBranch = main

```

**Comment by alexr00** [comment]
Sorry, I got the file wrong. Can you share the `config` file from the `.git` folder of the folder that you see that error in?

**Comment by bpasero** [comment]
Shared in Slack.

**Comment by alexr00** [comment]
Thanks for sharing. I didn't see anything suspicious there. What do you have `githubIssues.queries` set to?

**Comment by bpasero** [comment]
```
"githubIssues.queries": [
    {
        "label": "My Issues",
        "query": "assignee:bpasero sort:updated-desc is:open"
    }
]
```

**Comment by bpasero** [comment]
I do not see this anymore!
