### ISSUE TITLE
"No tree view with id 'github:compareChanges' registered" after opening PR

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode-pull-request-github#4002]
Testing #3985

After I created the PR, I got the error "No tree view with id 'github:compareChanges' registered."

I think these logs are related:
```
[Debug 1664465581.808s] PullRequestTree> Creating file and commit nodes for PR #2
[Debug 1664465582.89s] PullRequestOverviewPanel> pr.initialize
[Debug 1664465583.06s] PullRequestChangesTreeDataProvider> Error: TreeError [prStatus:github] Tree element not found: [object Object]
```

**Comment by alexr00** [comment]
Next time you see this can you grab the full stack for ` "No tree view with id 'github:compareChanges' registered."` from the dev tools?

**Comment by roblourens** [comment]
Been seeing this often lately

```
No tree view with id 'github:compareChanges' registered.: Error: No tree view with id 'github:compareChanges' registered.
    at f.$setVisible (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:112:13758)
    at l._doInvokeHandler (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:101:13680)
    at l._invokeHandler (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:101:13362)
    at l._receiveRequest (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:101:12132)
    at l._receiveOneMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:101:10834)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:101:8941
    at h.invoke (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:145)
    at v.deliver (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
    at g.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
    at r.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:69:19049)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:117:17104
    at h.invoke (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:145)
    at v.deliver (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
    at g.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
    at r.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:69:19049)
    at MessagePortMain.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:117:15144)
    at MessagePortMain.emit (node:events:526:28)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_process_init:5:364)
```

**Comment by joyceerhl** [comment]
I also see this and there's an additional callstack 

```
notificationsAlerts.ts:40 Error: No tree view with id 'github:compareChanges' registered.
	at f.$getChildren (vscode-file://vscode-app/vscode/bin/linux-x64/2ada565d06c2decc0c14af3f2289ee1ca7fed830-insider/out/vs/workbench/api/node/extensionHostProcess.js:113:12230)
	at l._doInvokeHandler (vscode-file://vscode-app/vscode/bin/linux-x64/2ada565d06c2decc0c14af3f2289ee1ca7fed830-insider/out/vs/workbench/api/node/extensionHostProcess.js:102:13680)
	at l._invokeHandler (vscode-file://vscode-app/vscode/bin/linux-x64/2ada565d06c2decc0c14af3f2289ee1ca7fed830-insider/out/vs/workbench/api/node/extensionHostProcess.js:102:13362)
	at l._receiveRequest (vscode-file://vscode-app/vscode/bin/linux-x64/2ada565d06c2decc0c14af3f2289ee1ca7fed830-insider/out/vs/workbench/api/node/extensionHostProcess.js:102:12132)
	at l._receiveOneMessage (vscode-file://vscode-app/vscode/bin/linux-x64/2ada565d06c2decc0c14af3f2289ee1ca7fed830-insider/out/vs/workbench/api/node/extensionHostProcess.js:102:11033)
	at vscode-file://vscode-app/vscode/bin/linux-x64/2ada565d06c2decc0c14af3f2289ee1ca7fed830-insider/out/vs/workbench/api/node/extensionHostProcess.js:102:8941
	at h.invoke (vscode-file://vscode-app/vscode/bin/linux-x64/2ada565d06c2decc0c14af3f2289ee1ca7fed830-insider/out/vs/workbench/api/node/extensionHostProcess.js:61:145)
	at v.deliver (vscode-file://vscode-app/vscode/bin/linux-x64/2ada565d06c2decc0c14af3f2289ee1ca7fed830-insider/out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
	at g.fire (vscode-file://vscode-app/vscode/bin/linux-x64/2ada565d06c2decc0c14af3f2289ee1ca7fed830-insider/out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
	at r.fire (vscode-file://vscode-app/vscode/bin/linux-x64/2ada565d06c2decc0c14af3f2289ee1ca7fed830-insider/out/vs/workbench/api/node/extensionHostProcess.js:70:16515)
	at vscode-file://vscode-app/vscode/bin/linux-x64/2ada565d06c2decc0c14af3f2289ee1ca7fed830-insider/out/vs/workbench/api/node/extensionHostProcess.js:118:17104
	at h.invoke (vscode-file://vscode-app/vscode/bin/linux-x64/2ada565d06c2decc0c14af3f2289ee1ca7fed830-insider/out/vs/workbench/api/node/extensionHostProcess.js:61:145)
	at v.deliver (vscode-file://vscode-app/vscode/bin/linux-x64/2ada565d06c2decc0c14af3f2289ee1ca7fed830-insider/out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
	at g.fire (vscode-file://vscode-app/vscode/bin/linux-x64/2ada565d06c2decc0c14af3f2289ee1ca7fed830-insider/out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
	at r.fire (vscode-file://vscode-app/vscode/bin/linux-x64/2ada565d06c2decc0c14af3f2289ee1ca7fed830-insider/out/vs/workbench/api/node/extensionHostProcess.js:70:16515)
	at o._receiveMessage (vscode-file://vscode-app/vscode/bin/linux-x64/2ada565d06c2decc0c14af3f2289ee1ca7fed830-insider/out/vs/workbench/api/node/extensionHostProcess.js:70:21327)
	at vscode-file://vscode-app/vscode/bin/linux-x64/2ada565d06c2decc0c14af3f2289ee1ca7fed830-insider/out/vs/workbench/api/node/extensionHostProcess.js:70:18770
	at h.invoke (vscode-file://vscode-app/vscode/bin/linux-x64/2ada565d06c2decc0c14af3f2289ee1ca7fed830-insider/out/vs/workbench/api/node/extensionHostProcess.js:61:145)
	at v.deliver (vscode-file://vscode-app/vscode/bin/linux-x64/2ada565d06c2decc0c14af3f2289ee1ca7fed830-insider/out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
	at g.fire (vscode-file://vscode-app/vscode/bin/linux-x64/2ada565d06c2decc0c14af3f2289ee1ca7fed830-insider/out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
	at g.acceptChunk (vscode-file://vscode-app/vscode/bin/linux-x64/2ada565d06c2decc0c14af3f2289ee1ca7fed830-insider/out/vs/workbench/api/node/extensionHostProcess.js:70:13346)
	at vscode-file://vscode-app/vscode/bin/linux-x64/2ada565d06c2decc0c14af3f2289ee1ca7fed830-insider/out/vs/workbench/api/node/extensionHostProcess.js:70:12476
	at h.invoke (vscode-file://vscode-app/vscode/bin/linux-x64/2ada565d06c2decc0c14af3f2289ee1ca7fed830-insider/out/vs/workbench/api/node/extensionHostProcess.js:61:145)
	at v.deliver (vscode-file://vscode-app/vscode/bin/linux-x64/2ada565d06c2decc0c14af3f2289ee1ca7fed830-insider/out/vs/workbench/api/node/extensionHostProcess.js:61:2266)
	at g.fire (vscode-file://vscode-app/vscode/bin/linux-x64/2ada565d06c2decc0c14af3f2289ee1ca7fed830-insider/out/vs/workbench/api/node/extensionHostProcess.js:61:1844)
	at g._processReadQueue (vscode-file://vscode-app/vscode/bin/linux-x64/2ada565d06c2decc0c14af3f2289ee1ca7fed830-insider/out/vs/workbench/api/node/extensionHostProcess.js:70:32010)
```

**Comment by chrmarti** [comment]
Still seeing this with v0.55.2022113009:

Error: No tree view with id 'github:compareChanges' registered.
    at f.$getChildren (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:11908)
    at u.N (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:11208)
    at u.M (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:10926)
    at u.H (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:10019)
    at u.G (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:9157)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:7788
    at d.invoke (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
    at w.deliver (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2029)
    at g.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1667)
    at h.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:72:14314)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:120:15804
    at d.invoke (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
    at w.deliver (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2029)
    at g.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1667)
    at h.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:72:14314)
    at MessagePortMain.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:120:13960)
    at MessagePortMain.emit (node:events:526:28)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:5:364)

**Comment by onionhammer** [comment]
See this popup every single time

**Comment by redlinejoes** [comment]
Still happening in v0.56.0. 
"No tree view with id 'github:compareChanges' registered." after opening PR.

**Comment by alexr00** [comment]
The fix is in VS Code insiders.

**Comment by neoOpus** [comment]
> The fix is in VS Code insiders.

I have this version and got the error

```
Version: 1.76.0 (user setup)
Commit: 92da9481c0904c6adfe372c12da3b7748d74bdcb
Date: 2023-03-01T10:22:44.506Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.25309
Sandboxed: Yes
```

**Comment by rubensa** [comment]
Same problem here.

`GitHub Pull Requests and Issues v0.60.0`

```
Version: 1.76.1
Commit: 5e805b79fcb6ba4c2d23712967df89a089da575b
Date: 2023-03-08T16:31:31.010Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Linux x64 5.19.0-35-generic
Sandboxed: No
```

```
Error: ENOENT: no such file or directory, lstat '/workspaces/project/.github/workflows/markdown-checker.yml.git'
	at Object.lstatSync (node:fs:1516:3)
	at c (/home/user/.vscode-server/extensions/redhat.vscode-yaml-1.12.1/dist/extension.js:2:284766)
	at /home/user/.vscode-server/extensions/redhat.vscode-yaml-1.12.1/dist/extension.js:2:285125
	at f.invoke (/vscode/vscode-server/bin/linux-x64/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at m.deliver (/vscode/vscode-server/bin/linux-x64/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:63:2066)
	at d.fire (/vscode/vscode-server/bin/linux-x64/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:63:1704)
	at /vscode/vscode-server/bin/linux-x64/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:98:9669
	at f.invoke (/vscode/vscode-server/bin/linux-x64/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at m.deliver (/vscode/vscode-server/bin/linux-x64/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:63:2066)
	at d.fire (/vscode/vscode-server/bin/linux-x64/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:63:1704)
	at m.acceptDocumentsAndEditorsDelta (/vscode/vscode-server/bin/linux-x64/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:98:13808)
	at m.$acceptDocumentsAndEditorsDelta (/vscode/vscode-server/bin/linux-x64/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:98:12249)
	at a.N (/vscode/vscode-server/bin/linux-x64/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:106:11223)
	at a.M (/vscode/vscode-server/bin/linux-x64/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:106:10941)
	at a.H (/vscode/vscode-server/bin/linux-x64/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:106:10034)
	at a.G (/vscode/vscode-server/bin/linux-x64/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:106:9015)
	at /vscode/vscode-server/bin/linux-x64/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:106:7803
	at f.invoke (/vscode/vscode-server/bin/linux-x64/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at m.deliver (/vscode/vscode-server/bin/linux-x64/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:63:2066)
	at d.fire (/vscode/vscode-server/bin/linux-x64/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:63:1704)
	at p.fire (/vscode/vscode-server/bin/linux-x64/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:72:14907)
	at /vscode/vscode-server/bin/linux-x64/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:122:16556
	at f.invoke (/vscode/vscode-server/bin/linux-x64/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at m.deliver (/vscode/vscode-server/bin/linux-x64/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:63:2066)
	at d.fire (/vscode/vscode-server/bin/linux-x64/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:63:1704)
	at p.fire (/vscode/vscode-server/bin/linux-x64/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:72:14907)
	at t.E (/vscode/vscode-server/bin/linux-x64/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:72:18973)
	at /vscode/vscode-server/bin/linux-x64/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:72:16961
	at f.invoke (/vscode/vscode-server/bin/linux-x64/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at m.deliver (/vscode/vscode-server/bin/linux-x64/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:63:2066)
	at d.fire (/vscode/vscode-server/bin/linux-x64/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:63:1704)
	at u.acceptChunk (/vscode/vscode-server/bin/linux-x64/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:72:12638)
	at /vscode/vscode-server/bin/linux-x64/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:72:11925
	at f.invoke (/vscode/vscode-server/bin/linux-x64/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at m.deliver (/vscode/vscode-server/bin/linux-x64/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:63:2066)
	at d.fire (/vscode/vscode-server/bin/linux-x64/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:63:1704)
	at d.u (/vscode/vscode-server/bin/linux-x64/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:72:28911)
	at d.acceptFrame (/vscode/vscode-server/bin/linux-x64/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:72:28717)
	at f.l (/vscode/vscode-server/bin/linux-x64/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:72:27304)
	at /vscode/vscode-server/bin/linux-x64/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:72:24627
	at Socket.t (/vscode/vscode-server/bin/linux-x64/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:72:22461)
	at Socket.emit (node:events:526:28)
	at addChunk (node:internal/streams/readable:315:12)
	at readableAddChunk (node:internal/streams/readable:289:9)
	at Socket.Readable.push (node:internal/streams/readable:228:10)
	at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

```
Error: No tree view with id 'github:compareChanges' registered.
	at m.$getChildren (vscode-file://vscode-app/vscode/vscode-server/bin/linux-x64/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:117:11887)
	at a.N (vscode-file://vscode-app/vscode/vscode-server/bin/linux-x64/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:106:11223)
	at a.M (vscode-file://vscode-app/vscode/vscode-server/bin/linux-x64/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:106:10941)
	at a.H (vscode-file://vscode-app/vscode/vscode-server/bin/linux-x64/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:106:10034)
	at a.G (vscode-file://vscode-app/vscode/vscode-server/bin/linux-x64/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:106:9172)
	at vscode-file://vscode-app/vscode/vscode-server/bin/linux-x64/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:106:7803
	at f.invoke (vscode-file://vscode-app/vscode/vscode-server/bin/linux-x64/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at m.deliver (vscode-file://vscode-app/vscode/vscode-server/bin/linux-x64/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:63:2066)
	at d.fire (vscode-file://vscode-app/vscode/vscode-server/bin/linux-x64/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:63:1704)
	at p.fire (vscode-file://vscode-app/vscode/vscode-server/bin/linux-x64/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:72:14907)
	at vscode-file://vscode-app/vscode/vscode-server/bin/linux-x64/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:122:16556
	at f.invoke (vscode-file://vscode-app/vscode/vscode-server/bin/linux-x64/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at m.deliver (vscode-file://vscode-app/vscode/vscode-server/bin/linux-x64/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:63:2066)
	at d.fire (vscode-file://vscode-app/vscode/vscode-server/bin/linux-x64/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:63:1704)
	at p.fire (vscode-file://vscode-app/vscode/vscode-server/bin/linux-x64/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:72:14907)
	at t.E (vscode-file://vscode-app/vscode/vscode-server/bin/linux-x64/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:72:18973)
	at vscode-file://vscode-app/vscode/vscode-server/bin/linux-x64/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:72:16961
	at f.invoke (vscode-file://vscode-app/vscode/vscode-server/bin/linux-x64/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at m.deliver (vscode-file://vscode-app/vscode/vscode-server/bin/linux-x64/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:63:2066)
	at d.fire (vscode-file://vscode-app/vscode/vscode-server/bin/linux-x64/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:63:1704)
	at u.acceptChunk (vscode-file://vscode-app/vscode/vscode-server/bin/linux-x64/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:72:12638)
	at vscode-file://vscode-app/vscode/vscode-server/bin/linux-x64/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:72:11925
	at f.invoke (vscode-file://vscode-app/vscode/vscode-server/bin/linux-x64/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at m.deliver (vscode-file://vscode-app/vscode/vscode-server/bin/linux-x64/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:63:2066)
	at d.fire (vscode-file://vscode-app/vscode/vscode-server/bin/linux-x64/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:63:1704)
	at d.u (vscode-file://vscode-app/vscode/vscode-server/bin/linux-x64/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:72:28911)
	at d.acceptFrame (vscode-file://vscode-app/vscode/vscode-server/bin/linux-x64/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:72:28717)
	at f.l (vscode-file://vscode-app/vscode/vscode-server/bin/linux-x64/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:72:27304)
	at vscode-file://vscode-app/vscode/vscode-server/bin/linux-x64/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:72:24627
	at Socket.t (vscode-file://vscode-app/vscode/vscode-server/bin/linux-x64/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:72:22461)
	at Socket.emit (node:events:526:28)
	at addChunk (node:internal/streams/readable:315:12)
	at readableAddChunk (node:internal/streams/readable:289:9)
	at Socket.Readable.push (node:internal/streams/readable:228:10)
	at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
c @ notificationsAlerts.ts:40
```
