### ISSUE TITLE
[GHES] GitHubTokenExchangeError: Internal Server Error

### ISSUE THREAD

**Issue by SuibianP** [microsoft/vscode-pull-request-github#4342]
Type: <b>Bug</b>

Logging in to a self-hosted GitHub Enterprise server from the GitHub sidebar results in "Having trouble logging in? Would you like to try a different way?" and finally "Error signing in to GitHub Enterprise".

Logs
```
2022-12-09 14:31:11.399 [info] Reading sessions from keychain...
2022-12-09 14:31:11.406 [info] Getting sessions for read:user,repo,user:email,workflow...
2022-12-09 14:31:11.406 [info] Got 0 sessions for read:user,repo,user:email,workflow...
2022-12-09 14:31:11.437 [info] Getting sessions for read:user,repo,user:email...
2022-12-09 14:31:11.437 [info] Got 0 sessions for read:user,repo,user:email...
2022-12-09 14:31:11.454 [info] Getting sessions for read:user,repo,user:email,workflow...
2022-12-09 14:31:11.454 [info] Got 0 sessions for read:user,repo,user:email,workflow...
2022-12-09 14:31:17.161 [info] Logging in for the following scopes: read:user repo user:email workflow
2022-12-09 14:31:17.170 [info] Trying without local server... (read:user repo user:email workflow)
2022-12-09 14:31:27.736 [info] Exchanging code for token...
2022-12-09 14:31:28.467 [error] GitHubTokenExchangeError: Internal Server Error
	at t.GitHubServer.u (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/github-authentication/dist/extension.js:2:1309015)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/github-authentication/dist/extension.js:2:1304423
2022-12-09 14:31:36.464 [info] Trying with local server... (read:user repo user:email workflow)
2022-12-09 14:31:38.721 [info] Exchanging code for token...
2022-12-09 14:31:39.081 [error] GitHubTokenExchangeError: Internal Server Error
	at t.GitHubServer.u (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/github-authentication/dist/extension.js:2:1309015)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/github-authentication/dist/extension.js:2:1305597
2022-12-09 14:31:46.451 [info] Trying device code flow... (read:user repo user:email workflow)
2022-12-09 14:31:47.176 [error] Error: Failed to get one-time code: Cookies must be enabled to use GitHub.
	at t.GitHubServer.p (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/github-authentication/dist/extension.js:2:1305870)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async t.GitHubServer.login (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/github-authentication/dist/extension.js:2:1303463)
	at async t.GitHubAuthenticationProvider.createSession (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/github-authentication/dist/extension.js:2:1299643)
```

Extension version: 0.57.2022120809
VS Code version: Code 1.74.0 (Universal) (5235c6bb189b60b01b1f49062f4ffa42384f8c91, 2022-12-05T16:43:37.5

**Comment by akhileshraju** [comment]
I see a similar error

![image](https://user-images.githubusercontent.com/17533956/208213907-64a8e868-72b5-4095-97b9-6174ff9fcea3.png)

Extension version - `0.56.0`
VS Code version - `1.74.1`
GHES version - `3.4.9`
