### ISSUE TITLE
Cannot read property of undefined `findIndex`

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode-pull-request-github#4538]
Seeing this in my insiders log when clicking through some comments

```
  ERR Cannot read properties of undefined (reading 'findIndex'): TypeError: Cannot read properties of undefined (reading 'findIndex')
    at /Users/lramos15/.vscode-insiders/extensions/github.vscode-pull-request-github-0.59.2023021609/dist/extension.js:1528:69716
    at Array.forEach (<anonymous>)
    at /Users/lramos15/.vscode-insiders/extensions/github.vscode-pull-request-github-0.59.2023021609/dist/extension.js:1528:69527
    at f.invoke (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
    at g.deliver (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2066)
    at h.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1704)
    at bn.diffThreads (/Users/lramos15/.vscode-insiders/extensions/github.vscode-pull-request-github-0.59.2023021609/dist/extension.js:1528:32141)
    at bn.getReviewThreads (/Users/lramos15/.vscode-insiders/extensions/github.vscode-pull-request-github-0.59.2023021609/dist/extension.js:1528:32545)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at bn.initializeReviewThreadCache (/Users/lramos15/.vscode-insiders/extensions/github.vscode-pull-request-github-0.59.2023021609/dist/extension.js:1528:22373)
    at async Promise.all (index 1)
    at $i.initializePullRequestData (/Users/lramos15/.vscode-insiders/extensions/github.vscode-pull-request-github-0.59.2023021609/dist/extension.js:1545:21013)
```

**Comment by alexr00** [comment]
Maybe coming from here?
 https://github.com/microsoft/vscode-pull-request-github/blob/77ca4453f544687360ab4c5a5df5d76d9d307a5c/src/view/reviewCommentController.ts#L244-L245

**Comment by ulugbekna** [comment]
I think I saw this when I clicked on `resolve conversation` for an already resolved conversation

**Comment by alexr00** [comment]
It's this one:

https://github.com/microsoft/vscode-pull-request-github/blob/a42163688c6f82bf5fb3aa5781a25cbe62dbbb30/src/view/reviewCommentController.ts#L297-L298
