### ISSUE TITLE
Extension failing to load PRs when using WSL

### ISSUE THREAD

**Issue by eastwood** [microsoft/vscode-pull-request-github#4622]
Type: <b>Bug</b>

1. Create a new profile (BugHunt)
2. Install Github Pull Request Extension
3. Install WSL extension
4. Open up wsl terminal and `git clone git@github.com:microsoft/vscode-pull-request-github.git`.
5. Run `code vscode-pull-request-github`
6. Open up github pull requests window

Notice that the extension is reporting uncaught errors:

> Uncaught Errors (1)
Cannot read properties of undefined (reading 'split')

Output -> Remote Extension Host

```
2023-03-14 13:43:03.432 [error] TypeError: Cannot read properties of undefined (reading 'split')
	at b (/home/eastwd/.vscode-server/extensions/github.vscode-pull-request-github-0.60.0/dist/extension.js:1403:1739)
	at y.compute (/home/eastwd/.vscode-server/extensions/github.vscode-pull-request-github-0.60.0/dist/extension.js:1395:37853)
	at /home/eastwd/.vscode-server/extensions/github.vscode-pull-request-github-0.60.0/dist/extension.js:1407:1150
	at /home/eastwd/.vscode-server/extensions/github.vscode-pull-request-github-0.60.0/dist/extension.js:1407:1089
	at Array.reduce (<anonymous>)
	at /home/eastwd/.vscode-server/extensions/github.vscode-pull-request-github-0.60.0/dist/extension.js:1407:1065
	at ce (/home/eastwd/.vscode-server/extensions/github.vscode-pull-request-github-0.60.0/dist/extension.js:1407:1593)
	at Xe.parseSshProtocol (/home/eastwd/.vscode-server/extensions/github.vscode-pull-request-github-0.60.0/dist/extension.js:1407:2836)
	at new Xe (/home/eastwd/.vscode-server/extensions/github.vscode-pull-request-github-0.60.0/dist/extension.js:1407:2162)
	at Tt (/home/eastwd/.vscode-server/extensions/github.vscode-pull-request-github-0.60.0/dist/extension.js:1407:12103)
	at /home/eastwd/.vscode-server/extensions/github.vscode-pull-request-github-0.60.0/dist/extension.js:1407:12348
	at Array.forEach (<anonymous>)
	at xt (/home/eastwd/.vscode-server/extensions/github.vscode-pull-request-github-0.60.0/dist/extension.js:1407:12328)
	at new $i (/home/eastwd/.vscode-server/extensions/github.vscode-pull-request-github-0.60.0/dist/extension.js:1546:9426)
	at He (/home/eastwd/.vscode-server/extensions/github.vscode-pull-request-github-0.60.0/dist/extension.js:1596:3771)
	at /home/eastwd/.vscode-server/extensions/github.vscode-pull-request-github-0.60.0/dist/extension.js:1596:3842
	at f.invoke (/home/eastwd/.vscode-server/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at m.deliver (/home/eastwd/.vscode-server/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:63:2066)
	at d.fire (/home/eastwd/.vscode-server/bin/5e805b79fcb6ba4c2d23712967df89a089da575b/out/vs/workbench/api/node/extensionHostProcess.js:63:1704)
	at /home/eastwd/.vscode-server/extensions/github.vscode-pull-request-github-0.60.0/dist/extension.js:1405:460854
	at Array.forEach (<anonymous>)
	at te.registerGitProvider (/home/eastwd/.vscode-server/extensions/github.vscode-pull-request-github-0.60.0/dist/extension.js:1405:460816)
	at z1 (/home/eastwd/.vscode-server/extensions/github.vscode-pull-request-github-0.60.0/dist/extension.js:1567:31598)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async kc (/home/eastwd/.vscode-server/extensions/github.vscode-pull-request-github-0.60.0/dist/extension.js:1596:5557)
	at async i0 (/home/eastwd/.vscode-server/extensions/github.vscode-pull-request-github-0.60.0/dist/extension.js:1596:6662)
```

Extension version: 0.60.0
VS Code version: Code 1.76.1 (5e805b79fcb6ba4c2d23712967df89a089da575b, 2023-03-08T16:32:00.131Z)
OS version: Windows_NT x64 10.0.22624
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800X3D 8-Core Processor            (16 x 3400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.92GB (13.99GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 7 5800X3D 8-Core Processor (16 x 3400)|
|Memory (System)|15.58GB (14.66GB free)|
|VM|0%|
</details>

**Comment by eastwood** [comment]
Worth noting, when I run this in "Reopen Folder in Windows" - everything works fine :)

**Comment by eastwood** [comment]
I also deleted the ~/.vscode-server directory before running to ensure the WSL instance was fresh :)

**Comment by alexr00** [comment]
I'm not able to reproduce this error.

> Open up github pull requests window

What are you opening here?

**Comment by eastwood** [comment]
Just the GitHub view in code. Where it usually lists the PRs and such it's stuck on "loading". Will share SS shortly.

**Comment by eastwood** [comment]
![image](https://user-images.githubusercontent.com/2359795/225630226-84c57426-2eb9-41f6-9a7f-31c0db13bc46.png)
This is what I mean @alexr00

**Comment by eastwood** [comment]
I compiled the extension and ran this in debug mode.
Turns out it was the ssh config resolver:

```

export function resolverFromConfig(text: string): ConfigResolver {
	const config = parseConfig(text);
	return h => config.compute(h.Host);
}
```
That was throwing.

This was caused by my .ssh/config file being malformed (no idea why).

Closing this story now, but may be worth having some error handling around this for future users.
I'm happy to push a PR if this is ok?

**Comment by alexr00** [comment]
Thank you for the in-depth investigation! Yes, I would accept a PR to add error handling.
