### ISSUE TITLE
Cannot read properties of undefined (reading 'registerActionRunner')

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-pull-request-github#4704]
1. Open any GH repo in vscode.dev, e.g. https://insiders.vscode.dev/github/microsoft/vscode
2. :bug: see the following in console:

```
TypeError: Cannot read properties of undefined (reading 'registerActionRunner')
	at P0.register (extension.js:1527:33763)
	at P0.onExtensionsChanged (extension.js:1527:34231)
```

**Comment by alexr00** [comment]
I can't reproduce this, but it's coming from the Git Lens integration. @eamodio FYI in case you know something about this.

I'll add some extra checks so that it can't happen again.

**Comment by eamodio** [comment]
@alexr00 I think I understand why that could happen -- if you are running the pre-release version of GitLens and it expires (e.g. its older than 14 days) we don't return an API (nor does the extension work anymore).
