### ISSUE TITLE
Not able to pull up Overview page from the "pull request" view:

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode-pull-request-github#4768]
Testing #4764

I am not able to pull up Overview page from the "pull request" view:
![image](https://user-images.githubusercontent.com/3840081/234375437-9c7d2d2d-f3fd-4194-87f1-33871ec60922.png)

Clicking on the pull request title does nothing.

I see this error:
![image](https://user-images.githubusercontent.com/3840081/234375956-8b2099c8-bad3-412d-b05d-87194af00579.png)

```
notificationsAlerts.ts:40 TypeError: Cannot read properties of undefined (reading 'title')
    at og.getTreeItem (c:\Users\kanadig\.vscode-insiders\extensions\github.vscode-pull-request-github-0.63.2023042509\dist\extension.js:1710:48743)
    at c:\Users\kanadig\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:98:65297
    at Array.map (<anonymous>)
    at y.R (c:\Users\kanadig\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:98:65262)
    at y.getChildren (c:\Users\kanadig\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:98:61563)
c @ notificationsAlerts.ts:40

```

**Comment by alexr00** [comment]
@karthiknadig I've fixed the error and the fix will be available in the next pre-release build, though I wouldn't expect that to cause the PR description to not show. Can you install the latest pre-release, repro the issue, then share the output of GitHub Pull Request?

**Comment by alexr00** [comment]
Just ran into this issue myself. It's an issue with using SSH remotes.
