### ISSUE TITLE
PR viewlet stays in loading state

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-pull-request-github#4900]
Type: <b>Bug</b>

TypeError: Cannot read properties of undefined (reading 'number')
    at Ut.createOrUpdatePullRequestModel (/Users/chrmarti/.vscode-insiders/extensions/github.vscode-pull-request-github-0.67.2023060813/dist/extension.js:1705:4679)
    at Ut.getPullRequestForBranch (/Users/chrmarti/.vscode-insiders/extensions/github.vscode-pull-request-github-0.67.2023060813/dist/extension.js:1703:39251)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Zi.getMatchingPullRequestMetadataFromGitHub (/Users/chrmarti/.vscode-insiders/extensions/github.vscode-pull-request-github-0.67.2023060813/dist/extension.js:1781:7211)
    at Vi.checkGitHubForPrBranch (/Users/chrmarti/.vscode-insiders/extensions/github.vscode-pull-request-github-0.67.2023060813/dist/extension.js:1784:6892)
    at Vi.validateState (/Users/chrmarti/.vscode-insiders/extensions/github.vscode-pull-request-github-0.67.2023060813/dist/extension.js:1784:8889)
    at Vi.validateStatueAndSetContext (/Users/chrmarti/.vscode-insiders/extensions/github.vscode-pull-request-github-0.67.2023060813/dist/extension.js:1784:5755)

Extension version: 0.67.2023060813
VS Code version: Code - Insiders 1.80.0-insider (db6bcdf309cc1565c502a54b73c33a63bdabfbd8, 2023-06-09T05:50:00.303Z)
OS version: Darwin arm64 22.5.0
Modes:
Remote OS version: Linux arm64 5.15.49-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|14, 13, 8|
|Memory (System)|64.00GB (0.34GB free)|
|Process Argv|--log debug|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: VS Code with Proxy|
|OS|Linux arm64 5.15.49-linuxkit|
|CPUs|unknown (5 x 0)|
|Memory (System)|7.67GB (5.37GB free)|
|VM|0%|
</details>

**Comment by chrmarti** [comment]
Tracked in https://github.com/microsoft/vscode-pull-request-github/issues/4893
