### ISSUE TITLE
ReferenceError: Buffer is not defined

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-pull-request-github#4917]
1. Open pull request in insiders.vscode.dev
2. :bug: see this error message

<img width="346" alt="image" src="https://github.com/microsoft/vscode-pull-request-github/assets/30305945/798603f9-e6d1-434d-8fa2-e1c975ecebbb">

ReferenceError: Buffer is not defined
	at Object.t [as avatarCircleAsImageDataUri] (extension.js:1667:65942)
	at async Nb.getTreeItem (extension.js:1800:12645)
	at async eval (/github/vs/workbench/api/worker/extensionHostWorker.js:80:62477)
	at async Promise.all (index 0)
	at async E.R (/github/vs/workbench/api/worker/extensionHostWorker.js:80:62420)
	at async E.getChildren (/github/vs/workbench/api/worker/extensionHostWorker.js:80:58845)
c @ workbench.web.main.js:760

**Comment by alexr00** [comment]
Duplicate of https://github.com/microsoft/vscode-pull-request-github/issues/4911

Sorry for not having the fix out yesterday. The pipeline changed and I didn't realize I needed to check a box to make it release 😳
