### ISSUE TITLE
Clicking on create draft results in error with blank screen

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode-pull-request-github#5137]
![image](https://github.com/microsoft/vscode-pull-request-github/assets/3840081/9ba8a87d-1675-416d-9f4b-b9fe888d6ab8)

```
webview-create-pr-view-new.js:585 Error: Minified React error #301; visit https://reactjs.org/docs/error-decoder.html?invariant=301 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at oh (webview-create-pr-view-new.js:585:51913)
    at di (webview-create-pr-view-new.js:585:61085)
    at Rj (webview-create-pr-view-new.js:587:9307)
    at Qj (webview-create-pr-view-new.js:587:928)
    at Kj (webview-create-pr-view-new.js:587:831)
    at yj (webview-create-pr-view-new.js:585:88612)
    at webview-create-pr-view-new.js:585:38465
    at _.unstable_runWithPriority (webview-create-pr-view-new.js:601:4112)
    at cg (webview-create-pr-view-new.js:585:38131)
    at fg (webview-create-pr-view-new.js:585:38411)
Ci @ webview-create-pr-view-new.js:585
webview-create-pr-view-new.js:585 Uncaught (in promise) Error: Minified React error #301; visit https://reactjs.org/docs/error-decoder.html?invariant=301 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at oh (webview-create-pr-view-new.js:585:51913)
    at di (webview-create-pr-view-new.js:585:61085)
    at Rj (webview-create-pr-view-new.js:587:9307)
    at Qj (webview-create-pr-view-new.js:587:928)
    at Kj (webview-create-pr-view-new.js:587:831)
    at yj (webview-create-pr-view-new.js:585:88612)
    at webview-create-pr-view-new.js:585:38465
    at _.unstable_runWithPriority (webview-create-pr-view-new.js:601:4112)
    at cg (webview-create-pr-view-new.js:585:38131)
    at fg (webview-create-pr-view-new.js:585:38411)
```

Logs:
```
2023-07-27 11:02:56.715 [info] Looking for git repository
2023-07-27 11:02:56.715 [info] Found 0 repositories during activation
2023-07-27 11:02:56.715 [info] Git repository found, initializing review manager and pr tree view.
2023-07-27 11:02:56.748 [info] Registering git provider
2023-07-27 11:02:57.850 [info] Review> Validate state in progress
2023-07-27 11:02:57.850 [info] Review> Validating state...
2023-07-27 11:02:57.850 [info] Cannot updates repositories as git is uninitialized
2023-07-27 11:02:57.851 [info] Repo state for file:///c%3A/GIT/s%20p/vscode-python changed.
2023-07-27 11:02:57.851 [info] Repo file:///c%3A/GIT/s%20p/vscode-python has already been setup.
2023-07-27 11:03:21.925 [info] Looking for git repository
2023-07-27 11:03:21.926 [info] Found 0 repositories during activation
2023-07-27 11:03:21.926 [info] Git repository found, initializing review manager and pr tree view.
2023-07-27 11:03:21.938 [info] Registering git provider
2023-07-27 11:03:24.597 [info] Git initialization state changed: state=initialized
2023-07-27 11:03:24.597 [info] Review> Validate state in progress
2023-07-27 11:03:24.597 [info] Review> Validating state...
2023-07-27 11:03:24.613 [info] Found GitHub remote for folder c:\GIT\s p\vscode-python
2023-07-27 11:03:25.330 [info] Repo state for file:///c%3A/GIT/s%20p/vscode-python changed.
2023-07-27 11:03:25.330 [info] Repo file:///c%3A/GIT/s%20p/vscode-python has already been setup.
2023-07-27 11:03:26.169 [info] Review> No matching pull request metadata found locally for current branch main
2023-07-27 11:03:26.169 [info] Review> no matching pull request metadata found for current branch main
2023-07-27 11:03:26.915 [info] Review> No matching pull request metadata found on GitHub for current branch main
2023-07-27 11:04:54.916 [info] Review> Validate state in progress
2023-07-27 11:04:54.916 [info] Review> Validating state...
2023-07-27 11:04:54.917 [info] PullRequestGitHelper> associate update-packages with base branch karthiknadig/vscode-python#main
2023-07-27 11:04:54.974 [info] Found GitHub remote for folder c:\GIT\s p\vscode-python
2023-07-27 11:04:55.765 [info] Review> No matching pull request metadata found locally for current branch update-packages
2023-07-27 11:04:55.765 [info] Review> no matching pull request metadata found for current branch update-packages
2023-07-27 11:04:55.765 [info] Review> No matching pull request metadata found on GitHub for current branch update-packages
2023-07-27 11:07:23.904 [info] CreatePullRequestViewProvider> Initializing "create" view: {"defaultBaseRemote":{"owner":"karthiknadig","repositoryName":"vscode-python"},"defaultBaseBranch":"main","defaultCompareRemote":{"owner":"karthiknadig","repositoryName":"vscode-python"},"defaultCompareBranch":"update-packages","defaultTitle":"Convert JS-style typings to native TS in `@vscode/python-extension` (#21692)","defaultDescription":"Closes https://github.com/microsoft/vscode-python/issues/21690","defaultMergeMethod":"merge","remoteCount":2,"allowAutoMerge":false,"mergeMethodsAvailability":{"merge":true,"squash":true,"rebase":true},"autoMergeDefault":false,"createError":"","labels":[],"isDraftDefault":false,"isDarkTheme":true,"creating":false}
2023-07-27 11:08:41.773 [info] Review> Validate state in progress
2023-07-27 11:08:41.773 [info] Review> Validating state...
2023-07-27 11:08:41.849 [info] Found GitHub remote for folder c:\GIT\s p\vscode-python
2023-07-27 11:08:42.686 [info] Review> No matching pull request metadata found locally for current branch update-packages
2023-07-27 11:08:42.687 [info] Review> no matching pull request metadata found for current branch update-packages
2023-07-27 11:08:42.688 [info] Review> No matching pull request metadata found on GitHub for current branch update-packages
```

**Comment by karthiknadig** [comment]
Reloading with trace on results in extension getting stuck:
![image](https://github.com/microsoft/vscode-pull-request-github/assets/3840081/239d9b27-973e-487f-9fd1-8d7058ba899d)

```
2023-07-27 11:02:56.715 [info] Looking for git repository
2023-07-27 11:02:56.715 [info] Found 0 repositories during activation
2023-07-27 11:02:56.715 [info] Git repository found, initializing review manager and pr tree view.
2023-07-27 11:02:56.748 [info] Registering git provider
2023-07-27 11:02:57.850 [info] Review> Validate state in progress
2023-07-27 11:02:57.850 [info] Review> Validating state...
2023-07-27 11:02:57.850 [info] Cannot updates repositories as git is uninitialized
2023-07-27 11:02:57.851 [info] Repo state for file:///c%3A/GIT/s%20p/vscode-python changed.
2023-07-27 11:02:57.851 [info] Repo file:///c%3A/GIT/s%20p/vscode-python has already been setup.
2023-07-27 11:03:21.925 [info] Looking for git repository
2023-07-27 11:03:21.926 [info] Found 0 repositories during activation
2023-07-27 11:03:21.926 [info] Git repository found, initializing review manager and pr tree view.
2023-07-27 11:03:21.938 [info] Registering git provider
2023-07-27 11:03:24.597 [info] Git initialization state changed: state=initialized
2023-07-27 11:03:24.597 [info] Review> Validate state in progress
2023-07-27 11:03:24.597 [info] Review> Validating state...
2023-07-27 11:03:24.613 [info] Found GitHub remote for folder c:\GIT\s p\vscode-python
2023-07-27 11:03:25.330 [info] Repo state for file:///c%3A/GIT/s%20p/vscode-python changed.
2023-07-27 11:03:25.330 [info] Repo file:///c%3A/GIT/s%20p/vscode-python has already been setup.
2023-07-27 11:03:26.169 [info] Review> No matching pull request metadata found locally for current branch main
2023-07-27 11:03:26.169 [info] Review> no matching pull request metadata found for current branch main
2023-07-27 11:03:26.915 [info] Review> No matching pull request metadata found on GitHub for current branch main
2023-07-27 11:04:54.916 [info] Review> Validate state in progress
2023-07-27 11:04:54.916 [info] Review> Validating state...
2023-07-27 11:04:54.917 [info] PullRequestGitHelper> associate update-packages with base branch karthiknadig/vscode-python#main
2023-07-27 11:04:54.974 [info] Found GitHub remote for folder c:\GIT\s p\vscode-python
2023-07-27 11:04:55.765 [info] Review> No matching pull request metadata found locally for current branch update-packages
2023-07-27 11:04:55.765 [info] Review> no matching pull request metadata found for current branch update-packages
2023-07-27 11:04:55.765 [info] Review> No matching pull request metadata found on GitHub for current branch update-packages
2023-07-27 11:07:23.904 [info] CreatePullRequestViewProvider> Initializing "create" view: {"defaultBaseRemote":{"owner":"karthiknadig","repositoryName":"vscode-python"},"defaultBaseBranch":"main","defaultCompareRemote":{"owner":"karthiknadig","repositoryName":"vscode-python"},"defaultCompareBranch":"update-packages","defaultTitle":"Convert JS-style typings to native TS in `@vscode/python-extension` (#21692)","defaultDescription":"Closes https://github.com/microsoft/vscode-python/issues/21690","defaultMergeMethod":"merge","remoteCount":2,"allowAutoMerge":false,"mergeMethodsAvailability":{"merge":true,"squash":true,"rebase":true},"autoMergeDefault":false,"createError":"","labels":[],"isDraftDefault":false,"isDarkTheme":true,"creating":false}
2023-07-27 11:08:41.773 [info] Review> Validate state in progress
2023-07-27 11:08:41.773 [info] Review> Validating state...
2023-07-27 11:08:41.849 [info] Found GitHub remote for folder c:\GIT\s p\vscode-python
2023-07-27 11:08:42.686 [info] Review> No matching pull request metadata found locally for current branch update-packages
2023-07-27 11:08:42.687 [info] Review> no matching pull request metadata found for current branch update-packages
2023-07-27 11:08:42.688 [info] Review> No matching pull request metadata found on GitHub for current branch update-packages
2023-07-27 11:26:04.411 [debug] Activation> Creating API implementation.
2023-07-27 11:26:04.411 [debug] Activation> Initializing state.
2023-07-27 11:26:04.411 [debug] Activation> Creating credential store.
2023-07-27 11:26:04.411 [debug] Authentication> Initializing GitHub authentication provider.
2023-07-27 11:26:05.054 [debug] RateLimit> Extension rate limit remaining: 140, /user
2023-07-27 11:26:05.363 [debug] Activation> Registering built in git provider.
2023-07-27 11:26:05.363 [debug] Activation> Registering live share git provider.
2023-07-27 11:26:05.363 [debug] Activation> Creating tree view.
2023-07-27 11:26:05.363 [info] Looking for git repository
2023-07-27 11:26:05.364 [info] Found 0 repositories during activation
2023-07-27 11:26:05.364 [info] Git repository found, initializing review manager and pr tree view.
2023-07-27 11:26:05.371 [info] Registering git provider
2023-07-27 11:26:05.564 [debug] GitPostCommitCommands> Trying to register post commit commands.
2023-07-27 11:26:08.147 [info] Git initialization state changed: state=initialized
2023-07-27 11:26:08.147 [info] Review> Validate state in progress
2023-07-27 11:26:08.147 [info] Review> Validating state...
2023-07-27 11:26:08.147 [debug] FolderRepositoryManager> Not all remotes found. The following remotes are missing: 
2023-07-27 11:26:08.148 [debug] FolderRepositoryManager> Displaying configured remotes: origin, upstream
2023-07-27 11:26:08.159 [info] Found GitHub remote for folder c:\GIT\s p\vscode-python
2023-07-27 11:26:08.162 [debug] GitHubRepository> Fetch metadata - enter
2023-07-27 11:26:08.163 [debug] RateLimit> Extension rate limit remaining: 139, /repos/{owner}/{repo}
2023-07-27 11:26:08.169 [debug] GitHubRepository> Fetch metadata - enter
2023-07-27 11:26:08.171 [debug] RateLimit> Extension rate limit remaining: 138, /repos/{owner}/{repo}

```

**Comment by karthiknadig** [comment]
Restarting VS Code results in blank view but no more `loading ...`:
![image](https://github.com/microsoft/vscode-pull-request-github/assets/3840081/e03cd4cf-de34-4e39-a8b4-a9da1b2a1a07)

```
2023-07-27 11:52:54.989 [info] Looking for git repository
2023-07-27 11:52:54.989 [info] Found 0 repositories during activation
2023-07-27 11:52:54.989 [info] Git repository found, initializing review manager and pr tree view.
2023-07-27 11:52:54.995 [info] Registering git provider
2023-07-27 11:52:59.532 [info] Git initialization state changed: state=initialized
2023-07-27 11:52:59.533 [info] Review> Validate state in progress
2023-07-27 11:52:59.533 [info] Review> Validating state...
2023-07-27 11:52:59.575 [info] Found GitHub remote for folder c:\GIT\s p\vscode-python
2023-07-27 11:53:00.977 [info] Repo state for file:///c%3A/GIT/s%20p/vscode-python changed.
2023-07-27 11:53:00.977 [info] Repo file:///c%3A/GIT/s%20p/vscode-python has already been setup.
2023-07-27 11:53:00.979 [info] Review> No matching pull request metadata found locally for current branch update-packages
2023-07-27 11:53:00.979 [info] Review> no matching pull request metadata found for current branch update-packages
2023-07-27 11:53:00.980 [info] Review> No matching pull request metadata found on GitHub for current branch update-packages
2023-07-27 11:54:16.432 [info] CreatePullRequestViewProvider> Initializing "create" view: {"defaultBaseRemote":{"owner":"karthiknadig","repositoryName":"vscode-python"},"defaultBaseBranch":"main","defaultCompareRemote":{"owner":"karthiknadig","repositoryName":"vscode-python"},"defaultCompareBranch":"update-packages","defaultTitle":"Update packages for Jedi and core python","defaultDescription":"","defaultMergeMethod":"merge","remoteCount":2,"allowAutoMerge":false,"mergeMethodsAvailability":{"merge":true,"squash":true,"rebase":true},"autoMergeDefault":false,"createError":"","labels":[],"isDraftDefault":false,"isDarkTheme":true,"creating":false}
```

**Comment by karthiknadig** [comment]
With `Trace` on , it does not seem to finish loading.

**Comment by alexr00** [comment]
What you see with `Trace` is this https://github.com/microsoft/vscode/issues/188783

**Comment by alexr00** [comment]
I'm not able to reproduce this. It looks like you're trying to create a PR from a fork into the parent. Is that correct?

**Comment by karthiknadig** [comment]
> It looks like you're trying to create a PR from a fork into the parent. Is that correct?

That is correct.
