### ISSUE TITLE
Exception in dev console: `Illegal Argument: line must be non-negative`

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/vscode-pull-request-github#5190]
# Exception: 

```
mainThreadExtensionService.ts:81 [GitHub.vscode-pull-request-github]Illegal argument: line must be non-negative
$onExtensionRuntimeError @ mainThreadExtensionService.ts:81

mainThreadExtensionService.ts:82 Error: Illegal argument: line must be non-negative
    at g (vscode-file://vscode-app/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:10:1101)
    at new n (vscode-file://vscode-app/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:98:4307)
    at new o (vscode-file://vscode-app/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:98:5823)
    at Fa (vscode-file://vscode-app/Users/ulugbekna/.vscode-insiders/extensions/github.vscode-pull-request-github-0.71.2023082209/dist/extension.js:1672:14857)
    at ar.createWorkspaceCommentThread (vscode-file://vscode-app/Users/ulugbekna/.vscode-insiders/extensions/github.vscode-pull-request-github-0.71.2023082209/dist/extension.js:1674:18151)
    at vscode-file://vscode-app/Users/ulugbekna/.vscode-insiders/extensions/github.vscode-pull-request-github-0.71.2023082209/dist/extension.js:1674:21145
```

As a screenshot: 

![Image](https://github.com/microsoft/vscode-pull-request-github/assets/16353531/ed1e0306-0444-4844-9a2a-518ed76885dc)

# Repro

I don't have one, sorry :( 

# Versions

GHPR v0.71.2023082209

```
Version: 1.82.0-insider
Commit: f125afbc800ec611f5a9ab1333c769832ce424b3
Date: 2023-08-21T05:34:23.256Z
Electron: 25.5.0
ElectronBuildId: 23084831
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.6.0
```

**Comment by alexr00** [comment]
This is the line with the error:

https://github.com/microsoft/vscode-pull-request-github/blob/b47b2eac82803047ddeddad9c403082fb77a8c40/src/github/utils.ts#L88-L89

**Comment by alexr00** [comment]
Looks like we haven't gotten the issue again.

**Comment by andreamah** [comment]
@ulugbekna can you verify that this is fixed?
