### ISSUE TITLE
No GPR panel in SCM view

### ISSUE THREAD

**Issue by AamuLumi** [Microsoft/vscode-pull-request-github#525]
- Extension version: 0.1.6
- VS Code version: Code - OSS 1.27.1 (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T17:56:24+03:00)
- OS version: Linux x64 4.18.5-90.current

Steps to Reproduce:

1. Install Github Pull Requests
2. Reload VSCode
3. Go to SCM View

I've checked all issues related, but nothing repairs my problem.
I work on a private repository with SSH. I've also tested with [this repository](https://github.com/RobinBuschmann/sequelize-typescript), but same problem.

Here's the origin's URLs of the repository (I remove the owner and the repository's name) :
```
git remote -v                                        
origin	git@github.com:<owner>/<repo> (fetch)
origin	git@github.com:<owner>/<repo> (push)
```
and for the second test :
```
git remote -v
origin	git@github.com:RobinBuschmann/sequelize-typescript.git (fetch)
origin	git@github.com:RobinBuschmann/sequelize-typescript.git (push)

```

Github Pull Requests output :
```
Looking for git repository
> git symbolic-ref --short HEAD
> git rev-parse develop
> git rev-parse --symbolic-full-name develop@{u}
> git rev-list --left-right develop...refs/remotes/origin/develop
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
Git repository found, initializing review manager and pr tree view.
```

Thanks a lot!

**Comment by RMacfarlane** [comment]
Thanks for all the info! As an experiment, could you try running `git remote add <some name> <some url, could just be junk>` in one of those repos? Changing the remotes should trigger a refresh, so if that works then the problem is a timing issue

**Comment by AamuLumi** [comment]
I tested : 
```
git remote add test git@github.com:RobinBuschmann/sequelize-typescript.git~
git remote add test2 blabla
```

In both cases, it just showed these lines in plugin output : 
```
> git symbolic-ref --short HEAD
> git rev-parse master
> git rev-parse --symbolic-full-name master@{u}
> git rev-list --left-right master...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
```
and always no GPR view.

I tested too with an https URL but got the same result.

Any other idea? :/

**Comment by NicolasHug** [comment]
Same problem here,

Extension version: 0.1.6
VS Code version: 1.27.2
OS version: Linux x64

and same result when adding a remote.

I tried manually adding a Github Token, but the problem persists.

**Comment by rebornix** [comment]
Can anyone try open developer tools and see if there is any error message there? Probably we fail to register the tree view but there is no error message being sent back to extensions.

**Comment by NicolasHug** [comment]
Here is my log, not sure if that's of any help, LMK if you need something else

<details>

```
20:39:42.318 /usr/lib/code/out/vs/workbench/workbench.main.js:1411  INFO no standard startup: panel is active
20:39:42.430 /usr/lib/code/out/vs/workbench/workbench.main.js:3254 Extension 'GitHub.vscode-pull-request-github cannot use PROPOSED API (must started out of dev or enabled via --enable-proposed-api)
w._updateEnableProposedApi @ /usr/lib/code/out/vs/workbench/workbench.main.js:3254
20:39:42.522 /usr/lib/code/out/vs/workbench/workbench.main.js:4236 Overwriting grammar scope name to file mapping for scope source.cython.
Old grammar file: file:///home/nico/.vscode-oss/extensions/guyskk.language-cython-0.0.4/syntaxes/Cython.tmLanguage.
New grammar file: file:///home/nico/.vscode-oss/extensions/tcwalther.cython-0.1.0/syntaxes/cython.tmLanguage
e.register @ /usr/lib/code/out/vs/workbench/workbench.main.js:4236
20:39:45.143 /usr/lib/code/out/vs/workbench/workbench.main.js:276 [Extension Host] vscode-icons is active!
20:39:45.279 /usr/lib/code/out/vs/workbench/workbench.main.js:119 [UriError]: Scheme is missing: {scheme: "", authority: "", path: "blahblahablah", query: "", fragment: ""}
(anonymous) @ /usr/lib/code/out/vs/workbench/workbench.main.js:119
20:39:45.279 /usr/lib/code/out/vs/workbench/workbench.main.js:119 [UriError]: Scheme is missing: {scheme: "", authority: "", path: "blahblahablahqefqefqef", query: "", fragment: ""}
(anonymous) @ /usr/lib/code/out/vs/workbench/workbench.main.js:119
20:39:45.280 /usr/lib/code/out/vs/workbench/workbench.main.js:119 [UriError]: Scheme is missing: {scheme: "", authority: "", path: "blahblahablah", query: "", fragment: ""}
(anonymous) @ /usr/lib/code/out/vs/workbench/workbench.main.js:119
20:39:45.280 /usr/lib/code/out/vs/workbench/workbench.main.js:119 [UriError]: Scheme is missing: {scheme: "", authority: "", path: "blahblahablahqefqefqef", query: "", fragment: ""}
(anonymous) @ /usr/lib/code/out/vs/workbench/workbench.main.js:119
20:39:45.931 /usr/lib/code/out/vs/workbench/workbench.main.js:276 [Extension Host] Git extension API method 'getGitPath' is deprecated.
t.log @ /usr/lib/code/out/vs/workbench/workbench.main.js:276
20:39:46.899 /usr/lib/code/out/vs/workbench/workbench.main.js:276 [Extension Host] [UriError]: Scheme is missing: {scheme: "", authority: "", path: "blahblahablah", query: "", fragment: ""}
t.log @ /usr/lib/code/out/vs/workbench/workbench.main.js:276
20:39:46.899 /usr/lib/code/out/vs/workbench/workbench.main.js:276 [Extension Host] [UriError]: Scheme is missing: {scheme: "", authority: "", path: "blahblahablahqefqefqef", query: "", fragment: ""}
t.log @ /usr/lib/code/out/vs/workbench/workbench.main.js:276
20:39:47.094 /usr/lib/code/out/vs/workbench/workbench.main.js:3263 [ms-python.python]Cannot read property 'replace' of undefined
e.$onExtensionRuntimeError @ /usr/lib/code/out/vs/workbench/workbench.main.js:3263
20:39:47.095 /usr/lib/code/out/vs/workbench/workbench.main.js:3263 TypeError: Cannot read property 'replace' of undefined
	at Object.parseVersion (/home/nico/.vscode-oss/extensions/ms-python.python-2018.9.0/out/utils/version.js:7:15)
	at getos (/home/nico/.vscode-oss/extensions/ms-python.python-2018.9.0/out/utils/platform.js:108:29)
	at /home/nico/.vscode-oss/extensions/ms-python.python-2018.9.0/node_modules/getos/index.js:66:18
	at customLogic (/home/nico/.vscode-oss/extensions/ms-python.python-2018.9.0/node_modules/getos/index.js:125:52)
	at /home/nico/.vscode-oss/extensions/ms-python.python-2018.9.0/node_modules/getos/index.js:63:16
	at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
e.$onExtensionRuntimeError @ /usr/lib/code/out/vs/workbench/workbench.main.js:3263
20:39:47.883 console.ts:136 [Extension Host] error: Unhandled Rejection at: Promise [object Promise]. Reason: Error: [GitHub.vscode-pull-request-github]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api GitHub.vscode-pull-request-github.
t.log @ console.ts:136
t._logExtensionHostMessage @ extensionHost.ts:412
(anonymous) @ extensionHost.ts:224
emitTwo @ events.js:126
emit @ events.js:214
emit @ internal/child_process.js:772
_combinedTickCallback @ internal/process/next_tick.js:141
_tickCallback @ internal/process/next_tick.js:180
20:39:47.887 console.ts:136 [Extension Host] [UriError]: Scheme is missing: {scheme: "", authority: "", path: "blahblahablah", query: "", fragment: ""}
t.log @ console.ts:136
t._logExtensionHostMessage @ extensionHost.ts:412
(anonymous) @ extensionHost.ts:224
emitTwo @ events.js:126
emit @ events.js:214
emit @ internal/child_process.js:772
_combinedTickCallback @ internal/process/next_tick.js:141
_tickCallback @ internal/process/next_tick.js:180
20:39:47.888 console.ts:136 [Extension Host] [UriError]: Scheme is missing: {scheme: "", authority: "", path: "blahblahablahqefqefqef", query: "", fragment: ""}
t.log @ console.ts:136
t._logExtensionHostMessage @ extensionHost.ts:412
(anonymous) @ extensionHost.ts:224
emitTwo @ events.js:126
emit @ events.js:214
emit @ internal/child_process.js:772
_combinedTickCallback @ internal/process/next_tick.js:141
_tickCallback @ internal/process/next_tick.js:180
20:39:48.574 console.ts:136 [Extension Host] rejected promise not handled within 1 second
t.log @ console.ts:136
t._logExtensionHostMessage @ extensionHost.ts:412
(anonymous) @ extensionHost.ts:224
emitTwo @ events.js:126
emit @ events.js:214
emit @ internal/child_process.js:772
_combinedTickCallback @ internal/process/next_tick.js:141
_tickCallback @ internal/process/next_tick.js:180
20:39:48.575 mainThreadExtensionService.ts:43 [GitHub.vscode-pull-request-github][GitHub.vscode-pull-request-github]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api GitHub.vscode-pull-request-github
e.$onExtensionRuntimeError @ mainThreadExtensionService.ts:43
e._doInvokeHandler @ rpcProtocol.ts:322
e._invokeHandler @ rpcProtocol.ts:307
e._receiveRequest @ rpcProtocol.ts:239
e._receiveOneMessage @ rpcProtocol.ts:186
(anonymous) @ rpcProtocol.ts:115
e.fire @ event.ts:140
a @ ipc.net.ts:106
n._socketDataListener @ ipc.net.ts:135
emitOne @ events.js:116
emit @ events.js:211
addChunk @ _stream_readable.js:263
readableAddChunk @ _stream_readable.js:250
Readable.push @ _stream_readable.js:208
onread @ net.js:594
20:39:48.577 mainThreadExtensionService.ts:44 Error: [GitHub.vscode-pull-request-github]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api GitHub.vscode-pull-request-github
	at ee (/usr/lib/code/out/vs/workbench/node/extensionHostProcess.js:795:383)
	at new t.PullRequestsTreeDataProvider (/home/nico/.vscode-oss/extensions/github.vscode-pull-request-github-0.1.7/media/extension.js:15:39539)
	at new w (/home/nico/.vscode-oss/extensions/github.vscode-pull-request-github-0.1.7/media/extension.js:15:49598)
	at /home/nico/.vscode-oss/extensions/github.vscode-pull-request-github-0.1.7/media/extension.js:15:164835
	at Generator.next (<anonymous>)
	at o (/home/nico/.vscode-oss/extensions/github.vscode-pull-request-github-0.1.7/media/extension.js:15:163672)
	at <anonymous>
e.$onExtensionRuntimeError @ mainThreadExtensionService.ts:44
e._doInvokeHandler @ rpcProtocol.ts:322
e._invokeHandler @ rpcProtocol.ts:307
e._receiveRequest @ rpcProtocol.ts:239
e._receiveOneMessage @ rpcProtocol.ts:186
(anonymous) @ rpcProtocol.ts:115
e.fire @ event.ts:140
a @ ipc.net.ts:106
n._socketDataListener @ ipc.net.ts:135
emitOne @ events.js:116
emit @ events.js:211
addChunk @ _stream_readable.js:263
readableAddChunk @ _stream_readable.js:250
Readable.push @ _stream_readable.js:208
onread @ net.js:594
20:39:48.578 mainThreadExtensionService.ts:43 [GitHub.vscode-pull-request-github]Cannot read property 'HEAD' of undefined
e.$onExtensionRuntimeError @ mainThreadExtensionService.ts:43
e._doInvokeHandler @ rpcProtocol.ts:322
e._invokeHandler @ rpcProtocol.ts:307
e._receiveRequest @ rpcProtocol.ts:239
e._receiveOneMessage @ rpcProtocol.ts:186
(anonymous) @ rpcProtocol.ts:115
e.fire @ event.ts:140
a @ ipc.net.ts:106
n._socketDataListener @ ipc.net.ts:135
emitOne @ events.js:116
emit @ events.js:211
addChunk @ _stream_readable.js:263
readableAddChunk @ _stream_readable.js:250
Readable.push @ _stream_readable.js:208
onread @ net.js:594
20:39:48.580 mainThreadExtensionService.ts:44 TypeError: Cannot read property 'HEAD' of undefined
	at _disposables.push.r.onDidRunGitStatus.e (/home/nico/.vscode-oss/extensions/github.vscode-pull-request-github-0.1.7/media/extension.js:15:48561)
	at e.fire (/usr/lib/code/out/vs/workbench/node/extensionHostProcess.js:99:917)
	at t.Repository.<anonymous> (/home/nico/.vscode-oss/extensions/github.vscode-pull-request-github-0.1.7/media/extension.js:1:158421)
	at Generator.next (<anonymous>)
	at o (/home/nico/.vscode-oss/extensions/github.vscode-pull-request-github-0.1.7/media/extension.js:1:156944)
	at <anonymous>
e.$onExtensionRuntimeError @ mainThreadExtensionService.ts:44
e._doInvokeHandler @ rpcProtocol.ts:322
e._invokeHandler @ rpcProtocol.ts:307
e._receiveRequest @ rpcProtocol.ts:239
e._receiveOneMessage @ rpcProtocol.ts:186
(anonymous) @ rpcProtocol.ts:115
e.fire @ event.ts:140
a @ ipc.net.ts:106
n._socketDataListener @ ipc.net.ts:135
emitOne @ events.js:116
emit @ events.js:211
addChunk @ _stream_readable.js:263
readableAddChunk @ _stream_readable.js:250
Readable.push @ _stream_readable.js:208
onread @ net.js:594
20:39:49.201 console.ts:136 [Extension Host] [UriError]: Scheme is missing: {scheme: "", authority: "", path: "blahblahablah", query: "", fragment: ""}
t.log @ console.ts:136
t._logExtensionHostMessage @ extensionHost.ts:412
(anonymous) @ extensionHost.ts:224
emitTwo @ events.js:126
emit @ events.js:214
emit @ internal/child_process.js:772
_combinedTickCallback @ internal/process/next_tick.js:141
_tickCallback @ internal/process/next_tick.js:180
20:39:49.201 console.ts:136 [Extension Host] [UriError]: Scheme is missing: {scheme: "", authority: "", path: "blahblahablahqefqefqef", query: "", fragment: ""}
t.log @ console.ts:136
t._logExtensionHostMessage @ extensionHost.ts:412
(anonymous) @ extensionHost.ts:224
emitTwo @ events.js:126
emit @ events.js:214
emit @ internal/child_process.js:772
_combinedTickCallback @ internal/process/next_tick.js:141
_tickCallback @ internal/process/next_tick.js:180
20:39:49.757 mainThreadExtensionService.ts:43 [GitHub.vscode-pull-request-github]Cannot read property 'HEAD' of undefined
e.$onExtensionRuntimeError @ mainThreadExtensionService.ts:43
e._doInvokeHandler @ rpcProtocol.ts:322
e._invokeHandler @ rpcProtocol.ts:307
e._receiveRequest @ rpcProtocol.ts:239
e._receiveOneMessage @ rpcProtocol.ts:186
(anonymous) @ rpcProtocol.ts:115
e.fire @ event.ts:140
a @ ipc.net.ts:106
n._socketDataListener @ ipc.net.ts:135
emitOne @ events.js:116
emit @ events.js:211
addChunk @ _stream_readable.js:263
readableAddChunk @ _stream_readable.js:250
Readable.push @ _stream_readable.js:208
onread @ net.js:594
20:39:49.758 mainThreadExtensionService.ts:44 TypeError: Cannot read property 'HEAD' of undefined
	at _disposables.push.r.onDidRunGitStatus.e (/home/nico/.vscode-oss/extensions/github.vscode-pull-request-github-0.1.7/media/extension.js:15:48561)
	at e.fire (/usr/lib/code/out/vs/workbench/node/extensionHostProcess.js:99:917)
	at t.Repository.<anonymous> (/home/nico/.vscode-oss/extensions/github.vscode-pull-request-github-0.1.7/media/extension.js:1:158421)
	at Generator.next (<anonymous>)
	at o (/home/nico/.vscode-oss/extensions/github.vscode-pull-request-github-0.1.7/media/extension.js:1:156944)
	at <anonymous>
e.$onExtensionRuntimeError @ mainThreadExtensionService.ts:44
e._doInvokeHandler @ rpcProtocol.ts:322
e._invokeHandler @ rpcProtocol.ts:307
e._receiveRequest @ rpcProtocol.ts:239
e._receiveOneMessage @ rpcProtocol.ts:186
(anonymous) @ rpcProtocol.ts:115
e.fire @ event.ts:140
a @ ipc.net.ts:106
n._socketDataListener @ ipc.net.ts:135
emitOne @ events.js:116
emit @ events.js:211
addChunk @ _stream_readable.js:263
readableAddChunk @ _stream_readable.js:250
Readable.push @ _stream_readable.js:208
onread @ net.js:594

```

</details>

**Comment by AamuLumi** [comment]
Here's mine:

```[GitHub.vscode-pull-request-github][GitHub.vscode-pull-request-github]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api GitHub.vscode-pull-request-github
MainThreadExtensionService.$onExtensionRuntimeError @ /usr/share/vscode/resources/app/out/vs/workbench/workbench.main.js:175063
/usr/share/vscode/resources/app/out/vs/workbench/workbench.main.js:175064 Error: [GitHub.vscode-pull-request-github]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api GitHub.vscode-pull-request-github
	at throwProposedApiError (/usr/share/vscode/resources/app/out/vs/workbench/node/extensionHostProcess.js:48977:15)
	at new t.PullRequestsTreeDataProvider (/home/aamulumi/.vscode/extensions/github.vscode-pull-request-github-0.1.7/media/extension.js:15:39539)
	at new w (/home/aamulumi/.vscode/extensions/github.vscode-pull-request-github-0.1.7/media/extension.js:15:49598)
	at /home/aamulumi/.vscode/extensions/github.vscode-pull-request-github-0.1.7/media/extension.js:15:164835
	at Generator.next (<anonymous>)
	at o (/home/aamulumi/.vscode/extensions/github.vscode-pull-request-github-0.1.7/media/extension.js:15:163672)
	at <anonymous>
MainThreadExtensionService.$onExtensionRuntimeError @ /usr/share/vscode/resources/app/out/vs/workbench/workbench.main.js:175064
/usr/share/vscode/resources/app/out/vs/workbench/workbench.main.js:175063 [GitHub.vscode-pull-request-github]Cannot read property 'HEAD' of undefined
MainThreadExtensionService.$onExtensionRuntimeError @ /usr/share/vscode/resources/app/out/vs/workbench/workbench.main.js:175063
/usr/share/vscode/resources/app/out/vs/workbench/workbench.main.js:175064 TypeError: Cannot read property 'HEAD' of undefined
	at _disposables.push.r.onDidRunGitStatus.e (/home/aamulumi/.vscode/extensions/github.vscode-pull-request-github-0.1.7/media/extension.js:15:48561)
	at Emitter.fire (/usr/share/vscode/resources/app/out/vs/workbench/node/extensionHostProcess.js:8858:38)
	at t.Repository.<anonymous> (/home/aamulumi/.vscode/extensions/github.vscode-pull-request-github-0.1.7/media/extension.js:1:158421)
	at Generator.next (<anonymous>)
	at o (/home/aamulumi/.vscode/extensions/github.vscode-pull-request-github-0.1.7/media/extension.js:1:156944)
	at <anonymous>
MainThreadExtensionService.$onExtensionRuntimeError @ /usr/share/vscode/resources/app/out/vs/workbench/workbench.main.js:175064
/usr/share/vscode/resources/app/out/vs/workbench/workbench.main.js:175063 [GitHub.vscode-pull-request-github]Cannot read property 'HEAD' of undefined
MainThreadExtensionService.$onExtensionRuntimeError @ /usr/share/vscode/resources/app/out/vs/workbench/workbench.main.js:175063
/usr/share/vscode/resources/app/out/vs/workbench/workbench.main.js:175064 TypeError: Cannot read property 'HEAD' of undefined
	at _disposables.push.r.onDidRunGitStatus.e (/home/aamulumi/.vscode/extensions/github.vscode-pull-request-github-0.1.7/media/extension.js:15:48561)
	at Emitter.fire (/usr/share/vscode/resources/app/out/vs/workbench/node/extensionHostProcess.js:8858:38)
	at t.Repository.<anonymous> (/home/aamulumi/.vscode/extensions/github.vscode-pull-request-github-0.1.7/media/extension.js:1:158421)
	at Generator.next (<anonymous>)
	at o (/home/aamulumi/.vscode/extensions/github.vscode-pull-request-github-0.1.7/media/extension.js:1:156944)
	at <anonymous>
MainThreadExtensionService.$onExtensionRuntimeError @ /usr/share/vscode/resources/app/out/vs/workbench/workbench.main.js:175064```

**Comment by RMacfarlane** [comment]
@AamuLumi I didn't look closely at the VSCode version you had in the original post. I think the problem is from that. In our builds, we have a different `product.json` that whitelists some extensions as being able to use the proposed API so that we can self-host on the API. The OSS version doesn't have this. Where are you getting your build from? If you're building it yourself, you can add

```
	"extensionAllowedProposedApi": [
		"GitHub.vscode-pull-request-github"
	]
```

otherwise, if you launch with the flag `--enable-proposed-api GitHub.vscode-pull-request-github` it should work

**Comment by NicolasHug** [comment]
I am personally using the [archlinux community package](https://www.archlinux.org/packages/community/x86_64/code/). I didn't try builting it myself, but indeed it works fine with `--enable-proposed-api GitHub.vscode-pull-request-github`.
Thanks!

**Comment by AamuLumi** [comment]
You're totally right! It works perfectly with the flag. Thanks a lot! :)

For information, I'm on Solus, so I use its packager [eopkg](https://packages.solus-project.com/shannon/v/vscode/).
