### ISSUE TITLE
Method not implemented

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode-pull-request-github#5380]
Steps to Reproduce:

1. Attempt to create a PR on github.dev
2. 🐛 See method not implemented

```
notificationsAlerts.ts:40  Error: Method not implemented.
	at Pn.diffBetween (extension.js:123:5276)
	at dy.gitFiles (extension.js:1948:2230)
	at ay.getGitChildren (extension.js:1931:7742)
	at ay.getChildren (extension.js:1931:6659)
	at v.Y (/microsoft/vs/workbench/api/worker/extensionHostWorker.js:80:16344)
	at v.getChildren (/microsoft/vs/workbench/api/worker/extensionHostWorker.js:80:12712)
	at c.$getChildren (/microsoft/vs/workbench/api/worker/extensionHostWorker.js:80:9275)
	at o.S (/microsoft/vs/workbench/api/worker/extensionHostWorker.js:84:48583)
	at o.Q (/microsoft/vs/workbench/api/worker/extensionHostWorker.js:84:48349)
	at o.M (/microsoft/vs/workbench/api/worker/extensionHostWorker.js:84:47426)
	at o.L (/microsoft/vs/workbench/api/worker/extensionHostWorker.js:84:46637)
	at R.eval [as value] (/microsoft/vs/workbench/api/worker/extensionHostWorker.js:84:45294)
	at a.y (workerMain.js:32:1902)
	at a.fire (workerMain.js:32:2119)
	at r.port1.onmessage (/microsoft/vs/workbench/api/worker/extensionHostWorker.js:91:3801)
```

**Comment by alexr00** [comment]
I'm not able to repro. I can see what's happening form the logs though, and I don't understand how we got into this situation
- The "Files Changed" and "Commits" view use either git or GitHub API.
- If the branch you're making a PR from doesn't have an upstream, we use git API
- On github.dev, the branch should always have an upstream, so we should always use GitHub API. 
- Somehow, we think that your branch doesn't have an upstream though, so we try to use git API.

@lramos15 can you think of anything special about how you were creating the PR that might cause your branch not to have an upstream?

**Comment by lramos15** [comment]
> [@lramos15](https://github.com/lramos15) can you think of anything special about how you were creating the PR that might cause your branch not to have an upstream?

No, I was just creating a PR against https://github.com/microsoft/vscode-python-debugger and followed the steps
1. Press `.` on github.com
2. Make changs
3. Switch branches
4. Commit changes
5. 🐛 Attempt to create PR

I ended up creating the PR from github.com which means GH did receive my branch.

**Comment by alexr00** [comment]
Should be fixed by https://github.com/microsoft/vscode-pull-request-github/pull/5388

**Comment by lramos15** [comment]
I can still repro
```
Error: Method not implemented.
	at Pn.diffBetween (extension.js:123:5276)
	at cy.gitFiles (extension.js:1963:2344)
	at async sy.getGitChildren (extension.js:1946:7729)
	at async p.Y (/microsoft/vs/workbench/api/worker/extensionHostWorker.js:80:66407)
	at async p.getChildren (/microsoft/vs/workbench/api/worker/extensionHostWorker.js:80:62777)
c @ workbench.web.main.js:766

```

Using github.dev with insiders
and
`v0.75.2023102612`

**Comment by alexr00** [comment]
Fix is available in pre-release. To verify:

1. Switch github.dev to use VS Code Insiders
2. Make sure you have the pre-release version of GHPRI installed in github.dev
3. Open a repo in github.dev
4. Create a new branch (Remote Repositories: Create Branch)
5. Make a commit on the branch
6. Start to create a PR (GitHub Pull Requests: Create Pull Request)
7. The Create view should open. Verify that the File Changes and Commits views are both populated correctly. Verify that you don't see an error notification with "Method not implemented".
