### ISSUE TITLE
Make hint actionable

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode-pull-request-github#5942]
Testing #5939

There is a hint about conflicts here, but no actionable:

![chrome_8V7uKGqGAX](https://github.com/microsoft/vscode-pull-request-github/assets/2931520/e3e5c702-6a02-4146-8034-fdd4db861b02)

**Comment by roblourens** [comment]
This isn't working for me. I click "Resolve Conflicts", it becomes disabled, but nothing else happens. I can add you to my private test repo if you want to see the PR but it's pretty simple, just changing the same file in the main branch and the PR branch.

When I tried on other branches, I saw the same and got some errors like these

```
2024-05-29 15:02:42.043 [error] cannot open file:///Users/roblou/code/testrepo/test2.png. Detail: File seems to be binary and cannot be opened as text: CodeExpectedError: cannot open file:///Users/roblou/code/testrepo/test2.png. Detail: File seems to be binary and cannot be opened as text
    at s.$tryOpenDocument (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2196:101536)
2024-05-29 15:03:14.785 [error] cannot open file:///Users/roblou/code/testrepo/README.md. Detail: Unable to read file '/Users/roblou/code/testrepo/README.md' (Error: Unable to resolve nonexistent file '/Users/roblou/code/testrepo/README.md'): CodeExpectedError: cannot open file:///Users/roblou/code/testrepo/README.md. Detail: Unable to read file '/Users/roblou/code/testrepo/README.md' (Error: Unable to resolve nonexistent file '/Users/roblou/code/testrepo/README.md')
    at s.$tryOpenDocument (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2196:101536)
2024-05-29 15:03:14.785 [error] cannot open file:///Users/roblou/code/testrepo/emptycommit.sh. Detail: Unable to read file '/Users/roblou/code/testrepo/emptycommit.sh' (Error: Unable to resolve nonexistent file '/Users/roblou/code/testrepo/emptycommit.sh'): CodeExpectedError: cannot open file:///Users/roblou/code/testrepo/emptycommit.sh. Detail: Unable to read file '/Users/roblou/code/testrepo/emptycommit.sh' (Error: Unable to resolve nonexistent file '/Users/roblou/code/testrepo/emptycommit.sh')
```

So I think it's not working well when the conflict is with an image or a renamed/deleted file. But also in this basic case, it didn't work and didn't log anything
