### ISSUE TITLE
`An error occurred while loading view: github:createPullRequestWebview`

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode-pull-request-github#6108]
Testing #6102

I followed the instructions in my fork of `vscode`, which github had said was synced with `main`, clicked `Revert` and saw this:

![Image](https://github.com/user-attachments/assets/69c2cb58-1110-4f9d-a8ce-b89d0b7c66a3)

I wonder if we could surface error info in the view? 

The issue was I didn't have a `main` branch in my fork, so feel free to close. 

```
mainThreadExtensionService.ts:78 [vscode.git]No such branch: main.
$onExtensionRuntimeError @ mainThreadExtensionService.ts:78
mainThreadExtensionService.ts:79 Error: No such branch: main.
    at N.getBranch (vscode-file://vscode-app/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/git/dist/main.js:2:936524)
    at T.retryRun (vscode-file://vscode-app/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/git/dist/main.js:2:1031903)
    at T.run (vscode-file://vscode-app/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/git/dist/main.js:2:1031507)
    at T.getBranch (vscode-file://vscode-app/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/git/dist/main.js:2:1019856)
    at ml.getCreateParams (vscode-file://vscode-app/Applications/code-insiders-portable-data/extensions/github.vscode-pull-request-github-0.93.2024072304/dist/extension.js:2198:5496)
    at ml.getCreateParams (vscode-file://vscode-app/Applications/code-insiders-portable-data/extensions/github.vscode-pull-request-github-0.93.2024072304/dist/extension.js:2216:3294)
    at ml.doInitializeParams (vscode-file://vscode-app/Applications/code-insiders-portable-data/extensions/github.vscode-pull-request-github-0.93.2024072304/dist/extension.js:2198:7883)
```

**Comment by alexr00** [comment]
There are probably other things that won't work right if you don't have your repo's default branch, but this is easy enough to improve.
