### ISSUE TITLE
SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-pull-request-github#751]
I see this in developer tools in one window. I haven't been using the extension in this window. I see it every time I reload the window. It's a multiroot workspace if that helps.

```
 ERR Unexpected end of JSON input: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.t.fromPRUri (/Users/roblou/.vscode-insiders/extensions/github.vscode-pull-request-github-insiders-0.345.0/media/extension.js:1:53851)
    at t.FileTypeDecorationProvider.provideDecoration (/Users/roblou/.vscode-insiders/extensions/github.vscode-pull-request-github-insiders-0.345.0/media/extension.js:8:6595)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:529:104
    at Array.map (<anonymous>)
    at e.$provideDecorations (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:528:972)
    at t._doInvokeHandler (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:658:837)
    at t._invokeHandler (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:658:509)
    at t._receiveRequest (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:657:60)
    at t._receiveOneMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:656:59)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:653:895
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:130:793
    at e.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:133:218)
    at a (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:186:147)
    at Socket.n._socketDataListener (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:186:368)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
```

**Comment by roblourens** [comment]
This is happening again, same error

**Comment by rebornix** [comment]
@roblourens are you using Nightly build?

**Comment by roblourens** [comment]
Yes

**Comment by rebornix** [comment]
@roblourens the nightly build is broken due to vsce on Nodejs 10.14 https://github.com/Microsoft/vscode-vsce/pull/314 , already fixed and published a new release, which contains the fix I mentioned above.
