### ISSUE TITLE
View on SCM viewlet: View descriptor pr not found

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode-pull-request-github#975]
Issue Type: <b>Bug</b>

Testing [Microsoft/vscode#69255](https://github.com/Microsoft/vscode/issues/69255)

When clicking file link in description editor:

![image](https://user-images.githubusercontent.com/9205389/53330055-d98fdf00-38ed-11e9-955c-18ca8e505229.png)

```
stack trace: Error: view descriptor pr not found
    at e.find (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4566:256)
    at e.setVisible (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4565:53)
    at d.toggleViewVisibility (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4586:384)
    at d.openView (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4584:167)
    at viewletService.openViewlet.then.i (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4570:925)
    at process._tickCallback (internal/process/next_tick.js:68:7) (at define.then.t.onMessage.process.on.t.catch.t (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:700:984))
```

Extension version: 1.50.0
VS Code version: Code - Insiders 1.32.0-insider (393b48d4a5de85b6fa1d2ad0a59588d6715e12ea, 2019-02-25T01:33:51.804Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.20GB free)|
|Process Argv|--extensions-dir /Users/chrmarti/Development/repos/tmp/ext --user-data-dir /Users/chrmarti/Development/repos/tmp/user pullrequest-demo|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by joaomoreno** [comment]
I get the same error but in a different situation:

1. Disable "Show in SCM"
2. Click a file link

The SCM viewlet gets revealed and the following error comes up in dev tools:

```
  ERR view descriptor pr not found: Error: view descriptor pr not found
    at e.find (file:///var/lib/snapd/snap/code-insiders/71/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:4566:256)
    at e.setVisible (file:///var/lib/snapd/snap/code-insiders/71/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:4565:53)
    at se.openView (file:///var/lib/snapd/snap/code-insiders/71/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:4833:247)
    at viewletService.openViewlet.then.i (file:///var/lib/snapd/snap/code-insiders/71/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:4570:925)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by RMacfarlane** [comment]
I forgot to re-trigger the build after checking in a fix for this on Friday, could one of you reverify with the most recent version of the extension? (1.56.0) Should already be fixed.

**Comment by chrmarti** [comment]
Verified in 1.56.0.
